"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class AssignOrganizationUserRolesRequestTypedDict(TypedDict):
    request_body: List[str]
    r"""Editable details about the user's roles."""
    organization_id: str
    r"""The unique identifier of the organization"""
    user_id: str
    r"""The unique identifier of the user"""


class AssignOrganizationUserRolesRequest(BaseModel):
    request_body: Annotated[
        List[str], FieldMetadata(request=RequestMetadata(media_type="application/json"))
    ]
    r"""Editable details about the user's roles."""

    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the organization"""

    user_id: Annotated[
        str,
        pydantic.Field(alias="userId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the user"""


class AssignOrganizationUserRolesResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class AssignOrganizationUserRolesResponse(BaseModel):
    headers: Dict[str, List[str]]
