"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .metricvalueupsertion import MetricValueUpsertion, MetricValueUpsertionTypedDict
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class BatchUpsertionMetricValuesRequestTypedDict(TypedDict):
    program_id: str
    r"""The unique identifier of the program"""
    metric_id: str
    r"""The unique identifier of the metric"""
    metric_value_upsertion: MetricValueUpsertionTypedDict
    r"""The metric values to upsert"""


class BatchUpsertionMetricValuesRequest(BaseModel):
    program_id: Annotated[
        str,
        pydantic.Field(alias="programId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the program"""

    metric_id: Annotated[
        str,
        pydantic.Field(alias="metricId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the metric"""

    metric_value_upsertion: Annotated[
        MetricValueUpsertion,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The metric values to upsert"""


class BatchUpsertionMetricValuesResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class BatchUpsertionMetricValuesResponse(BaseModel):
    headers: Dict[str, List[str]]
