"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata


CHAINS_GET_COMMANDS_OP_SERVERS = [
    # EU
    "https://h.eu.wdesk.com/s/wdata/oc/api",
    # US
    "https://h.app.wdesk.com/s/wdata/oc/api",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/oc/api",
]


class ChainsGetCommandsRequestTypedDict(TypedDict):
    environment_id: str
    r"""The ID of the Environment."""
    chain_id: str
    r"""The ID of the Chain."""


class ChainsGetCommandsRequest(BaseModel):
    environment_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the Environment."""

    chain_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the Chain."""
