"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chainrunpageresponse import ChainRunPageResponse, ChainRunPageResponseTypedDict
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata


CHAINS_CHAIN_RUN_HISTORY_OP_SERVERS = [
    # US
    "https://h.app.wdesk.com/s/wdata/oc/api",
    # EU
    "https://h.eu.wdesk.com/s/wdata/oc/api",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/oc/api",
]


class ChainsChainRunHistoryRequestTypedDict(TypedDict):
    chain_id: str
    r"""The ID of the Chain."""
    environment_id: str
    r"""The ID of the Environment."""
    cursor: NotRequired[str]
    r"""Cursor value returned from the API, indicating page information."""
    end_date: NotRequired[str]
    r"""End Date (Unix timestamp)."""
    limit: NotRequired[str]
    r"""Limit number of chainRuns returned (max 50)."""
    start_date: NotRequired[str]
    r"""Start Date (Unix timestamp)."""


class ChainsChainRunHistoryRequest(BaseModel):
    chain_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the Chain."""

    environment_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the Environment."""

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cursor value returned from the API, indicating page information."""

    end_date: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""End Date (Unix timestamp)."""

    limit: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Limit number of chainRuns returned (max 50)."""

    start_date: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Start Date (Unix timestamp)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cursor", "end_date", "limit", "start_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ChainsChainRunHistoryResponseTypedDict(TypedDict):
    result: ChainRunPageResponseTypedDict


class ChainsChainRunHistoryResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ChainsChainRunHistoryResponse]],
        Callable[[], Awaitable[Optional[ChainsChainRunHistoryResponse]]],
    ]

    result: ChainRunPageResponse
