"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chainrunpageresponse import ChainRunPageResponse, ChainRunPageResponseTypedDict
from enum import Enum
from pydantic import model_serializer
from typing import Awaitable, Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, QueryParamMetadata


CHAINS_CHAIN_FILTER_SEARCH_OP_SERVERS = [
    # US
    "https://h.app.wdesk.com/s/wdata/oc/api",
    # EU
    "https://h.eu.wdesk.com/s/wdata/oc/api",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/oc/api",
]


class Sort(str, Enum):
    r"""Sort direction (by date)."""

    DESC = "desc"
    ASC = "asc"


class QueryParamState(str, Enum):
    r"""The state of the Chain Run."""

    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    PAUSED = "paused"
    WARNED = "warned"
    COMPLETED = "completed"


class ChainsChainFilterSearchRequestTypedDict(TypedDict):
    chain_id: NotRequired[List[str]]
    r"""The ID(s) of the Chains to return."""
    cursor: NotRequired[str]
    r"""Cursor value returned from the API, indicating page information."""
    end_date: NotRequired[str]
    r"""End Date (Unix timestamp)."""
    environment_id: NotRequired[List[str]]
    r"""The ID(s) of the Environments to search. Not required for superusers or company admins."""
    sort: NotRequired[Sort]
    r"""Sort direction (by date)."""
    start_date: NotRequired[str]
    r"""Start Date (Unix timestamp)."""
    state: NotRequired[QueryParamState]
    r"""The state of the Chain Run."""


class ChainsChainFilterSearchRequest(BaseModel):
    chain_id: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""The ID(s) of the Chains to return."""

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cursor value returned from the API, indicating page information."""

    end_date: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""End Date (Unix timestamp)."""

    environment_id: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""The ID(s) of the Environments to search. Not required for superusers or company admins."""

    sort: Annotated[
        Optional[Sort],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Sort direction (by date)."""

    start_date: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Start Date (Unix timestamp)."""

    state: Annotated[
        Optional[QueryParamState],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The state of the Chain Run."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "chain_id",
                "cursor",
                "end_date",
                "environment_id",
                "sort",
                "start_date",
                "state",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ChainsChainFilterSearchResponseTypedDict(TypedDict):
    result: ChainRunPageResponseTypedDict


class ChainsChainFilterSearchResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ChainsChainFilterSearchResponse]],
        Callable[[], Awaitable[Optional[ChainsChainFilterSearchResponse]]],
    ]

    result: ChainRunPageResponse
