"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .metricvalue import MetricValueInput, MetricValueInputTypedDict
import pydantic
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class CreateValueRequestTypedDict(TypedDict):
    program_id: str
    r"""The unique identifier of the program"""
    metric_id: str
    r"""The unique identifier of the metric"""
    metric_value: MetricValueInputTypedDict
    r"""The properties of the metric value to create"""


class CreateValueRequest(BaseModel):
    program_id: Annotated[
        str,
        pydantic.Field(alias="programId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the program"""

    metric_id: Annotated[
        str,
        pydantic.Field(alias="metricId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the metric"""

    metric_value: Annotated[
        MetricValueInput,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The properties of the metric value to create"""
