"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from workiva import utils


class DestinationLinkStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Destination link status"""

    CONNECTED = "connected"
    DISCONNECTED = "disconnected"
