"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class DimensionValueTypedDict(TypedDict):
    r"""Data model for a dimension value"""

    active: NotRequired[bool]
    r"""Indicates whether the dimension value is available for use in new metrics."""
    id: NotRequired[str]
    r"""A user-entered, unique identifier for the dimension value, up to 20 characters."""
    name: NotRequired[Nullable[str]]
    r"""The name of the dimension value, up to 300 characters. If not provided, defaults to the value of 'id'."""


class DimensionValue(BaseModel):
    r"""Data model for a dimension value"""

    active: Optional[bool] = True
    r"""Indicates whether the dimension value is available for use in new metrics."""

    id: Optional[str] = None
    r"""A user-entered, unique identifier for the dimension value, up to 20 characters."""

    name: OptionalNullable[str] = UNSET
    r"""The name of the dimension value, up to 300 characters. If not provided, defaults to the value of 'id'."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["active", "id", "name"])
        nullable_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
