"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .drawingelement import DrawingElement, DrawingElementTypedDict
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class DrawingElementListResultTypedDict(TypedDict):
    r"""A collection of elements in a drawing. This contains the shapes, text boxes, and lines for drawing content including slides, layout slides, and drawings in documents. When there are no additional elements before the current  collection, the previous property will be null. When there are no additional elements after the current collection, the next property will be null."""

    data: List[DrawingElementTypedDict]
    r"""Elements contained by this drawing."""
    at_next_link: NotRequired[Nullable[str]]
    r"""Pagination link for next set of results"""


class DrawingElementListResult(BaseModel):
    r"""A collection of elements in a drawing. This contains the shapes, text boxes, and lines for drawing content including slides, layout slides, and drawings in documents. When there are no additional elements before the current  collection, the previous property will be null. When there are no additional elements after the current collection, the next property will be null."""

    data: List[DrawingElement]
    r"""Elements contained by this drawing."""

    at_next_link: Annotated[
        OptionalNullable[str], pydantic.Field(alias="@nextLink")
    ] = UNSET
    r"""Pagination link for next set of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["@nextLink"])
        nullable_fields = set(["@nextLink"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
