"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filecopyoptions import FileCopyOptions, FileCopyOptionsTypedDict
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class FileCopyTypedDict(TypedDict):
    r"""Details about a file copy including the destination container and options"""

    destination_container: NotRequired[Nullable[str]]
    r"""The unique id of the destination container to copy to. Omit this field to specify the root container. Specifying an empty string is invalid."""
    options: NotRequired[Nullable[FileCopyOptionsTypedDict]]
    r"""Additional options for the file copy. If no options are provided, all options default to false.

    """


class FileCopy(BaseModel):
    r"""Details about a file copy including the destination container and options"""

    destination_container: Annotated[
        OptionalNullable[str], pydantic.Field(alias="destinationContainer")
    ] = UNSET
    r"""The unique id of the destination container to copy to. Omit this field to specify the root container. Specifying an empty string is invalid."""

    options: OptionalNullable[FileCopyOptions] = UNSET
    r"""Additional options for the file copy. If no options are provided, all options default to false.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["destinationContainer", "options"])
        nullable_fields = set(["destinationContainer", "options"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    FileCopy.model_rebuild()
except NameError:
    pass
