"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .color import Color, ColorTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class FillTypedDict(TypedDict):
    r"""A shape or box fill settings for things like shapes. Use a null to indicate no fill."""

    color: ColorTypedDict
    r"""Represents a color."""
    opacity: NotRequired[float]
    r"""The opacity of a color where 1.0 is completely opaque and 0.0 is completely transparent."""


class Fill(BaseModel):
    r"""A shape or box fill settings for things like shapes. Use a null to indicate no fill."""

    color: Color
    r"""Represents a color."""

    opacity: Optional[float] = 1
    r"""The opacity of a color where 1.0 is completely opaque and 0.0 is completely transparent."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["opacity"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
