"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata


class GetActivityByIDRequestTypedDict(TypedDict):
    activity_id: str
    r"""The unique identifier of the activity"""


class GetActivityByIDRequest(BaseModel):
    activity_id: Annotated[
        str,
        pydantic.Field(alias="activityId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the activity"""
