"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel


class GraphReportExportFormat(str, Enum):
    r"""The format to export the graph report to - curently, only .CSV"""

    CSV = "csv"


class GraphReportExportTypedDict(TypedDict):
    r"""Details about a graph report export."""

    format_: GraphReportExportFormat
    r"""The format to export the graph report to - curently, only .CSV"""


class GraphReportExport(BaseModel):
    r"""Details about a graph report export."""

    format_: Annotated[GraphReportExportFormat, pydantic.Field(alias="format")]
    r"""The format to export the graph report to - curently, only .CSV"""


try:
    GraphReportExport.model_rebuild()
except NameError:
    pass
