"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hyperlinktype import HyperlinkType
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva import models
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class HyperlinkDocumentTypedDict(TypedDict):
    r"""The reference to the linked document for `document` type hyperlinks"""

    document: NotRequired[str]
    r"""The unique identifier of the document being referred to"""
    revision: NotRequired[str]


class HyperlinkDocument(BaseModel):
    r"""The reference to the linked document for `document` type hyperlinks"""

    document: Optional[str] = None
    r"""The unique identifier of the document being referred to"""

    revision: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["document", "revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HyperlinkSectionTypedDict(TypedDict):
    r"""The reference to the linked section for `section` type hyperlinks"""

    document: NotRequired[str]
    r"""The unique identifier of the document containing the section being referred to"""
    revision: NotRequired[str]
    r"""The revision of the document and section being referred to"""
    section: NotRequired[str]
    r"""The unique identifier of the section being referred to"""


class HyperlinkSection(BaseModel):
    r"""The reference to the linked section for `section` type hyperlinks"""

    document: Optional[str] = None
    r"""The unique identifier of the document containing the section being referred to"""

    revision: Optional[str] = None
    r"""The revision of the document and section being referred to"""

    section: Optional[str] = None
    r"""The unique identifier of the section being referred to"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["document", "revision", "section"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HyperlinkSpreadsheetTypedDict(TypedDict):
    r"""The reference to the linked spreadsheet for `spreadsheet` type hyperlinks"""

    spreadsheet: NotRequired[str]
    r"""The unique identifier of the spreadsheet being referred to"""
    revision: NotRequired[str]


class HyperlinkSpreadsheet(BaseModel):
    r"""The reference to the linked spreadsheet for `spreadsheet` type hyperlinks"""

    spreadsheet: Optional[str] = None
    r"""The unique identifier of the spreadsheet being referred to"""

    revision: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["spreadsheet", "revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HyperlinkSheetTypedDict(TypedDict):
    r"""The reference to the linked sheet for `sheet` type hyperlinks"""

    sheet: NotRequired[str]
    r"""The unique identifier of the sheet being referred to"""
    spreadsheet: NotRequired[str]
    r"""The unique identifier of the spreadsheet containing the sheet being referred to"""
    revision: NotRequired[str]


class HyperlinkSheet(BaseModel):
    r"""The reference to the linked sheet for `sheet` type hyperlinks"""

    sheet: Optional[str] = None
    r"""The unique identifier of the sheet being referred to"""

    spreadsheet: Optional[str] = None
    r"""The unique identifier of the spreadsheet containing the sheet being referred to"""

    revision: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sheet", "spreadsheet", "revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HyperlinkPresentationTypedDict(TypedDict):
    r"""The reference to the linked presentation for `presentation` type hyperlinks"""

    presentation: NotRequired[str]
    r"""The unique identifier of the presentation being referred to"""
    revision: NotRequired[str]


class HyperlinkPresentation(BaseModel):
    r"""The reference to the linked presentation for `presentation` type hyperlinks"""

    presentation: Optional[str] = None
    r"""The unique identifier of the presentation being referred to"""

    revision: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["presentation", "revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HyperlinkSlideTypedDict(TypedDict):
    r"""The reference to the linked slide for `slide` type hyperlinks"""

    slide: NotRequired[str]
    r"""The unique identifier of the slide being referred to"""
    presentation: NotRequired[str]
    r"""The unique identifier of the presentation containing the slide being referred to"""
    revision: NotRequired[str]


class HyperlinkSlide(BaseModel):
    r"""The reference to the linked slide for `slide` type hyperlinks"""

    slide: Optional[str] = None
    r"""The unique identifier of the slide being referred to"""

    presentation: Optional[str] = None
    r"""The unique identifier of the presentation containing the slide being referred to"""

    revision: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["slide", "presentation", "revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HyperlinkTypedDict(TypedDict):
    r"""Represents a hyperlink to another location. The `type` property will determine which of the other properties is set."""

    type: HyperlinkType
    r"""The type of the hyperlink"""
    document: NotRequired[Nullable[HyperlinkDocumentTypedDict]]
    r"""The reference to the linked document for `document` type hyperlinks"""
    section: NotRequired[Nullable[HyperlinkSectionTypedDict]]
    r"""The reference to the linked section for `section` type hyperlinks"""
    spreadsheet: NotRequired[Nullable[HyperlinkSpreadsheetTypedDict]]
    r"""The reference to the linked spreadsheet for `spreadsheet` type hyperlinks"""
    sheet: NotRequired[Nullable[HyperlinkSheetTypedDict]]
    r"""The reference to the linked sheet for `sheet` type hyperlinks"""
    presentation: NotRequired[Nullable[HyperlinkPresentationTypedDict]]
    r"""The reference to the linked presentation for `presentation` type hyperlinks"""
    slide: NotRequired[Nullable[HyperlinkSlideTypedDict]]
    r"""The reference to the linked slide for `slide` type hyperlinks"""
    url: NotRequired[Nullable[str]]
    r"""The raw URL for `url` type hyperlinks."""


class Hyperlink(BaseModel):
    r"""Represents a hyperlink to another location. The `type` property will determine which of the other properties is set."""

    type: HyperlinkType
    r"""The type of the hyperlink"""

    document: OptionalNullable[HyperlinkDocument] = UNSET
    r"""The reference to the linked document for `document` type hyperlinks"""

    section: OptionalNullable[HyperlinkSection] = UNSET
    r"""The reference to the linked section for `section` type hyperlinks"""

    spreadsheet: OptionalNullable[HyperlinkSpreadsheet] = UNSET
    r"""The reference to the linked spreadsheet for `spreadsheet` type hyperlinks"""

    sheet: OptionalNullable[HyperlinkSheet] = UNSET
    r"""The reference to the linked sheet for `sheet` type hyperlinks"""

    presentation: OptionalNullable[HyperlinkPresentation] = UNSET
    r"""The reference to the linked presentation for `presentation` type hyperlinks"""

    slide: OptionalNullable[HyperlinkSlide] = UNSET
    r"""The reference to the linked slide for `slide` type hyperlinks"""

    url: OptionalNullable[str] = UNSET
    r"""The raw URL for `url` type hyperlinks."""

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.HyperlinkType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "document",
                "section",
                "spreadsheet",
                "sheet",
                "presentation",
                "slide",
                "url",
            ]
        )
        nullable_fields = set(
            [
                "document",
                "section",
                "spreadsheet",
                "sheet",
                "presentation",
                "slide",
                "url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
