"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from workiva import utils


class LineSpacingUnit(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The units for a line spacing value as a percent of line height or points."""

    PERCENT = "percent"
    POINTS = "points"
