"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .styleref import StyleRef, StyleRefTypedDict
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ListFormatTypedDict(TypedDict):
    r"""The list formatting options applied to the given paragraph."""

    level: NotRequired[int]
    r"""The list level associated with the list."""
    prefix: NotRequired[Nullable[str]]
    r"""The list value prefix"""
    start_at: NotRequired[Nullable[int]]
    r"""The value the list starts at (for ordered lists). Null indicates that the list continues from the previous item."""
    style: NotRequired[StyleRefTypedDict]
    r"""A reference to a style."""
    suffix: NotRequired[Nullable[str]]
    r"""The list value suffix"""


class ListFormat(BaseModel):
    r"""The list formatting options applied to the given paragraph."""

    level: Optional[int] = None
    r"""The list level associated with the list."""

    prefix: OptionalNullable[str] = UNSET
    r"""The list value prefix"""

    start_at: Annotated[OptionalNullable[int], pydantic.Field(alias="startAt")] = UNSET
    r"""The value the list starts at (for ordered lists). Null indicates that the list continues from the previous item."""

    style: Optional[StyleRef] = None
    r"""A reference to a style."""

    suffix: OptionalNullable[str] = UNSET
    r"""The list value suffix"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["level", "prefix", "startAt", "style", "suffix"])
        nullable_fields = set(["prefix", "startAt", "suffix"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ListFormat.model_rebuild()
except NameError:
    pass
