"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .graphattachment import GraphAttachment, GraphAttachmentTypedDict
from .samplecell import SampleCell, SampleCellTypedDict
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class MatrixSampleTypedDict(TypedDict):
    r"""This object represents a single row of a matrix."""

    attachments: NotRequired[Nullable[List[GraphAttachmentTypedDict]]]
    r"""An optional array of partial information about the attachments on the matrix sample. To include in the response, provide the query parameter `$expand=attachments`."""
    data_values: NotRequired[Nullable[List[SampleCellTypedDict]]]
    r"""An array of SampleCell values representing the values for each data column of the sample matrix's cells"""
    id: NotRequired[str]
    r"""The unique ID of the matrix sample"""
    result_values: NotRequired[Nullable[List[SampleCellTypedDict]]]
    r"""An array of SampleCell values representing the values for each result cell in the sample matrix's cells."""


class MatrixSample(BaseModel):
    r"""This object represents a single row of a matrix."""

    attachments: OptionalNullable[List[GraphAttachment]] = UNSET
    r"""An optional array of partial information about the attachments on the matrix sample. To include in the response, provide the query parameter `$expand=attachments`."""

    data_values: Annotated[
        OptionalNullable[List[SampleCell]], pydantic.Field(alias="dataValues")
    ] = UNSET
    r"""An array of SampleCell values representing the values for each data column of the sample matrix's cells"""

    id: Optional[str] = None
    r"""The unique ID of the matrix sample"""

    result_values: Annotated[
        OptionalNullable[List[SampleCell]], pydantic.Field(alias="resultValues")
    ] = UNSET
    r"""An array of SampleCell values representing the values for each result cell in the sample matrix's cells."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attachments", "dataValues", "id", "resultValues"])
        nullable_fields = set(["attachments", "dataValues", "resultValues"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
