"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .graphattachment import GraphAttachment, GraphAttachmentTypedDict
from .matrixcolumn import MatrixColumn, MatrixColumnTypedDict
from .matrixsample import MatrixSample, MatrixSampleTypedDict
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class MatrixTypedDict(TypedDict):
    r"""Details about a matrix, including its name and ID."""

    attachments: NotRequired[Nullable[List[GraphAttachmentTypedDict]]]
    r"""An optional array of partial information about the attachments on the matrix. To include in the response, provide the query string `$expand=attachments`."""
    data_columns: NotRequired[Nullable[List[MatrixColumnTypedDict]]]
    r"""An array of the data columns in the matrix"""
    id: NotRequired[Nullable[str]]
    r"""The unique identifier of the matrix"""
    name: NotRequired[str]
    r"""The name of the matrix"""
    result_columns: NotRequired[List[MatrixColumnTypedDict]]
    r"""An array of the result columns in the matrix"""
    samples: NotRequired[Nullable[List[MatrixSampleTypedDict]]]
    r"""An optional array of partial information about the samples on the matrix. To include in the response, provide the query parameter `$expand=samples`. To include the samples' attachments, provide the parameter `$expand=samples,samples.attachments`."""


class Matrix(BaseModel):
    r"""Details about a matrix, including its name and ID."""

    attachments: OptionalNullable[List[GraphAttachment]] = UNSET
    r"""An optional array of partial information about the attachments on the matrix. To include in the response, provide the query string `$expand=attachments`."""

    data_columns: Annotated[
        OptionalNullable[List[MatrixColumn]], pydantic.Field(alias="dataColumns")
    ] = UNSET
    r"""An array of the data columns in the matrix"""

    id: OptionalNullable[str] = UNSET
    r"""The unique identifier of the matrix"""

    name: Optional[str] = None
    r"""The name of the matrix"""

    result_columns: Annotated[
        Optional[List[MatrixColumn]], pydantic.Field(alias="resultColumns")
    ] = None
    r"""An array of the result columns in the matrix"""

    samples: OptionalNullable[List[MatrixSample]] = UNSET
    r"""An optional array of partial information about the samples on the matrix. To include in the response, provide the query parameter `$expand=samples`. To include the samples' attachments, provide the parameter `$expand=samples,samples.attachments`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["attachments", "dataColumns", "id", "name", "resultColumns", "samples"]
        )
        nullable_fields = set(["attachments", "dataColumns", "id", "samples"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    Matrix.model_rebuild()
except NameError:
    pass
