"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .metricvalue_output import MetricValue, MetricValueTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class MetricValueUpsertionTypedDict(TypedDict):
    data: NotRequired[List[MetricValueTypedDict]]
    r"""An array of metric values, each representing a metric value data record belonging to a specific metric."""


class MetricValueUpsertion(BaseModel):
    data: Optional[List[MetricValue]] = None
    r"""An array of metric values, each representing a metric value data record belonging to a specific metric."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
