"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .milestoneresourcetype import MilestoneResourceType
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva import models
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class MilestoneResourceRefDocumentTypedDict(TypedDict):
    r"""The reference to the document for `document` type milestone"""

    document: NotRequired[str]
    r"""The unique identifier of the document being referred to"""
    revision: NotRequired[str]


class MilestoneResourceRefDocument(BaseModel):
    r"""The reference to the document for `document` type milestone"""

    document: Optional[str] = None
    r"""The unique identifier of the document being referred to"""

    revision: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["document", "revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MilestoneResourceRefPresentationTypedDict(TypedDict):
    r"""The reference to the presentation for `presentation` type milestone"""

    presentation: NotRequired[str]
    r"""The unique identifier of the presentation being referred to"""
    revision: NotRequired[str]


class MilestoneResourceRefPresentation(BaseModel):
    r"""The reference to the presentation for `presentation` type milestone"""

    presentation: Optional[str] = None
    r"""The unique identifier of the presentation being referred to"""

    revision: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["presentation", "revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MilestoneResourceRefSpreadsheetTypedDict(TypedDict):
    r"""The reference to the spreadsheet for `spreadsheet` type milestone"""

    spreadsheet: NotRequired[str]
    r"""The unique identifier of the spreadsheet being referred to"""
    revision: NotRequired[str]


class MilestoneResourceRefSpreadsheet(BaseModel):
    r"""The reference to the spreadsheet for `spreadsheet` type milestone"""

    spreadsheet: Optional[str] = None
    r"""The unique identifier of the spreadsheet being referred to"""

    revision: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["spreadsheet", "revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MilestoneResourceRefTypedDict(TypedDict):
    r"""Represents a reference to the resource associated with a milestone. The `type` property will determine which of the other properties is set."""

    type: MilestoneResourceType
    r"""The type of content associated with a milestone."""
    document: NotRequired[Nullable[MilestoneResourceRefDocumentTypedDict]]
    r"""The reference to the document for `document` type milestone"""
    presentation: NotRequired[Nullable[MilestoneResourceRefPresentationTypedDict]]
    r"""The reference to the presentation for `presentation` type milestone"""
    spreadsheet: NotRequired[Nullable[MilestoneResourceRefSpreadsheetTypedDict]]
    r"""The reference to the spreadsheet for `spreadsheet` type milestone"""


class MilestoneResourceRef(BaseModel):
    r"""Represents a reference to the resource associated with a milestone. The `type` property will determine which of the other properties is set."""

    type: MilestoneResourceType
    r"""The type of content associated with a milestone."""

    document: OptionalNullable[MilestoneResourceRefDocument] = UNSET
    r"""The reference to the document for `document` type milestone"""

    presentation: OptionalNullable[MilestoneResourceRefPresentation] = UNSET
    r"""The reference to the presentation for `presentation` type milestone"""

    spreadsheet: OptionalNullable[MilestoneResourceRefSpreadsheet] = UNSET
    r"""The reference to the spreadsheet for `spreadsheet` type milestone"""

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.MilestoneResourceType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["document", "presentation", "spreadsheet"])
        nullable_fields = set(["document", "presentation", "spreadsheet"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
