"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bulkworkspacegroupmembersmodification import (
    BulkWorkspaceGroupMembersModification,
    BulkWorkspaceGroupMembersModificationTypedDict,
)
import pydantic
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class ModifyWorkspaceGroupMembersRequestTypedDict(TypedDict):
    organization_id: str
    r"""The unique identifier of the organization"""
    workspace_id: str
    r"""The unique identifier of the workspace"""
    group_id: str
    r"""The unique identifier of the group"""
    bulk_workspace_group_members_modification: (
        BulkWorkspaceGroupMembersModificationTypedDict
    )
    r"""Details about the group member modification."""


class ModifyWorkspaceGroupMembersRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the organization"""

    workspace_id: Annotated[
        str,
        pydantic.Field(alias="workspaceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the workspace"""

    group_id: Annotated[
        str,
        pydantic.Field(alias="groupId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the group"""

    bulk_workspace_group_members_modification: Annotated[
        BulkWorkspaceGroupMembersModification,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Details about the group member modification."""
