"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing_extensions import TypedDict
from workiva.types import BaseModel, Nullable, UNSET_SENTINEL


class PaddingsTypedDict(TypedDict):
    r"""The paddings of a rectangle for properties of objects such as a shape, text box, or page."""

    bottom: Nullable[float]
    r"""The bottom edge padding in points."""
    left: Nullable[float]
    r"""The left edge padding in points."""
    right: Nullable[float]
    r"""The right edge padding in points."""
    top: Nullable[float]
    r"""The top edge padding in points."""


class Paddings(BaseModel):
    r"""The paddings of a rectangle for properties of objects such as a shape, text box, or page."""

    bottom: Nullable[float]
    r"""The bottom edge padding in points."""

    left: Nullable[float]
    r"""The left edge padding in points."""

    right: Nullable[float]
    r"""The right edge padding in points."""

    top: Nullable[float]
    r"""The top edge padding in points."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
