"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tabledto import TableDto, TableDtoTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class PagedResponseTableDtoTypedDict(TypedDict):
    body: NotRequired[List[TableDtoTypedDict]]
    code: NotRequired[int]
    cursor: NotRequired[str]


class PagedResponseTableDto(BaseModel):
    body: Optional[List[TableDto]] = None

    code: Optional[int] = None

    cursor: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body", "code", "cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
