"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ParagraphPropertiesAlignment(str, Enum):
    r"""Indicates the horizontal alignment of the text within a paragraph"""

    LEFT = "left"
    CENTER = "center"
    RIGHT = "right"
    JUSTIFIED = "justified"
