"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jsonpatchoperation import JSONPatchOperation, JSONPatchOperationTypedDict
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class PartiallyUpdateMetricByIDRequestTypedDict(TypedDict):
    program_id: str
    r"""The unique identifier of the program"""
    metric_id: str
    r"""The unique identifier of the metric"""
    request_body: List[JSONPatchOperationTypedDict]
    r"""A collection of patch operations to apply to the [metric](ref:sustainability#metric). Currently only one operation may be applied at a time."""


class PartiallyUpdateMetricByIDRequest(BaseModel):
    program_id: Annotated[
        str,
        pydantic.Field(alias="programId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the program"""

    metric_id: Annotated[
        str,
        pydantic.Field(alias="metricId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the metric"""

    request_body: Annotated[
        List[JSONPatchOperation],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""A collection of patch operations to apply to the [metric](ref:sustainability#metric). Currently only one operation may be applied at a time."""
