"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jsonpatchoperation import JSONPatchOperation, JSONPatchOperationTypedDict
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class PartiallyUpdateDocumentByIDRequestTypedDict(TypedDict):
    request_body: List[JSONPatchOperationTypedDict]
    r"""A collection of patch operations to apply to the document."""
    document_id: str
    r"""The unique identifier of the document"""


class PartiallyUpdateDocumentByIDRequest(BaseModel):
    request_body: Annotated[
        List[JSONPatchOperation],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""A collection of patch operations to apply to the document."""

    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the document"""


class PartiallyUpdateDocumentByIDResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class PartiallyUpdateDocumentByIDResponse(BaseModel):
    headers: Dict[str, List[str]]
