"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class PivotViewDefinitionRowDtoType(str, Enum):
    r"""The column type."""

    INTEGER = "integer"
    NUMBER = "number"
    BOOLEAN = "boolean"
    TIMESTAMP = "timestamp"
    DATE = "date"
    STRING = "string"
    FLOAT = "float"


class PivotViewDefinitionRowDtoTypedDict(TypedDict):
    name: str
    r"""Name of the pivot view row. The maximum size is 255 characters."""
    type: NotRequired[PivotViewDefinitionRowDtoType]
    r"""The column type."""


class PivotViewDefinitionRowDto(BaseModel):
    name: str
    r"""Name of the pivot view row. The maximum size is 255 characters."""

    type: Optional[PivotViewDefinitionRowDtoType] = None
    r"""The column type."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
