"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from pydantic import field_serializer
from typing_extensions import Annotated, TypedDict
from workiva import models, utils
from workiva.types import BaseModel


class System(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The name of the system holding this reference."""

    PREP = "prep"
    SPREADSHEETS = "spreadsheets"
    QUERIES = "queries"
    PROGRAM = "program"
    COM = "com"
    IAM = "iam"
    GRAPH = "graph"
    EXPLORER = "explorer"
    PROGRAM_V2 = "program_v2"
    EXPLORER_V2 = "explorer_v2"
    PROGRAM_DIMENSION_V1 = "program_dimension_v1"
    PROGRAM_TAG_V1 = "program_tag_v1"
    PCAF = "pcaf"


class QueryDependencyDtoTypedDict(TypedDict):
    r"""The query text associated with any persisted query contains references to tables upon which that query relies. This model represents those dependencies. Every dependency contains a database and table identifier as in a traditional SQL database."""

    database_id: str
    r"""The database in which this dependency exists."""
    system: System
    r"""The name of the system holding this reference."""
    table_id: str
    r"""The id of the table this dependency represents."""


class QueryDependencyDto(BaseModel):
    r"""The query text associated with any persisted query contains references to tables upon which that query relies. This model represents those dependencies. Every dependency contains a database and table identifier as in a traditional SQL database."""

    database_id: Annotated[str, pydantic.Field(alias="databaseId")]
    r"""The database in which this dependency exists."""

    system: System
    r"""The name of the system holding this reference."""

    table_id: Annotated[str, pydantic.Field(alias="tableId")]
    r"""The id of the table this dependency represents."""

    @field_serializer("system")
    def serialize_system(self, value):
        if isinstance(value, str):
            try:
                return models.System(value)
            except ValueError:
                return value
        return value


try:
    QueryDependencyDto.model_rebuild()
except NameError:
    pass
