"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class RangeLinkRefTypedDict(TypedDict):
    r"""A reference to a range link."""

    range_link: str
    r"""The unique identifier of a range link."""
    table: str
    r"""The unique identifier of a table"""
    revision: NotRequired[str]
    r"""Identifies a unique revision of content. The same revision can be used for any content request within a file because revisions are allocated at the file-level.
    When querying for content, this can be used to get a consistent version of the content. When editing content, this can be used to make the change to the content at a known state. In either case, omitting the revision (when allowed) will always default to the latest revision of the file.

    """


class RangeLinkRef(BaseModel):
    r"""A reference to a range link."""

    range_link: Annotated[str, pydantic.Field(alias="rangeLink")]
    r"""The unique identifier of a range link."""

    table: str
    r"""The unique identifier of a table"""

    revision: Optional[str] = None
    r"""Identifies a unique revision of content. The same revision can be used for any content request within a file because revisions are allocated at the file-level.
    When querying for content, this can be used to get a consistent version of the content. When editing content, this can be used to make the change to the content at a known state. In either case, omitting the revision (when allowed) will always default to the latest revision of the file.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    RangeLinkRef.model_rebuild()
except NameError:
    pass
