"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .richtextduplicationedit import (
    RichTextDuplicationEdit,
    RichTextDuplicationEditTypedDict,
)
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class RichTextDuplicationEditRequestTypedDict(TypedDict):
    rich_text_id: str
    r"""The unique identifier of the rich text content"""
    rich_text_duplication_edit: RichTextDuplicationEditTypedDict
    r"""The rich text duplication edits to apply"""


class RichTextDuplicationEditRequest(BaseModel):
    rich_text_id: Annotated[
        str,
        pydantic.Field(alias="richTextId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the rich text content"""

    rich_text_duplication_edit: Annotated[
        RichTextDuplicationEdit,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The rich text duplication edits to apply"""


class RichTextDuplicationEditResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class RichTextDuplicationEditResponse(BaseModel):
    headers: Dict[str, List[str]]
