"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class RichTextDuplicationEditResultType(str, Enum):
    r"""The type of resource created from a rich text duplication edit."""

    TABLE = "table"


class RichTextDuplicationEditResultTypedDict(TypedDict):
    r"""A reference to a resource that was created by a rich text duplication edit."""

    table: NotRequired[Nullable[str]]
    r"""The unique identifier of the table created by the rich text duplication edit."""
    type: NotRequired[RichTextDuplicationEditResultType]
    r"""The type of resource created from a rich text duplication edit."""


class RichTextDuplicationEditResult(BaseModel):
    r"""A reference to a resource that was created by a rich text duplication edit."""

    table: OptionalNullable[str] = UNSET
    r"""The unique identifier of the table created by the rich text duplication edit."""

    type: Optional[RichTextDuplicationEditResultType] = None
    r"""The type of resource created from a rich text duplication edit."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["table", "type"])
        nullable_fields = set(["table"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
