"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sectionlocktype import SectionLockType
from typing import List
from typing_extensions import TypedDict
from workiva.types import BaseModel


class SetSectionLockEditTypedDict(TypedDict):
    r"""Updates the selected section's lock to the set value"""

    selection: List[str]
    r"""A selection of one or more sections

    """
    lock: SectionLockType
    r"""A lock applied to a section."""


class SetSectionLockEdit(BaseModel):
    r"""Updates the selected section's lock to the set value"""

    selection: List[str]
    r"""A selection of one or more sections

    """

    lock: SectionLockType
    r"""A lock applied to a section."""
