"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dimensions import Dimensions, DimensionsTypedDict
from .drawingrelativeposition import (
    DrawingRelativePosition,
    DrawingRelativePositionTypedDict,
)
from .fill import Fill, FillTypedDict
from .margins import Margins, MarginsTypedDict
from .paddings import Paddings, PaddingsTypedDict
from .paragraph import Paragraph, ParagraphTypedDict
from .shapetype import ShapeType
from .stroke import Stroke, StrokeTypedDict
from .wrapstyletype import WrapStyleType
import pydantic
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva import models
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ShapeTypedDict(TypedDict):
    r"""A drawing element for a shape such as a rectangle, ellipse, polygon,
    etc. This also includes arrows, left bracket, right bracket, and flow chart
    shapes. Shapes can have zero to two modifiers or an auxiliary point depending
    on the shape type.

    """

    dimensions: DimensionsTypedDict
    r"""A dimension of a rectangle for properties of objects such as a shape, text box, table, chart, image, or page.

    """
    id: str
    r"""Identifier of the drawing element"""
    margins: Nullable[MarginsTypedDict]
    r"""The margins of a rectangle for properties of objects such as a shape, text box, or page.

    """
    position: DrawingRelativePositionTypedDict
    r"""The relative position of a drawing element."""
    wrap_style: Nullable[WrapStyleType]
    r"""The relative position type"""
    shape_type: ShapeType
    r"""The type of a shape to draw. Some shapes are aliased to others;
    for example, decision is an alias of diamond. The shape \"offPageReference\" 
    is unsupported by some non-Workiva applications and may cause issues during
    export if used.

    """
    fill: NotRequired[Nullable[FillTypedDict]]
    r"""A shape or box fill settings for things like shapes. Use a null to indicate no fill."""
    stroke: NotRequired[Nullable[StrokeTypedDict]]
    r"""Line stroke setting for things like shape edges. Use a null to indicate no stroke line."""
    paddings: NotRequired[PaddingsTypedDict]
    r"""The paddings of a rectangle for properties of objects such as a shape, text box, or page."""
    paragraphs: NotRequired[List[ParagraphTypedDict]]
    r"""The rich text paragraphs."""
    rotation: NotRequired[float]
    r"""The rotation in degrees of a shape around the center point of
    the shape. The rotation is applied after the shape is positioned and sized
    meaning the position and dimensions are for the shape without any rotation.

    """


class Shape(BaseModel):
    r"""A drawing element for a shape such as a rectangle, ellipse, polygon,
    etc. This also includes arrows, left bracket, right bracket, and flow chart
    shapes. Shapes can have zero to two modifiers or an auxiliary point depending
    on the shape type.

    """

    dimensions: Dimensions
    r"""A dimension of a rectangle for properties of objects such as a shape, text box, table, chart, image, or page.

    """

    id: str
    r"""Identifier of the drawing element"""

    margins: Nullable[Margins]
    r"""The margins of a rectangle for properties of objects such as a shape, text box, or page.

    """

    position: DrawingRelativePosition
    r"""The relative position of a drawing element."""

    wrap_style: Annotated[Nullable[WrapStyleType], pydantic.Field(alias="wrapStyle")]
    r"""The relative position type"""

    shape_type: Annotated[ShapeType, pydantic.Field(alias="shapeType")]
    r"""The type of a shape to draw. Some shapes are aliased to others;
    for example, decision is an alias of diamond. The shape \"offPageReference\" 
    is unsupported by some non-Workiva applications and may cause issues during
    export if used.

    """

    fill: OptionalNullable[Fill] = UNSET
    r"""A shape or box fill settings for things like shapes. Use a null to indicate no fill."""

    stroke: OptionalNullable[Stroke] = UNSET
    r"""Line stroke setting for things like shape edges. Use a null to indicate no stroke line."""

    paddings: Optional[Paddings] = None
    r"""The paddings of a rectangle for properties of objects such as a shape, text box, or page."""

    paragraphs: Optional[List[Paragraph]] = None
    r"""The rich text paragraphs."""

    rotation: Optional[float] = 0
    r"""The rotation in degrees of a shape around the center point of
    the shape. The rotation is applied after the shape is positioned and sized
    meaning the position and dimensions are for the shape without any rotation.

    """

    @field_serializer("wrap_style")
    def serialize_wrap_style(self, value):
        if isinstance(value, str):
            try:
                return models.WrapStyleType(value)
            except ValueError:
                return value
        return value

    @field_serializer("shape_type")
    def serialize_shape_type(self, value):
        if isinstance(value, str):
            try:
                return models.ShapeType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fill", "stroke", "paddings", "paragraphs", "rotation"])
        nullable_fields = set(["fill", "margins", "stroke", "wrapStyle"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    Shape.model_rebuild()
except NameError:
    pass
