"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .inheritfrom import InheritFrom
from .insertion import Insertion, InsertionTypedDict
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel


class SheetUpdateInsertRowsTypedDict(TypedDict):
    r"""Insert rows into the sheet"""

    inherit_from: InheritFrom
    r"""Where to inherit formats from when performing an insertion"""
    insertions: List[InsertionTypedDict]
    r"""List of row insertions"""


class SheetUpdateInsertRows(BaseModel):
    r"""Insert rows into the sheet"""

    inherit_from: Annotated[InheritFrom, pydantic.Field(alias="inheritFrom")]
    r"""Where to inherit formats from when performing an insertion"""

    insertions: List[Insertion]
    r"""List of row insertions"""


try:
    SheetUpdateInsertRows.model_rebuild()
except NameError:
    pass
