"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .interval import Interval, IntervalTypedDict
from typing import List
from typing_extensions import TypedDict
from workiva.types import BaseModel


class SheetUpdateResizeColumnsToFitTypedDict(TypedDict):
    r"""Auto-size columns to fit content"""

    intervals: List[IntervalTypedDict]
    r"""The intervals of columns to resize"""


class SheetUpdateResizeColumnsToFit(BaseModel):
    r"""Auto-size columns to fit content"""

    intervals: List[Interval]
    r"""The intervals of columns to resize"""
