"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .slide import Slide, SlideTypedDict
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class SlidesListResultTypedDict(TypedDict):
    r"""Returns a JSON object with `data` and `@nextLink` properties. `data` contains a list of `Slide` objects, and `@nextLink` provides the URL to the next set of results. If there are no additional results, `@nextLink` doesn't appear. If the request returns no results at all, `data` contains an empty array."""

    data: List[SlideTypedDict]
    at_next_link: NotRequired[str]
    r"""Pagination link for next set of results"""


class SlidesListResult(BaseModel):
    r"""Returns a JSON object with `data` and `@nextLink` properties. `data` contains a list of `Slide` objects, and `@nextLink` provides the URL to the next set of results. If there are no additional results, `@nextLink` doesn't appear. If the request returns no results at all, `data` contains an empty array."""

    data: List[Slide]

    at_next_link: Annotated[Optional[str], pydantic.Field(alias="@nextLink")] = None
    r"""Pagination link for next set of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["@nextLink"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SlidesListResult.model_rebuild()
except NameError:
    pass
