"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class SpreadsheetFiltersReapplicationTypedDict(TypedDict):
    r"""A spreadsheet filter reapply operation, which can reapply filters to a spreadsheet and optionally ignore read-only filters."""

    ignore_non_editable_filters: NotRequired[bool]
    r"""Skip filters that cannot be reapplied (due to not having edit permissions, locked sheets, or sheets in input mode) instead of returning an error."""


class SpreadsheetFiltersReapplication(BaseModel):
    r"""A spreadsheet filter reapply operation, which can reapply filters to a spreadsheet and optionally ignore read-only filters."""

    ignore_non_editable_filters: Annotated[
        Optional[bool], pydantic.Field(alias="ignoreNonEditableFilters")
    ] = False
    r"""Skip filters that cannot be reapplied (due to not having edit permissions, locked sheets, or sheets in input mode) instead of returning an error."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ignoreNonEditableFilters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SpreadsheetFiltersReapplication.model_rebuild()
except NameError:
    pass
