"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .styleguideimportresponse import (
    StyleGuideImportResponse,
    StyleGuideImportResponseTypedDict,
)
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata


class StyleGuideImportRequestTypedDict(TypedDict):
    style_guide_id: str
    r"""The unique identifier of the style guide"""


class StyleGuideImportRequest(BaseModel):
    style_guide_id: Annotated[
        str,
        pydantic.Field(alias="styleGuideId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the style guide"""


class StyleGuideImportResponse1TypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: StyleGuideImportResponseTypedDict


class StyleGuideImportResponse1(BaseModel):
    headers: Dict[str, List[str]]

    result: StyleGuideImportResponse
