"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tableanchorcreation import TableAnchorCreation, TableAnchorCreationTypedDict
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class TableAnchorCreationRequestTypedDict(TypedDict):
    table_id: str
    r"""The unique identifier for the table"""
    table_anchor_creation: TableAnchorCreationTypedDict
    r"""The details of range for which the table anchor needs to be created"""


class TableAnchorCreationRequest(BaseModel):
    table_id: Annotated[
        str,
        pydantic.Field(alias="tableId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier for the table"""

    table_anchor_creation: Annotated[
        TableAnchorCreation,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The details of range for which the table anchor needs to be created"""


class TableAnchorCreationResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class TableAnchorCreationResponse(BaseModel):
    headers: Dict[str, List[str]]
