"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .testformexport import TestFormExport, TestFormExportTypedDict
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class TestFormExportRequestTypedDict(TypedDict):
    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    test_form_id: str
    r"""The unique identifier of the test form"""
    test_form_export: TestFormExportTypedDict
    r"""Details about the test form export"""


class TestFormExportRequest(BaseModel):
    __test__ = False

    test_form_id: Annotated[
        str,
        pydantic.Field(alias="testFormId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the test form"""

    test_form_export: Annotated[
        TestFormExport,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Details about the test form export"""


class TestFormExportResponseTypedDict(TypedDict):
    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    headers: Dict[str, List[str]]


class TestFormExportResponse(BaseModel):
    __test__ = False

    headers: Dict[str, List[str]]
