"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .testform import TestForm, TestFormTypedDict
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class TestFormsListResultTypedDict(TypedDict):
    r"""Returns a JSON object with `data` and `@nextLink` properties. `data` contains a list of [`TestForm`](ref:testforms#testform) objects, and `@nextLink` provides the URL to the next set of results. If there are no additional results, `@nextLink` doesn't appear. If the request returns no results at all, `data` contains an empty array."""

    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    data: List[TestFormTypedDict]
    r"""A list of `Matrix` objects"""
    at_next_link: NotRequired[Nullable[str]]
    r"""The pagination link for next set of results"""


class TestFormsListResult(BaseModel):
    r"""Returns a JSON object with `data` and `@nextLink` properties. `data` contains a list of [`TestForm`](ref:testforms#testform) objects, and `@nextLink` provides the URL to the next set of results. If there are no additional results, `@nextLink` doesn't appear. If the request returns no results at all, `data` contains an empty array."""

    __test__ = False

    data: List[TestForm]
    r"""A list of `Matrix` objects"""

    at_next_link: Annotated[
        OptionalNullable[str], pydantic.Field(alias="@nextLink")
    ] = UNSET
    r"""The pagination link for next set of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["@nextLink"])
        nullable_fields = set(["@nextLink"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TestFormsListResult.model_rebuild()
except NameError:
    pass
