"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class TextFormatTypedDict(TypedDict):
    r"""Text formats. Fields that are omitted will be ignored."""

    bold: NotRequired[Nullable[bool]]
    r"""Text bold format"""
    font_color: NotRequired[Nullable[str]]
    r"""A hex color code"""
    font_family: NotRequired[Nullable[str]]
    r"""Text font format"""
    font_size: NotRequired[Nullable[float]]
    r"""Text font size, in points"""
    italic: NotRequired[Nullable[bool]]
    r"""Text italic format"""
    strikethrough: NotRequired[Nullable[bool]]
    r"""Text strikethrough format"""
    underline: NotRequired[Nullable[bool]]
    r"""Text underline format"""


class TextFormat(BaseModel):
    r"""Text formats. Fields that are omitted will be ignored."""

    bold: OptionalNullable[bool] = UNSET
    r"""Text bold format"""

    font_color: Annotated[OptionalNullable[str], pydantic.Field(alias="fontColor")] = (
        "#000000"
    )
    r"""A hex color code"""

    font_family: Annotated[
        OptionalNullable[str], pydantic.Field(alias="fontFamily")
    ] = UNSET
    r"""Text font format"""

    font_size: Annotated[OptionalNullable[float], pydantic.Field(alias="fontSize")] = (
        UNSET
    )
    r"""Text font size, in points"""

    italic: OptionalNullable[bool] = UNSET
    r"""Text italic format"""

    strikethrough: OptionalNullable[bool] = UNSET
    r"""Text strikethrough format"""

    underline: OptionalNullable[bool] = UNSET
    r"""Text underline format"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "bold",
                "fontColor",
                "fontFamily",
                "fontSize",
                "italic",
                "strikethrough",
                "underline",
            ]
        )
        nullable_fields = set(
            [
                "bold",
                "fontColor",
                "fontFamily",
                "fontSize",
                "italic",
                "strikethrough",
                "underline",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
