"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textalignment import TextAlignment
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva import models
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET_SENTINEL


class TextStyleAlignmentTypedDict(TypedDict):
    r"""The alignment applied by the text style."""

    alignment: NotRequired[Nullable[TextAlignment]]
    r"""Indicates the horizontal alignment of the text within a paragraph."""
    locked: NotRequired[bool]
    r"""Whether the alignment is locked."""


class TextStyleAlignment(BaseModel):
    r"""The alignment applied by the text style."""

    alignment: OptionalNullable[TextAlignment] = TextAlignment.LEFT
    r"""Indicates the horizontal alignment of the text within a paragraph."""

    locked: Optional[bool] = None
    r"""Whether the alignment is locked."""

    @field_serializer("alignment")
    def serialize_alignment(self, value):
        if isinstance(value, str):
            try:
                return models.TextAlignment(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["alignment", "locked"])
        nullable_fields = set(["alignment"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
