"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .type import Type, TypeTypedDict
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class TypesListResultTypedDict(TypedDict):
    r"""Returns a JSON object with `data` and `@nextLink` properties. `data` contains a list of [`Type`](ref:graph#type) objects, and `@nextLink` provides the URL to the next set of results. If there are no additional results, `@nextLink` doesn't appear. If the request returns no results at all, `data` contains an empty array."""

    at_next_link: NotRequired[Nullable[str]]
    r"""Pagination link for next set of results"""
    data: NotRequired[List[TypeTypedDict]]


class TypesListResult(BaseModel):
    r"""Returns a JSON object with `data` and `@nextLink` properties. `data` contains a list of [`Type`](ref:graph#type) objects, and `@nextLink` provides the URL to the next set of results. If there are no additional results, `@nextLink` doesn't appear. If the request returns no results at all, `data` contains an empty array."""

    at_next_link: Annotated[
        OptionalNullable[str], pydantic.Field(alias="@nextLink")
    ] = UNSET
    r"""Pagination link for next set of results"""

    data: Optional[List[Type]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["@nextLink", "data"])
        nullable_fields = set(["@nextLink"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TypesListResult.model_rebuild()
except NameError:
    pass
