"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rangevalues import RangeValues, RangeValuesTypedDict
import pydantic
from pydantic import model_serializer
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel, Nullable, UNSET_SENTINEL
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class UpdateValuesByRangeRequestTypedDict(TypedDict):
    range_values: RangeValuesTypedDict
    r"""All values for the range, not just those to update"""
    range: Nullable[str]
    r"""The range of values, in A1-style notation"""
    sheet_id: str
    r"""The unique identifier of the sheet"""
    spreadsheet_id: str
    r"""The unique identifier of the spreadsheet"""


class UpdateValuesByRangeRequest(BaseModel):
    range_values: Annotated[
        RangeValues,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""All values for the range, not just those to update"""

    range: Annotated[
        Nullable[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The range of values, in A1-style notation"""

    sheet_id: Annotated[
        str,
        pydantic.Field(alias="sheetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the sheet"""

    spreadsheet_id: Annotated[
        str,
        pydantic.Field(alias="spreadsheetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the spreadsheet"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class UpdateValuesByRangeResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class UpdateValuesByRangeResponse(BaseModel):
    headers: Dict[str, List[str]]
