"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tabledto import TableDto, TableDtoTypedDict
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class ValidateTablesDtoTypedDict(TypedDict):
    deleted_tables: NotRequired[List[TableDtoTypedDict]]
    r"""A list of tables that were deleted during the validation because not enough information was available to repair them. These tables will no longer be available via the endpoint and queries using these tables will cease to function properly."""
    repaired_tables: NotRequired[List[TableDtoTypedDict]]
    r"""A list of tables that were modified during the validation and will continue to
    be visible and to be usable in the account.
    """


class ValidateTablesDto(BaseModel):
    deleted_tables: Annotated[
        Optional[List[TableDto]], pydantic.Field(alias="deletedTables")
    ] = None
    r"""A list of tables that were deleted during the validation because not enough information was available to repair them. These tables will no longer be available via the endpoint and queries using these tables will cease to function properly."""

    repaired_tables: Annotated[
        Optional[List[TableDto]], pydantic.Field(alias="repairedTables")
    ] = None
    r"""A list of tables that were modified during the validation and will continue to
    be visible and to be usable in the account.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["deletedTables", "repairedTables"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ValidateTablesDto.model_rebuild()
except NameError:
    pass
