"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .refreshconnectiondto import RefreshConnectionDto, RefreshConnectionDtoTypedDict
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, QueryParamMetadata, RequestMetadata


WDATA_REFRESH_BATCH_OP_SERVERS = [
    # US
    "https://h.app.wdesk.com/s/wdata/prep",
    # EU
    "https://h.eu.wdesk.com/s/wdata/prep",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/prep",
]


class WdataRefreshBatchRequestTypedDict(TypedDict):
    request_body: List[RefreshConnectionDtoTypedDict]
    cancel_unwritables: NotRequired[bool]
    r"""Allow individual connections in the batch to be canceled if they have a destination that is unwritable. This will NOT cancel the entire batch."""


class WdataRefreshBatchRequest(BaseModel):
    request_body: Annotated[
        List[RefreshConnectionDto],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    cancel_unwritables: Annotated[
        Optional[bool],
        pydantic.Field(alias="cancelUnwritables"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Allow individual connections in the batch to be canceled if they have a destination that is unwritable. This will NOT cancel the entire batch."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cancelUnwritables"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
