"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pagedresponsequeryresultdto import (
    PagedResponseQueryResultDto,
    PagedResponseQueryResultDtoTypedDict,
)
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, QueryParamMetadata


WDATA_LIST_QUERY_RESULTS_OP_SERVERS = [
    # EU
    "https://h.eu.wdesk.com/s/wdata/prep",
    # US
    "https://h.app.wdesk.com/s/wdata/prep",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/prep",
]


class WdataListQueryResultsRequestTypedDict(TypedDict):
    query_id: str
    r"""The unique identifier of the query"""
    user_specific: NotRequired[bool]
    r"""Limit results to those created by the current user"""
    cursor: NotRequired[str]
    r"""A paging cursor; if included, `limit` is ignored"""
    limit: NotRequired[str]
    r"""The number of query results to return, from 1 to 1000; by default, 1000"""
    offset: NotRequired[int]
    r"""The item to start with on the page, greater than or equal to 0; by default, 0"""


class WdataListQueryResultsRequest(BaseModel):
    query_id: Annotated[
        str,
        pydantic.Field(alias="queryId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""The unique identifier of the query"""

    user_specific: Annotated[
        Optional[bool],
        pydantic.Field(alias="userSpecific"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Limit results to those created by the current user"""

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A paging cursor; if included, `limit` is ignored"""

    limit: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The number of query results to return, from 1 to 1000; by default, 1000"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""The item to start with on the page, greater than or equal to 0; by default, 0"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["userSpecific", "cursor", "limit", "offset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WdataListQueryResultsResponseTypedDict(TypedDict):
    result: PagedResponseQueryResultDtoTypedDict


class WdataListQueryResultsResponse(BaseModel):
    next: Union[
        Callable[[], Optional[WdataListQueryResultsResponse]],
        Callable[[], Awaitable[Optional[WdataListQueryResultsResponse]]],
    ]

    result: PagedResponseQueryResultDto
