"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pagedresponsetagdto import PagedResponseTagDto, PagedResponseTagDtoTypedDict
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, QueryParamMetadata


WDATA_LIST_TAGS_OP_SERVERS = [
    # EU
    "https://h.eu.wdesk.com/s/wdata/prep",
    # US
    "https://h.app.wdesk.com/s/wdata/prep",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/prep",
]


class WdataListTagsRequestTypedDict(TypedDict):
    cursor: NotRequired[str]
    r"""A paging cursor; if included, `limit` is ignored"""
    limit: NotRequired[int]
    r"""The number of tags to return, from 1 to 1000; by default, 1000"""
    offset: NotRequired[int]
    r"""The item to start with on the page, greater than or equal to 0; by default, 0"""


class WdataListTagsRequest(BaseModel):
    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A paging cursor; if included, `limit` is ignored"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1000
    r"""The number of tags to return, from 1 to 1000; by default, 1000"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The item to start with on the page, greater than or equal to 0; by default, 0"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cursor", "limit", "offset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WdataListTagsResponseTypedDict(TypedDict):
    result: PagedResponseTagDtoTypedDict


class WdataListTagsResponse(BaseModel):
    next: Union[
        Callable[[], Optional[WdataListTagsResponse]],
        Callable[[], Awaitable[Optional[WdataListTagsResponse]]],
    ]

    result: PagedResponseTagDto
