"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, QueryParamMetadata


WDATA_VALIDATE_FILENAME_OP_SERVERS = [
    # US
    "https://h.app.wdesk.com/s/wdata/prep",
    # EU
    "https://h.eu.wdesk.com/s/wdata/prep",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/prep",
]


class WdataValidateFilenameRequestTypedDict(TypedDict):
    filename: str
    r"""The name of the file to upload"""
    table_id: str
    r"""The ID of the table to upload the file to"""


class WdataValidateFilenameRequest(BaseModel):
    filename: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""The name of the file to upload"""

    table_id: Annotated[
        str,
        pydantic.Field(alias="tableId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""The ID of the table to upload the file to"""
