openapi: 3.0.3
info:
  title: Workiva API
  version: 1.2734.0
  description: 2026-01-01 Version of the Workiva API
servers:
  - url: https://api.app.wdesk.com
    description: US
  - url: https://api.eu.wdesk.com
    description: EU
  - url: https://api.apac.wdesk.com
    description: APAC
tags:
  - name: Activities
    description: |
      Activities enable you to retrieve a list of actions performed in the organization or a specific workspace, such as: <ul> <li>User logins</li> <li>Added users</li> <li>Changes to roles</li> <li>Changes to organization or workspace settings</li> </ul> These activities are also available in the Workiva platform and can be exported from Organization Admin or Workspace Settings. <br /><br /> To access activities through this API or in Workiva, a user must have a valid admin role: <ul> <li>Org U[...]
  - name: Admin
    description: Endpoints to manage organizations, workspaces, groups, and users
  - name: Content
    description: Endpoints for reading and writing Workiva content. See [**Introduction to Content Endpoints**](ref:content-guide) for more information.
  - name: Documents
    description: Documents enable you to organize and review data in collaborative files with linked text, documents, and images. Use these endpoints to manage documents and their sections in the Workiva Platform.
  - name: Files
    description: Endpoints to manage files and folders.
  - name: Graph
    description: The Graph endpoints enable access to Integrated Risk workspaces, such as to pull reports and records, create and edit records, and more. <br /><br /> Please refer to the [Graph Guides](ref:graph-guide) for further documentation and examples.
  - name: IAM
    description: |
      Before your application can access private data using other Workiva APIs, it must obtain an access token that grants access to those APIs.

      Use the IAM REST API endpoint to exchange your OAuth credentials (clientID and clientSecret) for a token.
  - name: Milestones
    description: Endpoints for working with Milestones. See [**Introduction to Milestones Endpoints**](ref:milestones-guide) for more information.
  - name: Operations
    description: Use these endpoints to manage operations, such as to check their status.
  - name: Permissions
    description: Endpoints to manage Permissions
  - name: Spreadsheets
    description: Spreadsheets enable you to work with large, complex data in a familiar, collaborative, and controlled environment. Use these endpoints to manage spreadsheets and their sheets in the Workiva platform.
  - name: Presentations
    description: Endpoints to manage presentations
  - name: Reports
    description: Endpoints used to generate Admin reports
  - name: Sustainability
    description: Endpoints to manage Sustainability Programs
  - name: Tasks
    description: |
      Tasks enable users to manage projects, organize responsibilities, and meet deadlines in the Workiva platform. Use these endpoints to create and manage tasks.
  - name: Test Forms
    description: |
      These endpoints are used to manage test forms, test phases, and matrices. They are also used to manage attachments on test phases, matrices, and samples.
paths:
  /activities/{activityId}:
    get:
      description: |
        Retrieves an activity given its ID.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the platform will always result in the same Activity ID. Please rely on the ActivityAction `alias` field to determine if an activity is relevant to your use case.
        :::
      operationId: getActivityById
      security:
        - oauth:
            - activity:read
      summary: Retrieve a single activity
      tags:
        - Activities
  /activityActions:
    get:
      description: |
        Retrieves a list of actions performed that may produce activities.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the platform will always result in the same Activity ID. Please rely on the ActivityAction `alias` field to determine if an activity is relevant to your use case.
        :::
      operationId: getActivityActions
      security:
        - oauth:
            - activity:read
      summary: Retrieve a list of activity actions
      tags:
        - Activities
  /activityActions/{activityActionId}:
    get:
      description: |
        Returns an action performed, given its ID

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the platform will always result in the same Activity ID. Please rely on the ActivityAction `alias` field to determine if an activity is relevant to your use case.
        :::
      operationId: getActivityActionById
      security:
        - oauth:
            - activity:read
      summary: Retrieve a single activity action
      tags:
        - Activities
  /content/anchors/{anchorId}:
    get:
      description: Returns an [`Anchor`](ref:content#anchor) given its id.
      operationId: getAnchorById
      security:
        - oauth:
            - file:read
      summary: Retrieve an anchor by ID
      tags:
        - Content
  /content/destinationLinks/{destinationLinkId}:
    get:
      description: Returns a [`DestinationLink`](ref:content#destinationlink) given its id
      operationId: getDestinationLinkById
      security:
        - oauth:
            - file:read
      summary: Retrieve a destination link by id
      tags:
        - Content
  /content/destinationLinks/{destinationLinkId}/sourceConversion:
    post:
      description: |
        Converts a destination link into a source link. The previous source, if any, will be converted into a destination link.

        Responses include a `Location` header, which indicates where to poll for results. For more details on long-running
        job polling, see [Operations endpoint](ref:getoperationbyid). When the source conversion
        completes, its status will be `completed`, and the response body includes a `resourceURL`. For more details on the `resourceURL`
        see [operation results endpoint](ref:getdestinationlinksourceconversionresults).
        For more details, see [Authentication documentation](ref:authentication).
      operationId: destinationLinkSourceConversion
      security:
        - oauth:
            - file:write
      summary: Initiate a destination link conversion
      tags:
        - Content
  /content/drawings/{drawingId}/elements:
    get:
      description: Returns a [`DrawingElementListResult`](ref:content#drawingelementlistresult) given its id
      operationId: getDrawingElementsById
      security:
        - oauth:
            - file:read
      summary: Retrieve drawing elements by id
      tags:
        - Content
  /content/drawings/{drawingId}/anchors:
    get:
      description: Returns an [`AnchorsListResult`](ref:content#anchorslistresult) for a given drawingId.
      operationId: getDrawingAnchors
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of drawing anchors
      tags:
        - Content
  /content/drawings/{drawingId}/anchors/{anchorId}:
    get:
      description: Returns an [`Anchor`](ref:content#anchor) given its id.
      operationId: getDrawingAnchorById
      security:
        - oauth:
            - file:read
      summary: Retrieve a drawing anchor by ID
      tags:
        - Content
  /content/drawings/{drawingId}/anchors/{anchorId}/extensions:
    get:
      description: Returns a paginated list of [`AnchorExtensions`](ref:content#anchorextension) for a given anchorId.
      operationId: getDrawingAnchorExtensions
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of drawing anchor extensions
      tags:
        - Content
  /content/images/upload:
    post:
      description: |
        Retrieves a URL that can be used to upload an image, and an operationId to track the image upload progress. Once uploaded, the image can be inserted in content.

        Image uploads must conform to the following constraints:

        - An image must be uploaded once per usage in content.
        - Image uploads must complete within ten minutes.
        - The file size of the uploaded image must 75 MB or smaller.
        - The total number of pixels in the uploaded image must be 50 Megapixels or smaller.
        - The image must be inserted in content within 24 hours or it will be removed.

        Responses include an `uploadUrl` which indicates where to upload the image. To upload the file,
        perform a PUT against the `uploadUrl` with the same authentication credentials and flow as the import request.
        For more details, see [Authentication documentation](ref:authentication). The response will also include
        a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the upload completes, its status will be
        `completed`, and the response body includes a `resourceURL`.
      operationId: imageUpload
      security:
        - oauth:
            - file:write
      summary: Initiate upload of an image
      tags:
        - Content
  /content/images/{imageId}:
    get:
      description: Returns a [`Image`](ref:content#image) given its id
      operationId: getImageById
      security:
        - oauth:
            - file:read
      summary: Retrieve an image by id
      tags:
        - Content
  /content/richText/{richTextId}/anchors:
    get:
      description: Returns an [`AnchorsListResult`](ref:content#anchorslistresult) for a given richTextId.
      operationId: getRichTextAnchors
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of rich text anchors
      tags:
        - Content
  /content/richText/{richTextId}/anchors/creation:
    post:
      description: |
        Create a new [`Anchor`](ref:content#anchor) using a [`RichTextAnchorCreation`](ref:content#richtextanchorcreation) request. This is a long running operation.

        Responses include a `Location` header, which indicates where to poll for
        results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid).
        When the creation completes, its status will be `completed`, and the response
        body includes a `resourceURL`. To GET the new rich text anchor, perform a GET
        on the `resourceURL` with the same authentication credentials and flow as the
        initial request. For more details, see
        [Authentication documentation](ref:authentication).
      operationId: richTextAnchorCreation
      security:
        - oauth:
            - file:write
      summary: Initiate creation of a new rich text anchor
      tags:
        - Content
  /content/richText/{richTextId}/anchors/{anchorId}:
    get:
      description: Returns an [`Anchor`](ref:content#anchor) given its id.
      operationId: getRichTextAnchorById
      security:
        - oauth:
            - file:read
      summary: Retrieve a rich text anchor by id
      tags:
        - Content
  /content/richText/{richTextId}/anchors/{anchorId}/extensions:
    get:
      description: Returns a paginated list of [`AnchorExtensions`](ref:content#anchorextension) for a given anchorId.
      operationId: getRichTextAnchorExtensions
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of rich text anchor extensions
      tags:
        - Content
  /content/richText/{richTextId}/duplication/edit:
    post:
      description: |-
        Sends a [`RichTextDuplicationEdit`](ref:content#richtextduplicationedit) to perform on the rich text.
        The optional revision property can be used to identify a stable version of the text to use for selections. The latest revision is used if not specified.
        This is a long running operation. Responses include a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
        The `resourceUrl` field will be populated with a link to the [Rich Text Duplication Edit Results endpoint](ref:getrichtextduplicationeditresults) to retrieve the IDs of the new resources.
      operationId: richTextDuplicationEdit
      security:
        - oauth:
            - file:write
      summary: Initiate duplication edits to rich text
      tags:
        - Content
  /content/richText/{richTextId}/edit:
    post:
      description: |-
        Sends a [`RichTextBatchEdit`](ref:content#richtextbatchedit) to perform as a batch on the rich text.
        The optional revision property can be used to identify a stable version of the text to use for selections. The latest revision is used if not specified.
        This is a long running operation. Responses include a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
        If the batch edit creates any new resources such as embedded tables, the `resourceUrl` field will be populated with a link to the [Rich Text Batch Edit Results endpoint](ref:getrichtextbatcheditresults) to retrieve the IDs of the new resources.
      operationId: richTextBatchEdit
      security:
        - oauth:
            - file:write
      summary: Initiate edits to rich text
      tags:
        - Content
  /content/richText/{richTextId}/links/edit:
    post:
      description: |-
        Sends a [`RichTextLinksBatchEdit`](ref:content#richtextlinksbatchedit) to perform as a batch on the rich text.
        The optional revision property can be used to identify a stable version of the text to use for selections. The latest revision is used if not specified.
        This is a long running operation. Responses include a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
        If the batch edit creates any new resources, such as destination links, the `resourceUrl` field will be populated with a link to the [Rich Text Links Batch Edit Results endpoint](ref:getrichtextlinksbatcheditresults) to retrieve the IDs of the new resources.
      operationId: richTextLinksBatchEdit
      security:
        - oauth:
            - file:write
      summary: Initiate edits to rich text links
      tags:
        - Content
  /content/richText/{richTextId}/paragraphs:
    get:
      description: Returns a [`ParagraphsListResult`](ref:content#paragraphslistresult) for a rich text object, given its id.
      operationId: getRichTextParagraphs
      security:
        - oauth:
            - file:read
      summary: Retrieve rich text paragraphs
      tags:
        - Content
  /content/styleGuides/{styleGuideId}:
    get:
      description: |
        Returns the [`StyleGuide`](ref:content#styleguide) populated with the text styles, list styles, etc. The revision will ensure a static content.
      operationId: getStyleGuideById
      security:
        - oauth:
            - file:read
      summary: Retrieve a style guide by id
      tags:
        - Content
  /content/styleGuides/{styleGuideId}/export:
    post:
      description: |
        Export the style guide with the given identifier. Options are
        specified using a
        [StyleGuideExport](ref:content#styleguideexport) object.

        Responses include a `Location` header, which indicates where to poll for
        results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid).
        When the export completes, its status will be `completed`, and the response
        body includes a `resourceURL`. To GET the exported style guide, perform a GET
        on the `resourceURL` with the same authentication credentials and flow as the
        initial request. For more details, see
        [Authentication documentation](ref:authentication).
      operationId: styleGuideExport
      security:
        - oauth:
            - file:read
      summary: Initiate a style guide export
      tags:
        - Content
  /content/styleGuides/{styleGuideId}/import:
    post:
      description: |
        Imports a style guide to the given identifier. This operation will replace the current style guide.

        Responses include an `uploadUrl` which indicates where to upload the style guide import. To upload the file,
        perform a PUT against the `uploadUrl` with the same authentication credentials and flow as the import request.
        For more details, see [Authentication documentation](ref:authentication). The response will also include
        a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the upload completes, its status will be
        `completed`, and the response body includes a `resourceURL`. To GET the style guide, perform a GET
        on the `resourceURL` with the same authentication credentials and flow as the initial request.
      operationId: styleGuideImport
      security:
        - oauth:
            - file:write
      summary: Initiate import of a style guide
      tags:
        - Content
  /content/tables/{tableId}/anchors:
    get:
      description: Returns an [`AnchorsListResult`](ref:content#anchorslistresult) given tableId.
      operationId: getTableAnchors
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of table anchors
      tags:
        - Content
  /content/tables/{tableId}/anchors/creation:
    post:
      description: |
        Create a new [`Anchor`](ref:content#anchor) using a [`TableAnchorCreation`](ref:content#tableanchorcreation) request. This is a long running operation.

        Responses include a `Location` header, which indicates where to poll for
        results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid).
        When the creation completes, its status will be `completed`, and the response
        body includes a `resourceURL`. To GET the new table anchor, perform a GET
        on the `resourceURL` with the same authentication credentials and flow as the
        initial request. For more details, see
        [Authentication documentation](ref:authentication).
      operationId: tableAnchorCreation
      security:
        - oauth:
            - file:write
      summary: Initiate creation of a new table anchor
      tags:
        - Content
  /content/tables/{tableId}/anchors/{anchorId}:
    get:
      description: Returns an [`Anchor`](ref:content#anchor) given its id.
      operationId: getTableAnchorById
      security:
        - oauth:
            - file:read
      summary: Retrieve a table anchor by ID
      tags:
        - Content
  /content/tables/{tableId}/anchors/{anchorId}/extensions:
    get:
      description: Returns a paginated list of [`AnchorExtensions`](ref:content#anchorextension) for a given anchorId.
      operationId: getTableAnchorExtensions
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of table anchor extensions
      tags:
        - Content
  /content/tables/{tableId}/cells:
    get:
      description: Returns a [`TableCellsResult`](ref:content#tablecellsresult) for a given tableId.
      operationId: getTableCells
      security:
        - oauth:
            - file:read
      summary: Retrieve table cell content
      tags:
        - Content
  /content/tables/{tableId}/cells/edit:
    post:
      description: |
        Sends a [`TableCellsBatchEdit`](ref:content#tablecellsbatchedit) to perform on the cells in a table.

        The optional revision property can be used to identify a stable cell location in the table. The latest revision is used if not specified.

        Responses include a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see[ Operations endpoint ](ref:getoperationbyid). When the creation completes, its status will be `completed`, and the response\nbody includes a `resourceURL`.\n"
      operationId: tableCellsBatchEdit
      security:
        - oauth:
            - file:write
      summary: Initiate edits to table cells
      tags:
        - Content
  /content/tables/{tableId}/properties/columns:
    get:
      description: |
        Returns a [`ColumnPropertiesListResult`](ref:content#columnpropertieslistresult) for a table
      operationId: getColumnProperties
      security:
        - oauth:
            - file:read
      summary: Retrieve table column properties
      tags:
        - Content
  /content/tables/{tableId}/edit:
    post:
      description: |
        Sends a single [`TableEdit`](ref:content#tableedit) to perform on the table.

        Responses include a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see
        [ Operations endpoint ](ref:getoperationbyid). When the creation completes, its status will be `completed`, and the response
        body includes a `resourceURL`.
      operationId: tableEdit
      security:
        - oauth:
            - file:write
      summary: Initiate edit to a table
      tags:
        - Content
  /content/tables/{tableId}/filters/reapplication:
    post:
      description: |
        Performs a [`TableFiltersReapplication`](ref:content#tablefiltersreapplication) on the specified table.
        This endpoint is used to refresh the table's filters based on the latest state or configuration changes.
        The filters are reapplied in the context of the table's current data state.
        This is a long running operation. Responses include a `Location` header, which indicates where to poll for results. For more details on
        long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: tableFiltersReapplication
      security:
        - oauth:
            - file:write
      summary: Reapply filters to the table
      tags:
        - Content
  /content/tables/{tableId}/links/edit:
    post:
      description: |
        Sends a [`TableLinksBatchEdit`](ref:content#tablelinksbatchedit) to perform on the links in a table.

        The optional revision property can be used to identify a stable cell location in the table. The latest revision is used if not specified.

        If the edit creates any new resources, such as destination links, the `resourceUrl` field will be populated with a link to the [Table Links Edit Results endpoint](ref:gettablelinkseditresults) to retrieve the IDs of the new resources.
      operationId: tableLinksBatchEdit
      security:
        - oauth:
            - file:write
      summary: Initiate edit to table links
      tags:
        - Content
  /content/tables/{tableId}/rangeLinks:
    get:
      description: Returns a [`RangeLinkListResult`](ref:content#rangelinklistresult) for a given tableId.
      operationId: getRangeLinks
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of range links
      tags:
        - Content
  /content/tables/{tableId}/rangeLinks/{rangeLinkId}:
    get:
      description: Returns a [`RangeLink`](ref:content#rangelink) given its id
      operationId: getRangeLinkById
      security:
        - oauth:
            - file:read
      summary: Retrieve a range link by id
      tags:
        - Content
  /content/tables/{tableId}/rangeLinks/{rangeLinkId}/destinations:
    get:
      description: Returns a [`RangeLinkListResult`](ref:content#rangelinklistresult) of destinations for a given source range link.
      operationId: getRangeLinkDestinations
      security:
        - oauth:
            - file:read
      summary: Retrieve range link destinations for a source
      tags:
        - Content
  /content/tables/{tableId}/rangeLinks/edit:
    post:
      description: |
        Sends a [`RangeLinkEdit`](ref:content#rangelinkedit) to perform on the range links in a table.
        This is a long running operation. Responses include a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: tableRangeLinksEdit
      security:
        - oauth:
            - file:write
      summary: Initiate range links edits on a table
      tags:
        - Content
  /content/tables/{tableId}/properties:
    get:
      description: |
        Returns a [`TableProperties`](ref:content#tableproperties) for a table
      operationId: getTableProperties
      security:
        - oauth:
            - file:read
      summary: Retrieve a table's properties by id
      tags:
        - Content
    patch:
      description: |
        Partially updates a table's properties given its ID.

        This is a long running operation. Responses include a `Location` header, which indicates where to poll for results.
        For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).

        ### Options
        | Path               | PATCH Operations Supported |
        |--------------------|----------------------------|
        | `/name`            | `replace`                  |
        | `/resizeRowsToFit` | `replace`                  |
        | `/lock`            | `replace`                  |
      operationId: partiallyUpdateTableProperties
      security:
        - oauth:
            - file:write
      summary: Partially update a table's properties
      tags:
        - Content
  /content/tables/{tableId}/properties/rows:
    get:
      description: |
        Returns a [`RowPropertiesListResult`](ref:content#rowpropertieslistresult) for a table
      operationId: getRowProperties
      security:
        - oauth:
            - file:read
      summary: Retrieve table row properties
      tags:
        - Content
  /milestones/creation:
    post:
      operationId: milestoneCreation
      summary: Initiates a request to create a new milestone
      description: |
        Create a new [`Milestone`](ref:milestones#milestone) using a [`MilestoneCreation`](ref:milestones#milestonecreation) request. This is a long running operation. Responses include a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the creation completes, its status will be `completed`, and the response body includes a `resourceURL`. To GET the new milestone, perform a GET on the[...]
      tags:
        - Milestones
      security:
        - oauth:
            - file:write
  /milestones/{milestoneId}:
    get:
      description: Returns a [`Milestone`](ref:milestones#milestone) given its id
      operationId: getMilestoneById
      security:
        - oauth:
            - file:read
      summary: Retrieve a milestone by id
      tags:
        - Milestones
    delete:
      operationId: deleteMilestoneById
      summary: Deletes a milestone
      description: Deletes the [`Milestone`](ref:milestones#milestone) with a given id.
      tags:
        - Milestones
      security:
        - oauth:
            - file:write
    patch:
      operationId: partiallyUpdateMilestoneById
      summary: Partially updates a milestone
      description: |
        Partially updates a [`Milestone`](ref:milestones#milestone) with a given id.

        ### Options
        | Path                   | PATCH Operations Supported         | Value Type             |
        |------------------------|------------------------------------|------------------------|
        | `/title`               | `replace`                          | `string`               |
        | `/remarks`             | `replace`                          | `string`, `null`       |
      tags:
        - Milestones
      security:
        - oauth:
            - file:write
  /programs:
    get:
      description: Returns a paginated list of [programs](ref:sustainability#program).
      operationId: getPrograms
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of programs
      tags:
        - Sustainability
    post:
      description: |
        Creates a new [program](ref:sustainability#program).
      operationId: createProgram
      security:
        - oauth:
            - file:write
      summary: Create a new program
      tags:
        - Sustainability
  /programs/{programId}:
    get:
      description: Retrieves a [program](ref:sustainability#program) given its ID
      operationId: getProgramById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single program
      tags:
        - Sustainability
    patch:
      description: |
        Partially updates the properties of a [program](ref:sustainability#program). Only one property may be updated at a time.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/name`|`replace`, `test`|
      operationId: partiallyUpdateProgramById
      security:
        - oauth:
            - file:write
      summary: Partially update a single program
      tags:
        - Sustainability
  /programs/{programId}/dimensions:
    get:
      description: Returns a paginated list of [dimensions](ref:sustainability#dimension).
      operationId: getDimensions
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of dimensions
      tags:
        - Sustainability
    post:
      description: |
        Creates a new [dimension](ref:sustainability#dimension).
      operationId: createDimension
      security:
        - oauth:
            - file:write
      summary: Create a new dimension
      tags:
        - Sustainability
  /programs/{programId}/dimensions/{dimensionId}:
    get:
      description: Retrieves a [dimension](ref:sustainability#dimension) given its ID
      operationId: getDimensionById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single dimension
      tags:
        - Sustainability
    patch:
      description: |
        Partially updates the properties of a [dimension](ref:sustainability#dimension). Only one property may be updated at a time.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/active`|`replace`, `test`|
        |`/name`|`replace`, `test`|
        |`/values`|`replace`, `test`|
      operationId: partiallyUpdateDimensionById
      security:
        - oauth:
            - file:write
      summary: Partially update a single dimension
      tags:
        - Sustainability
  /programs/{programId}/metrics:
    get:
      description: Returns a paginated list of [Metrics](ref:sustainability#metric).
      operationId: getMetrics
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of metrics
      tags:
        - Sustainability
    post:
      description: |
        Creates a new [metric](ref:sustainability#metric).
      operationId: createMetric
      security:
        - oauth:
            - file:write
      summary: Create a new metric
      tags:
        - Sustainability
  /programs/{programId}/metrics/{metricId}:
    delete:
      description: |
        Deletes a [metric](ref:sustainability#metric) given its ID
      operationId: deleteMetricById
      security:
        - oauth:
            - file:write
      summary: Delete a single metric
      tags:
        - Sustainability
    get:
      description: Retrieves a [`Metric`](ref:sustainability#metric) given its ID
      operationId: getMetricById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single metric
      tags:
        - Sustainability
    patch:
      description: |
        Partially updates the properties of a [metric](ref:sustainability#metric). Only one property may be updated at a time.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/datatype`|`replace`|
        |`/description`|`replace`, `test`|
        |`/index`|`replace`, `test`|
        |`/name`|`replace`, `test`|
        |`/requireNotes`|`replace`, `test`|
        |`/requireSupportingAttachments`|`replace`, `test`|
        |`/topic`|`replace`, `test`|
        |`/unit`|`replace`, `test`|
      operationId: partiallyUpdateMetricById
      security:
        - oauth:
            - file:write
      summary: Partially update a single metric
      tags:
        - Sustainability
  /programs/{programId}/metrics/{metricId}/values:
    get:
      description: Returns a paginated list of [metric Values](ref:sustainability#metricvalue)
      operationId: getValues
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of metric values
      tags:
        - Sustainability
    post:
      description: |
        Creates a new [metric value](ref:sustainability#metricvalue)
      operationId: createValue
      security:
        - oauth:
            - file:write
      summary: Create a new metric value
      tags:
        - Sustainability
  /programs/{programId}/metrics/{metricId}/values/{metricValueId}:
    delete:
      description: |
        Deletes a [metric value](ref:sustainability#metricvalue) value given its ID
      operationId: deleteMetricValueById
      security:
        - oauth:
            - file:write
      summary: Delete a single metric value
      tags:
        - Sustainability
    get:
      description: |
        Retrieves a [metric value](ref:sustainability#metricvalue) value given its ID
      operationId: getMetricValueById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single metric value
      tags:
        - Sustainability
    patch:
      description: |
        Partially updates the properties of a [metric value](ref:sustainability#metricvalue) value. Only one property may be updated at a time.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/notes`|`replace`, `test`|
        |`/value`|`replace`, `test`|
      operationId: partiallyUpdateMetricValueById
      security:
        - oauth:
            - file:write
      summary: Partially update a single metric value
      tags:
        - Sustainability
  /programs/{programId}/metrics/{metricId}/values/batchDeletion:
    post:
      description: |
        Batch delete the given metric values.

        For each value, provide either the id or both the reportingPeriod and coordinates (if any).
        If both are provided, the given id will be used.
      operationId: batchDeletionMetricValues
      security:
        - oauth:
            - file:write
      summary: Initiate a batch deletion of metric values
      tags:
        - Sustainability
  /programs/{programId}/metrics/{metricId}/values/batchUpsertion:
    post:
      description: |
        Batch upsert values for the given metric. The payload is limited to 10MB; break it into multiple requests if necessary.

        For each value, provide either the id or both the reportingPeriod and coordinates (if any).
        If both are provided, the given id will be used.

        The API will validate the request and return a 202 Accepted status.
        However, the operation will be processed asynchronously, so the values may take some time to appear in the system.
        Poll the location provided in the Location header to check the status of the operation.

        If any of the values fail to be processed, no changes will be stored in the system.
      operationId: batchUpsertionMetricValues
      security:
        - oauth:
            - file:write
      summary: Initiate a batch upsertion of metric values
      tags:
        - Sustainability
  /programs/{programId}/permissions:
    get:
      description: |
        Retrieves a paginated list of permissions for a given Sustainability Program
      operationId: getProgramPermissions
      security:
        - oauth:
            - file:read
        - contextless-oauth:
            - file:read
      summary: Retrieve permissions for a program
      tags:
        - Sustainability
  /programs/{programId}/permissions/modification:
    post:
      description: |
        Assign and/or revoke permissions on a Sustainability Program. If any modification in a request fails, all modifications on that request fail. <br /><br /> _To modify an existing permission, the existing permission must first be  explicitly revoked. Then, the new permission needs to be assigned. This  can be done in a single request by sending `toAssign` and `toRevoke` in  the request body._
      operationId: programPermissionsModification
      security:
        - oauth:
            - file:write
        - contextless-oauth:
            - file:write
      summary: Modify permissions on a program
      tags:
        - Sustainability
  /programs/{programId}/topics:
    get:
      description: Returns a paginated list of [topics](ref:sustainability#topic).
      operationId: getTopics
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of topics
      tags:
        - Sustainability
    post:
      description: |
        Creates a new [topic](ref:sustainability#topic).
      operationId: createTopic
      security:
        - oauth:
            - file:write
      summary: Create a new topic
      tags:
        - Sustainability
  /programs/{programId}/topics/{topicId}:
    delete:
      description: |
        Deletes a [topic](ref:sustainability#topic) given its ID
      operationId: deleteTopicById
      security:
        - oauth:
            - file:write
      summary: Delete a single topic
      tags:
        - Sustainability
    get:
      description: |
        Retrieves a [topic](ref:sustainability#topic) given its ID
      operationId: getTopicById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single topic
      tags:
        - Sustainability
    patch:
      description: |
        Partially updates the properties of a [topic](ref:sustainability#topic). Only one property may be updated at a time.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/index`|`replace`, `test`|
        |`/name`|`replace`, `test`|
        |`/parent`|`replace`, `test`|
      operationId: partiallyUpdateTopicById
      security:
        - oauth:
            - file:write
      summary: Partially update a single topic
      tags:
        - Sustainability
  /organizations:
    get:
      description: |
        Returns a paginated list of [organizations](ref:admin#organization).
        This functionality is only available to Managed Service Provider Applications. Contact your CSM for assistance.
      operationId: getOrganizations
      security:
        - contextless-oauth:
            - organization:read
      summary: Retrieve a list of organizations
      tags:
        - Admin
  /organizations/{organizationId}:
    get:
      description: |
        Retrieves an organization given its ID
      operationId: getOrganizationById
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve a single organization
      tags:
        - Admin
    patch:
      description: |
        Updates the properties of an organization.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/name`|`replace`|
      operationId: partiallyUpdateOrganizationById
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Update a single organization
      tags:
        - Admin
  /organizations/{organizationId}/activities:
    get:
      description: |
        Returns a paginated list of activities for a given organization.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the platform will always result in the same Activity ID. Please rely on the ActivityAction `alias` field to determine if an activity is relevant to your use case.
        :::
      operationId: getOrganizationActivities
      security:
        - oauth:
            - activity:read
      summary: Retrieve a list of activities for an organization
      tags:
        - Activities
  /organizations/{organizationId}/orgReportUsers:
    get:
      description: |
        Similar to an organization admin's "People View" export, this returns a paged list of specific details about the organization's users, including their usernames, display names, email addresses, SAML IDs, last logins, workspace memberships, licenses and roles. Results are sorted by displayName. <br /><br /> To obtain an organization's users, you need its organizationId. To view the organizationId in Wdesk, click your name in the lower left, and select <strong>Organization Admin</strong>. [...]
      operationId: getOrgReportUsers
      security:
        - oauth:
            - organization:read
      summary: List organization users
      tags:
        - Reports
  /organizations/{organizationId}/roles:
    get:
      description: |
        Retrieves available roles within an organization given its ID
      operationId: getOrganizationRoles
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve available roles within an organization
      tags:
        - Admin
  /organizations/{organizationId}/solutions:
    get:
      description: |
        Retrieves available solutions within an organization given its ID
      operationId: getOrganizationSolutions
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve available solutions within an organization
      tags:
        - Admin
  /organizations/{organizationId}/users:
    get:
      description: Retrieve users in an organization.
      operationId: getOrganizationUsers
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve list of an organizations users
      tags:
        - Admin
    post:
      description: |
        Creates a new OrganizationUser resource
      operationId: createOrganizationUser
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Create a new organization User
      tags:
        - Admin
  /organizations/{organizationId}/users/assignment:
    post:
      description: Assign an existing organization user to an organization
      operationId: assignUserToOrganization
      security:
        - oauth:
            - organization:write
      summary: Assign existing user to organization
      tags:
        - Admin
  /organizations/{organizationId}/users/{userId}:
    delete:
      description: |
        Delete a user from an organization
      operationId: deleteOrganizationUserById
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Delete an organization user
      tags:
        - Admin
    get:
      description: |
        Retrieves an organization user given its ID
      operationId: getOrganizationUserById
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve a single user in an organization
      tags:
        - Admin
    patch:
      description: |
        Partially update the properties of a [User](ref:admin#user) within an Organization.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/givenName`|`replace`|
        |`/familyName`|`replace`|
        |`/displayName`|`replace`|
        |`/username`|`replace`|
        |`/email`|`replace`|
      operationId: partiallyUpdateOrganizationUserById
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Partially update a single user in an organization
      tags:
        - Admin
  /organizations/{organizationId}/users/{userId}/roles:
    get:
      description: |
        Retrieve a User's roles within an Organization
      operationId: getOrganizationUserRoleList
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: List Roles assigned to an Organization User
      tags:
        - Admin
  /organizations/{organizationId}/users/{userId}/roles/assignment:
    post:
      description: |
        Assign a User's roles within an Organization. If one assignment fails, all assignments fail.
      operationId: assignOrganizationUserRoles
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Assign roles for an Organization User
      tags:
        - Admin
  /organizations/{organizationId}/users/{userId}/roles/revocation:
    post:
      description: |
        Revoke a User's roles within an Organization. If one revocation fails, all revocations fail.
      operationId: revokeOrganizationUserRoles
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Revoke roles for an Organization User
      tags:
        - Admin
  /organizations/{organizationId}/workspaces:
    get:
      description: Retrieve a list of workspaces in an organization.
      operationId: getWorkspaces
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve list of workspaces
      tags:
        - Admin
    post:
      description: |
        Creates a new workspace resource
      operationId: createWorkspace
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Create a new workspace
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}:
    get:
      description: |
        Retrieves a workspace given its ID
      operationId: getWorkspaceById
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve a single workspace
      tags:
        - Admin
    patch:
      description: |
        Updates the properties of a workspace.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/name`|`replace`|
      operationId: partiallyUpdateWorkspaceById
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Update a single workspace
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/activities:
    get:
      description: |
        Returns a paginated list of activities for a given organization and workspace.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the platform will always result in the same Activity ID. Please rely on the ActivityAction `alias` field to determine if an activity is relevant to your use case.
        :::
      operationId: getOrganizationWorkspaceActivities
      security:
        - oauth:
            - activity:read
      summary: Retrieve a list of activities for a workspace
      tags:
        - Activities
  /organizations/{organizationId}/workspaces/{workspaceId}/groups:
    get:
      description: Retrieve a list of groups in a workspace
      operationId: getWorkspaceGroups
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve list of groups
      tags:
        - Admin
    post:
      description: |
        Creates a new group resource
      operationId: createWorkspaceGroup
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Create a new group in a workspace
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/groups/{groupId}:
    delete:
      description: |
        Deletes a group given its ID.
      operationId: deleteWorkspaceGroupById
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Delete a single group
      tags:
        - Admin
    get:
      description: |
        Retrieves a group given its ID
      operationId: getWorkspaceGroupById
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve a single group
      tags:
        - Admin
    patch:
      description: |
        Updates the properties of a group.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/name`|`replace`|
      operationId: partiallyUpdateWorkspaceGroupById
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Update a single group
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/groups/{groupId}/members:
    get:
      description: Retrieve a list of members in a workspace group
      operationId: getWorkspaceGroupMembers
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve list of group members
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/groups/{groupId}/members/modification:
    post:
      description: |
        Add and/or remove members from a group. When failures are encountered for particular members, error responses are returned for each.
      operationId: modifyWorkspaceGroupMembers
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Modify members in a group
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/memberships:
    get:
      description: Retrieve all memberships of a workspace
      operationId: getWorkspaceMemberships
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve list of workspace memberships
      tags:
        - Admin
    post:
      description: |
        Creates a new `WorkspaceMembership` resource
      operationId: createWorkspaceMembership
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Create a new workspace membership
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/memberships/membershipCreation:
    post:
      description: |
        Creates a new `WorkspaceMembership` and allows control over notification options.
      operationId: workspaceMembershipCreationWithOptions
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Create a new workspace membership with options
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/memberships/{workspaceMembershipId}:
    delete:
      description: |
        Revoke a user's membership to a `Workspace`.
      operationId: deleteWorkspaceMembershipById
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Delete a workspace membership
      tags:
        - Admin
    get:
      description: |
        Retrieves a workspace membership given its ID
      operationId: getWorkspaceMembershipById
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve a single workspace membership
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/memberships/{workspaceMembershipId}/roles:
    get:
      description: |
        Retrieves available roles for a workspace membership
      operationId: getOrganizationWorkspaceMembershipRoles
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve available roles for a workspace membership
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/memberships/{workspaceMembershipId}/roles/assignment:
    post:
      description: |
        Assign a member's roles within a Workspace. If one assignment fails, all assignments fail.
      operationId: assignWorkspaceMembershipRoles
      security:
        - oauth:
            - organization:write
        - contextless-oauth:
            - organization:write
      summary: Assign roles for a Workspace Membership
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/memberships/{workspaceMembershipId}/roles/revocation:
    post:
      description: |
        Revoke a member's roles within a Workspace. If one revocation fails, all revocations fail.
      operationId: revokeWorkspaceMembershipRoles
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Revoke roles for a Workspace Membership
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/roles:
    get:
      description: |
        Retrieves available roles within a workspace given an organization and workspace ID
      operationId: getOrganizationWorkspaceRoles
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve available roles within a workspace
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/solutions:
    get:
      description: |
        Retrieves available solutions within a workspace given its ID
      operationId: getWorkspaceSolutions
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve available solutions within a workspace
      tags:
        - Admin
  /organizations/{organizationId}/workspaces/{workspaceId}/solutions/{solutionId}:
    get:
      description: |
        Retrieve a solutions within a workspace given its ID
      operationId: getWorkspaceSolutionsByID
      security:
        - oauth:
            - organization:read
        - contextless-oauth:
            - organization:read
      summary: Retrieve a solution by id
      tags:
        - Admin
  /oauth2/token:
    post:
      summary: Retrieve a token
      description: |
        Include the client_id and client_secret in the body of the request as form encoded parameters. For example, the body of the request would be `grant_type=client_credentials&client_id=<client_id>&client_secret=<client_secret>`. The client can optionally specify a `scope` parameter to limit the scope of the returned [access token](ref:helpers#bearertoken). In turn, the server uses a `scope` response parameter to inform the client of the scope of the actual access token issued. The actual `s[...]
      operationId: tokenRequest
      tags:
        - IAM
  /documents:
    get:
      description: Returns a paginated list of [documents](ref:documents#document).
      operationId: getDocuments
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of documents
      tags:
        - Documents
  /documents/{documentId}:
    get:
      description: |
        Retrieves a [document](ref:documents#document) given its ID.
      operationId: getDocumentById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single document
      tags:
        - Documents
    patch:
      description: |
        Updates the properties of a [document](ref:documents#document).

        This is a long running operation. Responses include a `Location` header,
        which indicates where to poll for results. For more details on long-running job polling,
        see [Operations endpoint](ref:getoperationbyid).

        ### Options

        |Path                             |PATCH Operations Supported        |
        |---------------------------------|----------------------------------|
        |`/customFields/<custom field id>`|`add`, `remove`, `replace`, `test`|
        |`/customFieldGroups`             |`add`, `remove`, `replace`, `test`|
        |`/sectionCustomFieldGroups`      |`add`, `remove`, `replace`, `test`|
        |`/lock`                          |`replace`                         |

        ### Examples

        #### Add a custom field value

        ```json
        [
          {
            "op": "add",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva"
          }
        ]
        ```

        #### Remove a custom field value

        ```json
        [
          {
            "op": "remove",
            "path": "/customFields/com.workiva.gsr.legal_entity"
          }
        ]
        ```

        #### Replace a custom field value

        ```json
        [
          {
            "op": "replace",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva, Inc."
          }
        ]
        ```

        #### Verifying customFieldGroup is empty before replacing the list

        ```json
        [
          {
            "op": "test",
            "path": "/customFieldGroups",
            "value": []
          },
          {
            "op": "replace",
            "path": "/customFieldGroups",
            "value": ["gsr.reporting"]
          }
        ]
        ```

        #### Adding a customFieldGroup to the end of a list

        ```json
        [
          {
            "op": "add",
            "path": "/customFieldGroups/-",
            "value": "gsr.reporting"
          }
        ]
        ```
      operationId: partiallyUpdateDocumentById
      security:
        - oauth:
            - file:write
      summary: Partially update a single document
      tags:
        - Documents
  /documents/{documentId}/export:
    post:
      description: |
        Asynchronously exports a [document](ref:documents#document) as .PDF or .DOCX., or .XHTML. Options are specified using a [DocumentExport](ref:documents#documentexport) object.
        When exporting XHTML that you plan to edit or modify, use the `editableXhtml` option. Otherwise, the export retains fidelity so it visually matches the document as it appears in the browser.
        Responses include a `Location` header, which indicates where to poll for export results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the export completes, its status will be `completed`, and the response body includes a `resourceURL`. To download the exported file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the export request. For more details, see [Authentication documentation](ref:authe[...]
      operationId: documentExport
      security:
        - oauth:
            - file:read
      summary: Initiate a document export
      tags:
        - Documents
  /documents/{documentId}/filters/reapplication:
    post:
      description: |
        Performs a [`DocumentFiltersReapplication`](ref:content#documentfiltersreapplication) on the specified document.
        This endpoint is used to refresh the document's filters based on the latest state or configuration changes.
        The filters are reapplied in the context of the document's current data state.

        This is a long-running operation. Responses include a `Location` header, which indicates where to poll for results.
        For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: documentFiltersReapplication
      security:
        - oauth:
            - file:write
      summary: Reapply filters to the document
      tags:
        - Documents
  /documents/{documentId}/links/publication:
    post:
      description: |
        Publishes the links in a document - either all (as document owner) or only one's own. Content at the latest document revision will be used for publish.
        The response also includes a `Location` header, which indicates where to poll for operation results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: documentLinksPublication
      security:
        - oauth:
            - file:write
      summary: Initiate publication of links in a document
      tags:
        - Documents
  /documents/{documentId}/milestones:
    get:
      description: Returns [MilestoneListResult](ref:milestones#milestonelistresult).
      operationId: getDocumentMilestones
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of milestones for a document
      tags:
        - Documents
  /documents/{documentId}/permissions:
    get:
      description: |
        Retrieves a paginated list of permissions for a given document
      operationId: getDocumentPermissions
      security:
        - oauth:
            - file:read
        - contextless-oauth:
            - file:read
      summary: Retrieve permissions for a document
      tags:
        - Documents
  /documents/{documentId}/permissions/modification:
    post:
      description: |
        Assign and/or revoke permissions on a document. If any modification in a request fails, all modifications on that request fail. <br /><br /> _To modify an existing permission, the existing permission must first be  explicitly revoked. Then, the new permission needs to be assigned. This  can be done in a single request by sending `toAssign` and `toRevoke` in  the request body._
      operationId: documentPermissionsModification
      security:
        - oauth:
            - file:write
        - contextless-oauth:
            - file:write
      summary: Modify permissions on a document
      tags:
        - Documents
  /documents/{documentId}/sections:
    get:
      description: |
        Returns a list of [sections](ref:documents#section).
      operationId: getSections
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of sections
      tags:
        - Documents
    post:
      description: |
        Creates a new [section](ref:documents#section) in a [document](ref:documents#document), given its properties. By default, the new section appears at the top-most position.
      operationId: createSection
      security:
        - oauth:
            - file:write
      summary: Create a new section in a document
      tags:
        - Documents
  /documents/{documentId}/sections/{sectionId}:
    delete:
      description: |
        Deletes a [section](ref:documents#section) given its ID.
      operationId: deleteSectionById
      security:
        - oauth:
            - file:write
      summary: Delete a single section
      tags:
        - Documents
    get:
      description: |
        Retrieves a [section](ref:documents#section) given its ID.
      operationId: getSectionById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single section
      tags:
        - Documents
    patch:
      description: |
        Updates the properties of a [section](ref:documents#section).

        This is a long running operation. Responses include a `Location` header,
        which indicates where to poll for results. For more details on long-running job polling,
        see [Operations endpoint](ref:getoperationbyid).

        ### Options

        | Path                                     | PATCH Operations Supported         |
        |------------------------------------------|------------------------------------|
        | `/name`                                  | `replace`                          |
        | `/parent`                                | `replace`                          |
        | `/parent/id`                             | `replace`                          |
        | `/index`                                 | `replace`                          |
        | `/nonPrinting`                           | `replace`                          |
        | `/customFields`                          | `add`, `remove`, `replace`, `test` |
        | `/customFields/<customFieldId>`          | `add`, `remove`, `replace`, `test` |
        | `/lock`                                  | `replace`                          |
        | `/properties/margins/top`                | `replace`                          |
        | `/properties/margins/bottom`             | `replace`                          |
        | `/properties/margins/right`              | `replace`                          |
        | `/properties/margins/left`               | `replace`                          |
        | `/properties/pageBreakBefore`            | `replace`                          |
        | `/properties/exhibit`                    | `replace`                          |
        | `/properties/edgarKeepTogether`          | `replace`                          |
        | `/properties/pageNumber/reset`           | `replace`                          |
        | `/properties/pageNumber/startAt`         | `replace`                          |
        | `/properties/background/color`           | `replace`                          |
        | `/properties/background/image`           | `replace`                          |
        | `/properties/restartFootnoteNumbering`   | `replace`                          |
        | `/properties/header/alternatingPage`     | `replace`                          |
        | `/properties/header/differentFirstPage`  | `replace`                          |
        | `/properties/header/differentLastPage`   | `replace`                          |
        | `/properties/header/margin/right`        | `replace`                          |
        | `/properties/header/margin/left`         | `replace`                          |
        | `/properties/header/matchSectionMargins` | `replace`                          |
        | `/properties/header/positionFromTop`     | `replace`                          |
        | `/properties/header/sameAsPrevious`      | `replace`                          |
        | `/properties/footer/alternatingPage`     | `replace`                          |
        | `/properties/footer/differentFirstPage`  | `replace`                          |
        | `/properties/footer/differentLastPage`   | `replace`                          |
        | `/properties/footer/margin/right`        | `replace`                          |
        | `/properties/footer/margin/left`         | `replace`                          |
        | `/properties/footer/matchSectionMargins` | `replace`                          |
        | `/properties/footer/positionFromBottom`  | `replace`                          |
        | `/properties/footer/sameAsPrevious`      | `replace`                          |

        ### Examples

        #### Update the name of a section

        ```json
        [
          {
            "op": "replace",
            "path": "/name",
            "value": "Introduction"
          }
        ]
        ```

        #### Update the parent of a section (preserving its index)

        ```json
        [
          {
            "op": "replace",
            "path": "/parent",
            "value": {
              "id": "b9b3ddb587744a27aafda3c9865f1f0a_1"
            }
          }
        ]
        ```

        #### Update the parent of a section (making it the first child)

        ```json
        [
          {
            "op": "replace",
            "path": "/parent",
            "value": {
              "id": "b9b3ddb587744a27aafda3c9865f1f0a_1"
            }
          },
          {
            "op": "replace",
            "path": "/index",
            "value": 0
          }
        ]
        ```

        #### Add a custom field value
        ```json

        [
          {
            "op": "add",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva"
          }
        ]
        ```

        #### Remove a custom field value

        ```json
        [
          {
            "op": "remove",
            "path": "/customFields/com.workiva.gsr.legal_entity"
          }
        ]
        ```

        #### Replace a custom field value
        ```json

        [
          {
            "op": "replace",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva, Inc."
          }
        ]
        ```
      operationId: partiallyUpdateSectionById
      security:
        - oauth:
            - file:write
      summary: Partially update a single section
      tags:
        - Documents
  /documents/{documentId}/sections/{sectionId}/copy:
    post:
      description: |-
        Asynchronously copies a [section](ref:documents#section) given details about the copy's destination within the same or another document. Options are specified using a [SectionCopy](ref:documents#sectioncopy) object.

        Copies only the section's content — not any labels, comments, tasks, or formatting from a style guide. Unless otherwise specified, the copy appears at the top level of its destination document, with an index of 0, and with the same name as the original section.
      operationId: copySection
      security:
        - oauth:
            - file:write
      summary: Copy section
      tags:
        - Documents
  /documents/{documentId}/sections/edit:
    post:
      description: |
        Updates the properties of a collection of [sections](ref:documents#section) in a document using [SectionsEdits](ref:documents#sectionsedit) request. This is a long running operation.
        Responses include a `Location` header, which indicates where to poll for results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the update completes, its status will be `completed`.
      operationId: editSections
      security:
        - oauth:
            - file:write
      summary: Initiate sections edits
      tags:
        - Documents
  /documents/{documentId}/sections/{sectionId}/permissions:
    get:
      description: |
        Retrieves a paginated list of permissions for the given section in a document
      operationId: getSectionPermissions
      security:
        - oauth:
            - file:read
        - contextless-oauth:
            - file:read
      summary: Retrieve permissions for a section in a document
      tags:
        - Documents
  /documents/{documentId}/sections/{sectionId}/permissions/modification:
    post:
      description: |
        Assign and/or revoke permissions on a section. If any modification in a request fails, all modifications on that request fail. <br /><br /> _To modify an existing permission, the existing permission must first be  explicitly revoked. Then, the new permission needs to be assigned. This  can be done in a single request by sending `toAssign` and `toRevoke` in  the request body._
      operationId: sectionPermissionsModification
      security:
        - oauth:
            - file:write
        - contextless-oauth:
            - file:write
      summary: Modify permissions on a given section of a document
      tags:
        - Documents
  /files:
    get:
      description: Returns a paginated list of [files](ref:files#file).
      operationId: getFiles
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of files
      tags:
        - Files
    post:
      description: |
        Creates a new [file](ref:files#file). Requires name and kind. kind
        must be one of `Document`, `Spreadsheet`, `Presentation`, or `Folder` and
        is case-sensitive. Use the `container` attribute to specify the container that houses the file, such
        as a folder. If empty, the root folder is the container. Files are created
        asynchronously and may not immediately be available on a subsequent `GET`.

        ### Examples
        #### Create a new document at the root of the file system
        ```json
        {
          "name": "2019 Year-End Summary",
          "kind": "Document"
        }
        ```

        #### Create a folder within an existing folder
        ```json
        {
          "name": "2019 Year-End Documents",
          "kind": "Folder",
          "container": "V0ZFYXRhSW50aXR5IkZvbGRlcjoxSkFGOTZGRjiENDk1Qzk4RjQ4OTgzN0M6ODdDNjZENi"
        }
        ```
      operationId: createFile
      security:
        - oauth:
            - file:write
      summary: Create a new file
      tags:
        - Files
  /files/import:
    post:
      description: |
        Import a file for conversion to a Workiva equivalent. This is a long running operation.
        Response includes an `uploadUrl` which indicates where to upload the file for import. To upload the file, perform a PUT against the `uploadUrl` with the same authentication credentials and flow as the import request. For more details, see [Authentication documentation](ref:authentication).
      operationId: importFile
      security:
        - oauth:
            - file:write
      summary: Initiate a file import
      tags:
        - Files
  /files/trash:
    get:
      description: Returns a paginated list of files that have been trashed.
      operationId: getTrashedFiles
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of trashed files
      tags:
        - Files
  /files/{fileId}:
    get:
      description: |
        Retrieves a [file](ref:files#file) given its ID
      operationId: getFileById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single file
      tags:
        - Files
    patch:
      description: |
        Partially updates the properties of a [file](ref:files#file). Only one property may be updated at a time.
        Updates are applied asynchronously and may not immediately be reflected on a subsequent `GET`.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/container`|`replace`|
        |`/name`|`replace`|
      operationId: partiallyUpdateFileById
      security:
        - oauth:
            - file:write
      summary: Partially update a single file
      tags:
        - Files
  /files/{fileId}/copy:
    post:
      description: |
        Copy a file to a new location. This is a long running operation. Responses include a `Location` header, which indicates where to poll for copy results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
        Once the operation is completed, the `resourceUrl` field will be populated with a link to the   [Retrieve copy file results for a single operation endpoint](ref:getcopyfileresults)  to see the results of the File Copy Request.
      operationId: copyFile
      security:
        - oauth:
            - file:write
      summary: Initiate a file copy
      tags:
        - Files
  /files/{fileId}/export:
    post:
      description: |
        Export a file by its unique ID. This is a long running operation. Responses include a `Location` header, which indicates where to poll for export results. For  more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
        When the export process is complete, the status of the Operation  will change to completed. The `resourceUrl` field of the operation will contain  the download url of the exported file. To download the file, perform a GET against  the `resourceUrl` with the same authentication credentials and flow as the export request.  For more details, see Authentication documentation.
        For more on Document, Spreadsheet, and Presentation export options, see the following: [Documents](https://developers.workiva.com/2026-01-01/platform-documentexport), [Spreadsheets](https://developers.workiva.com/2026-01-01/platform-spreadsheetexport), and [Presentations](https://developers.workiva.com/2026-01-01/platform-presentationexport).
      operationId: exportFileById
      security:
        - oauth:
            - file:write
      summary: Initiate a file export by ID
      tags:
        - Files
  /files/{fileId}/restore:
    post:
      description: Restores a file given its ID. If the file being restored is a Folder, its contents will be recursively restored.
      operationId: restoreFileById
      security:
        - oauth:
            - file:write
      summary: Initiate restoration of a single file
      tags:
        - Files
  /files/{fileId}/trash:
    post:
      description: Trashes a file given its ID. If the file being trashed is a Folder, its contents will be recursively trashed.
      operationId: trashFileById
      security:
        - oauth:
            - file:write
      summary: Initiate trash of a single file
      tags:
        - Files
  /files/{fileId}/permissions:
    get:
      description: |
        Retrieves a paginated list of permissions for a given file
      operationId: getFilePermissions
      security:
        - oauth:
            - file:read
        - contextless-oauth:
            - file:read
      summary: Retrieve permissions for a file
      tags:
        - Files
  /files/{fileId}/permissions/modification:
    post:
      description: |
        Assign and/or revoke permissions on a file. If any modification in a request fails, all modifications on that request fail. <br /><br /> _To modify an existing permission, the existing permission must first be  explicitly revoked. Then, the new permission needs to be assigned. This  can be done in a single request by sending `toAssign` and `toRevoke` in  the request body._
      operationId: filePermissionsModification
      security:
        - oauth:
            - file:write
        - contextless-oauth:
            - file:write
      summary: Modify permissions on a file
      tags:
        - Files
  /graph/edits:
    post:
      description: |-
        Creates new record [edits](ref:graph#edit) given their properties. Each edit in the supplied array requires at least an `operation` and `targetId`. Up to 1000 edits may be processed per request.
        If there are invalid edits, the error details will include a list of errors encountered. Each message will include the zero-based position of the failed edit in the provided list of edits.
      operationId: createEdits
      security:
        - oauth:
            - graph:write
      summary: Create new record edits
      tags:
        - Graph
  /graph/records:
    get:
      description: Returns a list of [records](ref:graph#record) matching the provided filters. At least one filter is required. If no filter is provided an error will be returned.
      operationId: getRecords
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of records
      tags:
        - Graph
  /graph/records/{recordId}:
    get:
      description: Retrieves a [record](ref:graph#record) given its ID. The unique identifier is typically a UUID, but it may be a different unique string in some cases.
      operationId: getRecordById
      security:
        - oauth:
            - graph:read
      summary: Retrieve a single record
      tags:
        - Graph
  /graph/reports/{reportId}/export:
    post:
      description: |
        Asynchronously exports a graph report (only CSV available at this time).
        This endpoint will execute the query of a saved report and export to the specified format (only CSV available at this time). The ID of the [record](ref:graph#record) containing the saved report is used for the `reportID` path element. Reports are stored in records of type `DataSource` and `ReportView`. The list of applicable records can be retrieved from the `/records` endpoint such as `GET /records?$filter=type eq DataSource or type eq ReportView`. A filter on the `title` property shoul[...]
        Responses include a `Location` header, which indicates where to poll for export results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the export completes, its status will be `completed`, and the response body includes a `resourceURL`. To download the exported file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the export request. For more details, see [Authentication documentation](ref:authe[...]
      operationId: graphReportExport
      security:
        - oauth:
            - graph:read
      summary: Initiate a graph report export
      tags:
        - Graph
  /graph/types:
    get:
      description: |
        The Types endpoint is used to discover what [types](ref:graph#type) of records exist and their attributes. This endpoint lets you know what to expect from the Records endpoints.
      operationId: getTypes
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of types
      tags:
        - Graph
  /graph/types/{typeId}:
    get:
      description: |
        Returns a record [type](ref:graph#type) given its ID (name)
      operationId: getTypeById
      security:
        - oauth:
            - graph:read
      summary: Retrieve a single type
      tags:
        - Graph
  /operations/{operationId}:
    get:
      description: |
        Retrieves an [operation](ref:operations#operation) given its ID. <br /><br /> Note: This endpoint is rate-limited. You may experience rates as low as 1 request per second. When polling for updates, examine the `Retry-After` header and retry after that many seconds.
      operationId: getOperationById
      security:
        - oauth: []
      summary: Retrieve a single operation
      tags:
        - Operations
  /operations/{operationId}/copyFileResults:
    get:
      description: |
        Returns a [`CopyFileListResult`](ref:operations#copyfilelistresult) describing the results of a file copy operation. <br /><br /> Note: This endpoint is rate-limited. You may experience rates as low as 1 request per second. When polling for updates, examine the `Retry-After` header and retry after that many seconds.
      operationId: getCopyFileResults
      security:
        - oauth:
            - file:read
      summary: Retrieve copy file results for a single operation
      tags:
        - Operations
  /operations/{operationId}/destinationLinkSourceConversionResults:
    get:
      description: |
        Returns the results for a destination link source conversion.
        This will include the new source anchor's ID and the destination link ID for the old source (if any).
      operationId: getDestinationLinkSourceConversionResults
      security:
        - oauth:
            - file:read
      summary: Retrieves the results from a destination link source conversion.
      tags:
        - Operations
  /operations/{operationId}/imageUploadResults:
    get:
      description: Returns a [`ImageUploadResultCollection`](ref:operations#imageuploadresultcollection) describing the results of a image upload.
      operationId: getImageUploadCreationResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a image upload
      tags:
        - Operations
  /operations/{operationId}/importFileResults:
    get:
      description: |
        Returns a [`ImportFileListResult`](ref:operations#importfilelistresult) describing the results of a file import operation. <br /><br /> Note: This endpoint is rate-limited. You may experience rates as low as 1 request per second. When polling for updates, examine the `Retry-After` header and retry after that many seconds.
      operationId: getImportFileResults
      security:
        - oauth:
            - file:read
      summary: Retrieve import file results for a single operation
      tags:
        - Operations
  /operations/{operationId}/metricValuesBatchUpsertionResults:
    get:
      description: |
        Returns a [`MetricValuesListResult`](ref:sustainability#metricvalueslistresult) describing the results of a metric values batch upsertion operation. <br /><br /> Note: This endpoint is rate-limited. You may experience rates as low as 1 request per second. When polling for updates, examine the `Retry-After` header and retry after that many seconds.
      operationId: getBatchUpsertionMetricValuesResults
      security:
        - oauth:
            - file:read
      summary: Retrieve the results of a metric values batch upsertion operation
      tags:
        - Operations
  /operations/{operationId}/milestoneCreationResults:
    get:
      operationId: getMilestoneCreationResults
      summary: Retrieve results for a milestone creation
      description: Returns a [`MilestoneCreationListResult`](ref:operations#milestonecreationlistresult) describing the results of a milestone creation.
      tags:
        - Operations
      security:
        - oauth:
            - file:read
  /operations/{operationId}/patchDocumentResults:
    get:
      description: Returns a [`PatchDocumentListResult`](ref:operations#patchdocumentlistresult) describing the results of a patch document.
      operationId: getPatchDocumentResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a patch document
      tags:
        - Operations
  /operations/{operationId}/patchPresentationResults:
    get:
      description: Returns a [`PatchPresentationListResult`](ref:operations#patchpresentationlistresult) describing the results of a patch presentation.
      operationId: getPatchPresentationResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a patch presentation
      tags:
        - Operations
  /operations/{operationId}/patchSectionResults:
    get:
      description: Returns a [`PatchSectionListResult`](ref:operations#patchsectionlistresult) describing the results of a patch section.
      operationId: getPatchSectionResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a patch Section
      tags:
        - Operations
  /operations/{operationId}/patchSheetResults:
    get:
      description: Returns a [`PatchSheetListResult`](ref:operations#patchsheetlistresult) describing the results of a patch sheet.
      operationId: getPatchSheetResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a patch sheet
      tags:
        - Operations
  /operations/{operationId}/patchSlideLayoutResults:
    get:
      description: Returns a [`PatchSlideLayoutListResult`](ref:operations#patchslidelayoutlistresult) describing the results of a patch slide layout.
      operationId: getPatchSlideLayoutResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a patch slide layout
      tags:
        - Operations
  /operations/{operationId}/patchSlideResults:
    get:
      description: Returns a [`PatchSlideListResult`](ref:operations#patchslidelistresult) describing the results of a patch slide.
      operationId: getPatchSlideResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a patch slide
      tags:
        - Operations
  /operations/{operationId}/patchSpreadsheetResults:
    get:
      description: Returns a [`PatchSpreadsheetListResult`](ref:operations#patchspreadsheetlistresult) describing the results of a patch spreadsheet.
      operationId: getPatchSpreadsheetResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a patch spreadsheet
      tags:
        - Operations
  /operations/{operationId}/patchTablePropertiesResults:
    get:
      description: Returns a [`PatchTablePropertiesListResult`](ref:operations#patchtablepropertieslistresult) describing the results of a patch table properties.
      operationId: getPatchTablePropertiesResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a patch table properties
      tags:
        - Operations
  /operations/{operationId}/rangeLinkEditResults:
    get:
      description: Returns a [`RangeLinkEditResultCollection`](ref:operations#rangelinkeditresultcollection) describing the results of a range link edit.
      operationId: getRangeLinkEditResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a range link edit
      tags:
        - Operations
  /operations/{operationId}/richTextBatchEditResults:
    get:
      description: Returns a [`RichTextEditListResult`](ref:operations#richtexteditlistresult) describing the results of a rich text batch edit.
      operationId: getRichTextBatchEditResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a rich text batch edit
      tags:
        - Operations
  /operations/{operationId}/richTextAnchorCreationResults:
    get:
      description: Returns a [`RichTextAnchorCreationResultCollection`](ref:operations#richtextanchorcreationresultcollection) describing the results of a rich text anchor creation.
      operationId: getRichTextAnchorCreationResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a rich text anchor creation
      tags:
        - Operations
  /operations/{operationId}/richTextDuplicationEditResults:
    get:
      description: Returns a [`RichTextDuplicationEditListResult`](ref:operations#richtextduplicationeditlistresult) describing the results of a rich text duplication edit.
      operationId: getRichTextDuplicationEditResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a rich text duplication edit
      tags:
        - Operations
  /operations/{operationId}/richTextLinksBatchEditResults:
    get:
      description: Returns a [`RichTextLinksEditListResult`](ref:operations#richtextlinkseditlistresult) describing the results of a rich text batch edit.
      operationId: getRichTextLinksBatchEditResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a rich text links batch edit
      tags:
        - Operations
  /operations/{operationId}/tableAnchorCreationResults:
    get:
      description: Returns a [`TableAnchorCreationResultCollection`](ref:operations#tableanchorcreationresultcollection) describing the results of a table anchor creation.
      operationId: getTableAnchorCreationResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a table anchor creation
      tags:
        - Operations
  /operations/{operationId}/tableCellEditResults:
    get:
      description: Returns a [`TableCellEditListResult`](ref:operations#tablecelleditlistresult) describing the results of a table cell edit.
      operationId: getTableCellEditResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a table cell edit
      tags:
        - Operations
  /operations/{operationId}/tableEditResults:
    get:
      description: Returns a [`TableEditListResult`](ref:operations#tableeditlistresult) describing the results of a table edit.
      operationId: getTableEditResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a table edit
      tags:
        - Operations
  /operations/{operationId}/tableLinksEditResults:
    get:
      description: Returns a [`TableLinksEditListResult`](ref:operations#tablelinkseditlistresult) describing the results of a table links edit.
      operationId: getTableLinksEditResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a table links edit
      tags:
        - Operations
  /operations/{operationId}/tableReapplyFilterResults:
    get:
      description: Returns a [`TableReapplyFilterListResult`](ref:operations#tablereapplyfilterlistresult) describing the results of a table reapply filter.
      operationId: getTableReapplyFilterResults
      security:
        - oauth:
            - file:read
      summary: Retrieve results for a table reapply filter
      tags:
        - Operations
  /permissions:
    get:
      description: Returns a list of permissions.
      operationId: getPermissions
      security:
        - oauth:
            - file:read
        - contextless-oauth:
            - file:read
      summary: Retrieve a list of all available permissions
      tags:
        - Permissions
  /permissions/{permissionId}:
    get:
      description: |
        Retrieves a permission given its ID
      operationId: getPermissionById
      security:
        - oauth:
            - file:read
        - contextless-oauth:
            - file:read
      summary: Retrieve a single permission
      tags:
        - Permissions
  /presentations/{presentationId}:
    get:
      description: |
        Retrieves a presentation given its ID.
      operationId: getPresentationById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single presentation
      tags:
        - Presentations
    patch:
      description: |
        Updates the properties of a [presentation](ref:presentations#presentation).

        This is a long running operation. Responses include a `Location` header,
        which indicates where to poll for results. For more details on long-running
        job polling, see [Operations endpoint](ref:getoperationbyid).


        ### Options

        | Path                              | PATCH Operations Supported         |
        |-----------------------------------|------------------------------------|
        | `/customFields/<custom field id>` | `add`, `remove`, `replace`, `test` |
        | `/customFieldGroups`              | `add`, `remove`, `replace`, `test` |
        | `/slideCustomFieldGroups`         | `add`, `remove`, `replace`, `test` |
        | `/lock`                           | `replace`                          |


        ### Examples

        #### Add a custom field value

        ```json
        [
          {
            "op": "add",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva"
          }
        ]
        ```

        #### Remove a custom field value

        ```json
        [
          {
            "op": "remove",
            "path": "/customFields/com.workiva.gsr.legal_entity"
          }
        ]
        ```

        #### Replace a custom field value

        ```json
        [
          {
            "op": "replace",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva, Inc."
          }
        ]
        ```

        #### Verifying customFieldGroup is empty before replacing the list

        ```json
        [
          {
            "op": "test",
            "path": "/customFieldGroups",
            "value": []
          },
          {
            "op": "replace",
            "path": "/customFieldGroups",
            "value": ["gsr.reporting"]
          }
        ]
        ```

        #### Adding a customFieldGroup to the end of a list

        ```json
        [
          {
            "op": "add",
            "path": "/customFieldGroups/-",
            "value": "gsr.reporting"
          }
        ]
        ```
      operationId: partiallyUpdatePresentationById
      security:
        - oauth:
            - file:write
      summary: Partially updates a single presentation
      tags:
        - Presentations
  /presentations/{presentationId}/export:
    post:
      description: |
        Asynchronously export a presentation as .PDF or .PPTX. Options are specified using a [PresentationExport](ref:presentations#presentationexport) object.

        Responses include a `Location` header, which indicates where to poll for export results. For more details on long-running job polling, see [ Operations endpoint ](ref:getoperationbyid). When the export completes, its status will be `completed`, and the response body includes a `resourceURL`. To download the exported file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the export request. For more details, see [Authentication documentation](ref:aut[...]
      operationId: presentationExport
      security:
        - oauth:
            - file:read
      summary: Initiate a presentation export
      tags:
        - Presentations
  /presentations/{presentationId}/filters/reapplication:
    post:
      description: |
        Performs a [`PresentationFiltersReapplication`](ref:content#presentationfiltersreapplication) on the specified presentation.
        This endpoint is used to refresh the presentation's filters based on the latest state or configuration changes.
        The filters are reapplied in the context of the presentation's current data state.

        This is a long-running operation. Responses include a `Location` header, which indicates where to poll for results.
        For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: presentationFiltersReapplication
      security:
        - oauth:
            - file:write
      summary: Reapply filters to the presentation
      tags:
        - Presentations
  /presentations/{presentationId}/links/publication:
    post:
      description: |
        Publishes the links in a presentation - either all (as document owner) or only one's own. Content at the latest presentation revision will be used for publish.
        The response also includes a `Location` header, which indicates where to poll for operation results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: presentationLinksPublication
      security:
        - oauth:
            - file:write
      summary: Initiate publication of links in a presentation
      tags:
        - Presentations
  /presentations/{presentationId}/milestones:
    get:
      description: Returns [MilestoneListResult](ref:milestones#milestonelistresult).
      operationId: getPresentationMilestones
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of milestones for a presentation
      tags:
        - Presentations
  /presentations/{presentationId}/slideLayouts:
    get:
      description: Returns a list of slide layouts.
      operationId: getSlideLayouts
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of slide layouts
      tags:
        - Presentations
  /presentations/{presentationId}/slideLayouts/{slideLayoutId}:
    get:
      description: |
        Retrieves a slide layout given its ID.
      operationId: getSlideLayoutById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single slide layout
      tags:
        - Presentations
    patch:
      description: |
        Updates one or more properties of a single slide layout.

        This is a long running operation. Responses include a `Location` header,
        which indicates where to poll for results. For more details on long-running
        job polling, see [Operations endpoint](ref:getoperationbyid).

        ### Options

        | Path            | PATCH Operations Supported |
        |-----------------|----------------------------|
        | `/name`         | `replace`                  |
        | `/index`        | `replace`                  |
        | `/lock`         | `replace`                  |
      operationId: partiallyUpdateSlideLayoutById
      security:
        - oauth:
            - file:write
      summary: Partially update a single slide layout
      tags:
        - Presentations
  /presentations/{presentationId}/slides:
    get:
      description: Returns a list of slides.
      operationId: getSlides
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of slides
      tags:
        - Presentations
  /presentations/{presentationId}/slides/{slideId}:
    get:
      description: |
        Retrieves a slide given its ID.
      operationId: getSlideById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single slide
      tags:
        - Presentations
    patch:
      description: |
        Updates one or more properties of a single slide.

        This is a long running operation. Responses include a `Location` header,
        which indicates where to poll for results. For more details on long-running
        job polling, see [Operations endpoint](ref:getoperationbyid).

        ### Options

        | Path                              | PATCH Operations Supported         |
        |-----------------------------------|------------------------------------|
        | `/name`                           | `replace`                          |
        | `/index`                          | `replace`                          |
        | `/parent`                         | `replace`                          |
        | `/customFields/<custom field id>` | `add`, `remove`, `replace`, `test` |
        | `/lock`                           | `replace`                          |

        ### Examples

        #### Update the name of a slide

        ```json
        [
          {
            "op": "replace",
            "path": "/name",
            "value": "Risk Factor"
          }
        ]
        ```

        #### Update the parent of a slide (preserving its index)

        ```json
        [
          {
            "op": "replace",
            "path": "/parent",
            "value": {
              "id": "b9b3ddb587744a27aafda3c9865f1f0a_1"
            }
          }
        ]
        ```

        #### Update the parent of a slide (making it the first child)

        ```json
        [
          {
            "op": "replace",
            "path": "/parent",
            "value": {
              "id": "b9b3ddb587744a27aafda3c9865f1f0a_1"
            }
          },
          {
            "op": "replace",
            "path": "/index",
            "value": 0
          }
        ]
        ```

        #### Add a custom field value

        ```json
        [
          {
            "op": "add",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva"
          }
        ]
        ```

        #### Remove a custom field value

        ```json
        [
          {
            "op": "remove",
            "path": "/customFields/com.workiva.gsr.legal_entity"
          }
        ]
        ```

        #### Replace a custom field value

        ```json
        [
          {
            "op": "replace",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva, Inc."
          }
        ]
        ```
      operationId: partiallyUpdateSlideById
      security:
        - oauth:
            - file:write
      summary: Partially update a single slide
      tags:
        - Presentations
  /spreadsheets:
    get:
      description: |
        Returns a paginated list of [spreadsheets](ref:spreadsheets#spreadsheet).
      operationId: getSpreadsheets
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of spreadsheets
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}:
    get:
      description: |
        Retrieves a [spreadsheet](ref:spreadsheets#spreadsheet) given its ID.
      operationId: getSpreadsheetById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single spreadsheet
      tags:
        - Spreadsheets
    patch:
      description: |
        Updates the properties of a [spreadsheet](ref:spreadsheets#spreadsheet).

        This is a long running operation. Responses include a `Location` header,
        which indicates where to poll for results. For more details on long-running job polling,
        see [Operations endpoint](ref:getoperationbyid).

        ### Options
        | Path                              | PATCH Operations Supported         |
        |-----------------------------------|------------------------------------|
        | `/customFields/<custom field id>` | `add`, `remove`, `replace`, `test` |
        | `/customFieldGroups`              | `add`, `remove`, `replace`, `test` |
        | `/sheetCustomFieldGroups`         | `add`, `remove`, `replace`, `test` |
        | `/lock`                           | `replace`                          |

        ### Examples

        #### Add a custom field value

        ```json
        [
          {
            "op": "add",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva"
          }
        ]
        ```

        #### Remove a custom field value

        ```json
        [
          {
            "op": "remove",
            "path": "/customFields/com.workiva.gsr.legal_entity"
          }
        ]
        ```

        #### Replace a custom field value

        ```json
        [
          {
            "op": "replace",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva, Inc."
          }
        ]
        ```

        #### Verifying customFieldGroup is empty before replacing the list

        ```json
        [
          {
            "op": "test",
            "path": "/customFieldGroups",
            "value": []
          },
          {
            "op": "replace",
            "path": "/customFieldGroups",
            "value": ["gsr.reporting"]
          }
        ]
        ```

        #### Adding a customFieldGroup to the end of a list

        ```json
        [
          {
            "op": "add",
            "path": "/customFieldGroups/-",
            "value": "gsr.reporting"
          }
        ]
        ```
      operationId: partiallyUpdateSpreadsheetById
      security:
        - oauth:
            - file:write
      summary: Partially update a single spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/datasets:
    get:
      description: Returns a list of [datasets](ref:spreadsheets#dataset). <br /><br /> Use this endpoint to identify any datasets that exist within a given [spreadsheet](ref:spreadsheets#spreadsheet), up to one per [sheet](ref:spreadsheets#sheet).
      operationId: getDatasets
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of datasets
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/datasets/bulkUpsert:
    post:
      description: Asynchronously upserts an array of [datasets](ref:spreadsheets#dataset) to a [spreadsheet](ref:spreadsheets#spreadsheet), given their properties. Each [sheet](ref:spreadsheets#sheet) can have only one dataset, and its range will always start with `A1`. <br /><br /> Bulk upsertion creates or updates datasets in sheets and performs any calculations after it completes. When complete, the dataset's range is locked through both the UI and endpoints that write values to a sheet. To [...]
      operationId: upsertDatasets
      security:
        - oauth:
            - file:write
      summary: Bulk upsert of datasets
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/export:
    post:
      description: |
        Asynchronously exports a [spreadsheet](ref:spreadsheets#spreadsheet) as .XLSX, .PDF, or .CSV.

        Responses include a `Location` header, which indicates where to poll for export results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the export completes, its status will be `completed`, and the response body includes a `resourceURL`. To download the exported file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the export request. For more details, see [Authentication documentation](ref:authe[...]

        Note: To export to .PDF, the spreadsheet can have no more than 250,000 cells.
      operationId: spreadsheetExport
      security:
        - oauth:
            - file:read
      summary: Initiate a spreadsheet export
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/filters/reapplication:
    post:
      description: |
        Performs a [`SpreadsheetFiltersReapplication`](ref:content#spreadsheetfiltersreapplication) on the specified spreadsheet.
        This endpoint is used to refresh the spreadsheet's filters based on the latest state or configuration changes.
        The filters are reapplied in the context of the spreadsheet's current data state.

        This is a long-running operation. Responses include a `Location` header, which indicates where to poll for results.
        For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: spreadsheetFiltersReapplication
      security:
        - oauth:
            - file:write
      summary: Reapply filters to the spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/links/publication:
    post:
      description: |
        Publishes the links in a spreadsheet - either all (as document owner) or only one's own. Content at the latest spreadsheet revision will be used for publish.
        The response also includes a `Location` header, which indicates where to poll for operation results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: spreadsheetLinksPublication
      security:
        - oauth:
            - file:write
      summary: Initiate publication of links in a spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/milestones:
    get:
      description: Returns [MilestoneListResult](ref:milestones#milestonelistresult).
      operationId: getSpreadsheetMilestones
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of milestones for a spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/permissions:
    get:
      description: |
        Retrieves a paginated list of permissions for a given spreadsheet
      operationId: getSpreadsheetPermissions
      security:
        - oauth:
            - file:read
        - contextless-oauth:
            - file:read
      summary: Retrieve permissions for a spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/permissions/modification:
    post:
      description: |
        Assign and/or revoke permissions on a spreadsheet. If any modification in a request fails, all modifications on that request fail. <br /><br /> _To modify an existing permission, the existing permission must first be  explicitly revoked. Then, the new permission needs to be assigned. This  can be done in a single request by sending `toAssign` and `toRevoke` in  the request body._
      operationId: spreadsheetPermissionsModification
      security:
        - oauth:
            - file:write
        - contextless-oauth:
            - file:write
      summary: Modify permissions on a spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets:
    get:
      description: Returns a list of [sheets](ref:spreadsheets#sheet).
      operationId: getSheets
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of sheets
      tags:
        - Spreadsheets
    post:
      description: |
        Creates a new [sheet](ref:spreadsheets#sheet) in a [spreadsheet](ref:spreadsheets#spreadsheet), given its properties. If the sheet name provided isn't unique, a number is appended to make it unique. By default, creates a top-level sheet in the top-most position.
      operationId: createSheet
      security:
        - oauth:
            - file:write
      summary: Create a new sheet in a spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets/{sheetId}:
    delete:
      description: |
        Deletes a [sheet](ref:spreadsheets#sheet) given its ID.
      operationId: deleteSheetById
      security:
        - oauth:
            - file:write
      summary: Delete a single sheet
      tags:
        - Spreadsheets
    get:
      description: |
        Retrieves a [sheet](ref:spreadsheets#sheet) given its ID.
      operationId: getSheetById
      security:
        - oauth:
            - file:read
      summary: Retrieve a single sheet
      tags:
        - Spreadsheets
    patch:
      description: |
        Updates the properties of a [sheet](ref:spreadsheets#sheet).

        This is a long running operation. Responses include a `Location` header,
        which indicates where to poll for results. For more details on long-running job polling,
        see [Operations endpoint](ref:getoperationbyid).

        ### Options
        | Path                              | PATCH Operations Supported         |
        |-----------------------------------|------------------------------------|
        | `/name`                           | `replace`                          |
        | `/index`                          | `replace`                          |
        | `/parent`                         | `replace`                          |
        | `/customFields/<custom field id>` | `add`, `remove`, `replace`, `test` |
        | `/lock`                           | `replace`                          |

        ### Examples

        #### Lock an unlocked sheet

        ```json
        [
          {
            "op": "replace",
            "path": "/lock",
            "value": "lock"
          }
        ]
        ```

        #### Unlock a locked sheet

        ```json
        [
          {
            "op": "replace",
            "path": "/lock",
            "value": null
          }
        ]
        ```

        #### Update the name of a sheet

        ```json
        [
          {
            "op": "replace",
            "path": "/name",
            "value": "Q1 Draft"
          }
        ]
        ```

        #### Update the parent of a sheet (preserving its index)

        ```json
        [
          {
            "op": "replace",
            "path": "/parent",
            "value": {
              "id": "242a56d3cc0742c8abad0820bd318b23"
            }
          }
        ]
        ```

        #### Update the parent of a sheet (making it the first child)

        ```json
        [
          {
            "op": "replace",
            "path": "/parent",
            "value": {
              "id": "242a56d3cc0742c8abad0820bd318b23"
            }
          },
          {
            "op": "replace",
            "path": "/index",
            "value": 0
          }
        ]
        ```

        #### Add a custom field value

        ```json
        [
          {
            "op": "add",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva"
          }
        ]
        ```

        #### Remove a custom field value

        ```json
        [
          {
            "op": "remove",
            "path": "/customFields/com.workiva.gsr.legal_entity"
          }
        ]
        ```

        #### Replace a custom field value

        ```json
        [
          {
            "op": "replace",
            "path": "/customFields/com.workiva.gsr.legal_entity",
            "value": "Workiva, Inc."
          }
        ]
        ```
      operationId: partiallyUpdateSheetById
      security:
        - oauth:
            - file:write
      summary: Partially update a single sheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets/{sheetId}/copy:
    post:
      description: |-
        Asynchronously copies a [sheet](ref:spreadsheets#sheet) given details about the copy's destination within the same or another spreadsheet. Options are specified using a [SheetCopy](ref:spreadsheets#sheetcopy) object.

        This endpoint copies a sheet's content, but does not copy labels, comments, or tasks. It will copy over most formatting, however it does not copy user-defined style guides across spreadsheets. So if the source sheet has  formatting that depends on a user-defined style guide, that formatting will be lost when copying to a new spreadsheet.

        Unless otherwise specified, the copy appears at the top level of its  destination spreadsheet, with an index of 0, and with the same name as the original sheet.
      operationId: copySheet
      security:
        - oauth:
            - file:write
      summary: Copy sheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets/{sheetId}/dataset:
    delete:
      description: Deletes the [dataset](ref:spreadsheets#dataset) for the specified [sheet](ref:spreadsheets#sheet). <br /><br /> When you delete a dataset, you can select whether to leave its associated values in place. To delete its values, pass `true` for query parameter `$deletevalues` (default is `false`).
      operationId: deleteDatasetBySheetId
      security:
        - oauth:
            - file:write
      summary: Delete a single dataset
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets/{sheetId}/permissions:
    get:
      description: |
        Retrieves a paginated list of permissions for the given sheet in a spreadsheet
      operationId: getSheetPermissions
      security:
        - oauth:
            - file:read
        - contextless-oauth:
            - file:read
      summary: Retrieve permissions for a sheet in a spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets/{sheetId}/permissions/modification:
    post:
      description: |
        Assign and/or revoke permissions on a sheet. If any modification in a request fails, all modifications on that request fail. <br /><br /> _To modify an existing permission, the existing permission must first be  explicitly revoked. Then, the new permission needs to be assigned. This  can be done in a single request by sending `toAssign` and `toRevoke` in  the request body._
      operationId: sheetPermissionsModification
      security:
        - oauth:
            - file:write
        - contextless-oauth:
            - file:write
      summary: Modify permissions on a given sheet of a spreadsheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets/{sheetId}/sheetdata:
    get:
      description: |-
        Retrieve data from a range in a sheet. Includes the value & formatting of cells, visibility of columns and cells, merged ranges, etc.
        Limit the results to particular fields by providing a comma-separated list of paths, rooted at the `data` object.
        Example: $fields=cells.calculatedValue,cells.formats.valueFormat <br /><br /> Note: This endpoint is rate-limited. You may experience rates as low as 600 requests per minute.  This rate is shared across your workspace. When you encounter a 429, examine the `Retry-After`  header and retry after that many seconds.
      operationId: getSheetData
      security:
        - oauth:
            - file:read
      summary: Retrieve data from a sheet
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets/{sheetId}/update:
    post:
      description: 'Asynchronously submits a [SheetUpdate](ref:spreadsheets#sheetupdate) to a [sheet](ref:spreadsheets#sheet). Each [SheetUpdate](ref:spreadsheets#sheetupdate) can have only one update field set per request. <br /><br /> Note: This endpoint is rate-limited. You may experience rates as low as 60 requests per minute.  This rate is shared across your workspace. When you encounter a 429, examine the `Retry-After`  header and retry after that many seconds.'
      operationId: updateSheet
      security:
        - oauth:
            - file:write
      summary: Update sheet content
      tags:
        - Spreadsheets
  /spreadsheets/{spreadsheetId}/sheets/{sheetId}/values/{range}:
    get:
      description: |-
        Returns the paginated values for a specified range.
        When you retrieve values from a range, Ones scale is used regardless of the cell's scale formatting.
      operationId: getValuesByRange
      security:
        - oauth:
            - file:read
      summary: Retrieve a list of range values
      tags:
        - Spreadsheets
    put:
      description: |-
        Overwrites all values in a range with new values. The provided range must not exceed the specified range. If the provided range of values is *smaller* than the specified range, it clears all cells in the range **and** those not covered by the range values. Rows of values in the provided range must be of equal length. An empty range of values is valid and may be used to clear a range.
        To indicate that a cell's value shouldn't be replaced, use the special cell value `null`.
        When you add a value to a cell, it uses Ones scale regardless of the cell's scale formatting.
      operationId: updateValuesByRange
      security:
        - oauth:
            - file:write
      summary: Update values in a range
      tags:
        - Spreadsheets
  /tasks:
    get:
      description: |
        > Returns a paginated list of [tasks](ref:tasks#task). Currently this endpoint returns general tasks
        (such as those created as part of editing documents, sheets, and presentations) and tasks that have been associated  with a Sustainability Program.
        It does not return tasks created as part of a process.
      operationId: getTasks
      security:
        - oauth:
            - task:read
      summary: Retrieve a list of tasks
      tags:
        - Tasks
    post:
      description: |
        Creates a new [task](ref:tasks#task) given its properties.
      operationId: createTask
      security:
        - oauth:
            - task:write
      summary: Create a new task
      tags:
        - Tasks
  /tasks/{taskId}:
    delete:
      description: |
        Deletes a [task](ref:tasks#task) given its ID
      operationId: deleteTaskById
      security:
        - oauth:
            - task:write
      summary: Delete a single task
      tags:
        - Tasks
    get:
      description: |
        Retrieves a [task](ref:tasks#task) given its ID
      operationId: getTaskById
      security:
        - oauth:
            - task:read
      summary: Retrieve a single task
      tags:
        - Tasks
    patch:
      description: |
        Partially updates the properties of a [task](ref:tasks#task).
        Please note: Tasks are automatically restarted when the following properties are updated:
        - `assignees`
        - `approvalSteps`: If any `participants` who have already approved are updated, the task will be restarted.
        - `location`
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/approvalSteps`|`replace`|
        |`/assignees`|`replace`|
        |`/description`|`replace`|
        |`/dueDate`|`replace`|
        |`/location`|`replace`|
        |`/owner`|`replace`|
        |`/title`|`replace`|
      operationId: partiallyUpdateTaskById
      security:
        - oauth:
            - task:write
      summary: Partially update a single task
      tags:
        - Tasks
  /tasks/{taskId}/actionSubmission:
    post:
      operationId: submitTaskAction
      summary: Initiate a task action submission
      description: |
        This endpoint enables submitting actions on a [task](ref:tasks#task). For tasks with multiple approval steps, it's the only way to advance a task through the approval process.
      tags:
        - Tasks
      security:
        - oauth:
            - task:write
  /testForms:
    get:
      description: |
        Retrieves a list of [test forms](ref:testforms#testform).
      operationId: getTestForms
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of test forms
      tags:
        - Test Forms
  /testForms/{testFormId}:
    get:
      description: |
        Retrieves a [test form](ref:testforms#testform) given its ID.
      operationId: getTestFormById
      security:
        - oauth:
            - graph:read
      summary: Retrieve a single test form
      tags:
        - Test Forms
  /testForms/{testFormId}/export:
    post:
      description: |
        Asynchronously exports a [test form](ref:testforms#testform).

        Responses include a `Location` header, which indicates where to poll for export results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the export completes, its status will be `completed`, and the response body includes a `resourceURL`. To download the exported file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the export request. For more details, see [Authentication documentation](ref:authe[...]
      operationId: testFormExport
      security:
        - oauth:
            - graph:read
      summary: Initiate a test form export
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases:
    get:
      description: |
        Returns a list of [test phases](ref:testforms#testphase).
      operationId: getTestPhases
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of test phases
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}:
    get:
      description: |
        Retrieves a [test phase](ref:testforms#testphase) given its ID.
      operationId: getTestPhaseById
      security:
        - oauth:
            - graph:read
      summary: Retrive a single test phase
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/attachmentUpload:
    post:
      description: |-
        Starts the process to upload and attach a file to a [test phase](ref:testforms#testphase) using a [graph attachment upload](ref:testforms#graphattachmentupload) object. The response body will include an `uploadUrl`. To upload the file contents, perform a PUT on the `uploadUrl` with the same authentication credentials and flow as the attachmentUpload request. For more details, see [Authentication documentation](ref:authentication).

        The response also includes a `Location` header, which indicates where to poll for operation results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: testPhaseAttachmentUpload
      security:
        - oauth:
            - graph:write
      summary: Initiate a test phase attachment upload
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/attachments:
    get:
      description: |
        Returns a list of [attachments](ref:testforms#graphattachment) for a [test phase](ref:testforms#testphase).
      operationId: getTestPhaseAttachments
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of test phase attachments
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}:
    get:
      description: |
        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.
      operationId: getTestPhaseAttachmentById
      security:
        - oauth:
            - graph:read
      summary: Retrieve a single test phase attachment
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}/download:
    post:
      description: |
        Asynchronously downloads an attachment from a [test phase](ref:testforms#testphase).

        Responses include a `Location` header, which indicates where to poll for download results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the download is ready, its status will be `completed`, and the response body includes a `resourceURL`. To download the file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the download request. For more details, see [Authentication documentation](ref:authentic[...]
      operationId: testPhaseAttachmentDownloadById
      security:
        - oauth:
            - graph:read
      summary: Initiate a test phase attachment download
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}/export:
    post:
      description: |
        Asynchronously exports an attachment for a [test phase](ref:testforms#testphase) to .PDF.

        Responses include a `Location` header, which indicates where to poll for export results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the export completes, its status will be `completed`, and the response body includes a `resourceURL`. To download the exported file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the export request. For more details, see [Authentication documentation](ref:authe[...]
      operationId: testPhaseAttachmentExportById
      security:
        - oauth:
            - graph:read
      summary: Initiate a test phase attachment export
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices:
    get:
      description: |
        Returns a list of [matrices](ref:testforms#matrix).
      operationId: getMatrices
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of matrices
      tags:
        - Test Forms
    post:
      description: |
        Create a new empty [matrix](ref:testforms#matrix). The `id` field for the matrix and its columns should be left blank; this will be populated by the endpoint.
      operationId: createMatrix
      security:
        - oauth:
            - graph:write
      summary: Create a new matrix
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}:
    get:
      description: |
        Retrieves a [matrix](ref:testforms#matrix) given its ID.
      operationId: getMatrixById
      security:
        - oauth:
            - graph:read
      summary: Retrieve a single matrix
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachmentUpload:
    post:
      description: |
        Starts the process to upload and attach a file to a [matrix](ref:testforms#matrix) using a [graph attachment upload](ref:testforms#graphattachmentupload) object. The response body will include an `uploadUrl`. To upload the file contents, perform a PUT on the `uploadUrl` with the same authentication credentials and flow as the attachmentUpload request. For more details, see [Authentication documentation](ref:overview#authentication).

        The response also includes a `Location` header, which indicates where to poll for operation results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: matrixAttachmentUpload
      security:
        - oauth:
            - graph:write
      summary: Initiate a matrix attachment upload
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments:
    get:
      description: |
        Returns a list of [attachments](ref:testforms#graphattachment) for a matrix.
      operationId: getMatrixAttachments
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of matrix attachments
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}:
    get:
      description: |
        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.
      operationId: getMatrixAttachmentById
      security:
        - oauth:
            - graph:read
      summary: Retrieve a single matrix attachment
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}/download:
    post:
      description: |
        Asynchronously downloads an attachment from a [matrix](ref:testforms#matrix).

        Responses include a `Location` header, which indicates where to poll for download results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the download is ready, its status will be `completed`, and the response body includes a `resourceURL`. To download the file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the download request. For more details, see [Authentication documentation](ref:authentic[...]
      operationId: matrixAttachmentDownloadById
      security:
        - oauth:
            - graph:read
      summary: Initiate a matrix attachment download
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}/export:
    post:
      description: |
        Asynchronously exports an attachment for a [matrix](ref:testforms#matrix) to .PDF.

        Responses include a `Location` header, which indicates where to poll for export results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the export completes, its status will be `completed`, and the response body includes a `resourceURL`. To download the exported file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the export request. For more details, see [Authentication documentation](ref:authe[...]
      operationId: matrixAttachmentExportById
      security:
        - oauth:
            - graph:read
      summary: Initiate an export of a matrix attachment
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples:
    get:
      description: |
        Returns a list of [samples](ref:testforms#matrixsample).
      operationId: getSamples
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of samples
      tags:
        - Test Forms
    post:
      description: |
        Create a new [sample](ref:testforms#matrixsample) in a [matrix](ref:testforms#matrix). The new sample will be appended to the end of the matrix.
      operationId: createSample
      security:
        - oauth:
            - graph:write
      summary: Create a new sample
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/insertion:
    post:
      description: Inserts multiple [samples](ref:testforms#matrixsamples) into a [matrix](ref:testforms#matrix), and appends new samples to the end of the matrix. You can leave columns empty for later use. For new samples, provide no IDs; the endpoint generates them.
      operationId: sampleInsertion
      security:
        - oauth:
            - graph:write
      summary: Insert samples
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/update:
    post:
      description: Updates multiple [samples](ref:testforms#matrixsamples), with the requestBody of each specifying columns to update by their IDs. Columns not included in the request remain as-is.
      operationId: sampleUpdate
      security:
        - oauth:
            - graph:write
      summary: Update samples
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}:
    get:
      description: |
        Retrieves a [sample](ref:testforms#matrixsample) given its ID.
      operationId: getSampleById
      security:
        - oauth:
            - graph:read
      summary: Retrieve a single sample
      tags:
        - Test Forms
    patch:
      description: |
        Partially updates the properties of a [sample](ref:testforms#matrixsample). Note: Cell values must always be strings, even if they represent a number.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/dataValues/<index>/value`|`replace`|
        |`/resultValues/<index>/value`|`replace`|
      operationId: partiallyUpdateSampleById
      security:
        - oauth:
            - graph:write
      summary: Partially update a single sample
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachmentUpload:
    post:
      description: |
        Starts the process to upload and attach a file to a [sample](ref:testforms#matrixsample) using a [graph attachment upload](ref:testforms#graphattachmentupload) object. The response body will include an `uploadUrl`. To upload the file contents, perform a PUT on the `uploadUrl` with the same authentication credentials and flow as the attachmentUpload request. For more details, see [Authentication documentation](ref:authentication).

        The response also includes a `Location` header, which indicates where to poll for operation results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid).
      operationId: sampleAttachmentUpload
      security:
        - oauth:
            - graph:write
      summary: Initiate an upload of a sample attachment
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments:
    get:
      description: |
        Returns a list of [attachments](ref:testforms#graphattachment) for a [sample](ref:testforms#matrixsample).
      operationId: getSampleAttachments
      security:
        - oauth:
            - graph:read
      summary: Retrieve a list of sample attachments
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}:
    get:
      description: |
        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.
      operationId: getSampleAttachmentById
      security:
        - oauth:
            - graph:read
      summary: Retrieve a single sample attachment
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}/download:
    post:
      description: |
        Asynchronously downloads an attachment from a [sample](ref:testforms#matrixsample).

        Responses include a `Location` header, which indicates where to poll for download results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the download is ready, its status will be `completed`, and the response body includes a `resourceURL`. To download the file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the download request. For more details, see [Authentication documentation](ref:authentic[...]
      operationId: sampleAttachmentDownloadById
      security:
        - oauth:
            - graph:read
      summary: Initiate a download of a sample attachment
      tags:
        - Test Forms
  /testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}/export:
    post:
      description: |
        Asynchronously exports an attachment for a [sample](ref:testforms#matrixsample) to .PDF.

        Responses include a `Location` header, which indicates where to poll for export results. For more details on long-running job polling, see [Operations endpoint](ref:getoperationbyid). When the export completes, its status will be `completed`, and the response body includes a `resourceURL`. To download the exported file, perform a GET on the `resourceURL` with the same authentication credentials and flow as the export request. For more details, see [Authentication documentation](ref:authe[...]
      operationId: sampleAttachmentExportById
      security:
        - oauth:
            - graph:read
      summary: Initiate an export of a sample attachment
      tags:
        - Test Forms
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /iam/v1/oauth2/token
          scopes:
            activity:read: Read Activity data.
            file:read: Read files.
            file:write: Write files.
            graph:read: Read Graph data.
            graph:write: Write Graph data.
            organization:read: Read Organization data.
            organization:write: Write Organization data.
    contextless-oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /iam/v1/oauth2/token
          scopes:
            file:read: Read files.
            file:write: Write files.
            organization:read: Read Organization data.
            organization:write: Write Organization data.
  parameters:
    ActivityId:
      description: The unique identifier of the activity
      in: path
      name: activityId
      required: true
      schema:
        type: string
    MaxPageSize:
      description: The maximum number of results to retrieve
      in: query
      name: $maxpagesize
      required: false
      schema:
        default: 1000
        maximum: 1000
        minimum: 1
        type: integer
    Next:
      description: Pagination cursor for next set of results.
      in: query
      name: $next
      required: false
      schema:
        type: string
    OrderBy:
      description: One or more comma-separated expressions to indicate the order in which to sort the results.
      in: query
      name: $orderBy
      required: false
      schema:
        type: string
    ActivityActionId:
      description: The unique identifier of the activity action
      in: path
      name: activityActionId
      required: true
      schema:
        type: string
    AnchorId:
      description: The unique identifier of the anchor
      in: path
      name: anchorId
      required: true
      schema:
        type: string
    Revision:
      description: Returns resources at a specific revision
      in: query
      name: $revision
      required: false
      schema:
        type: string
    DestinationLinkId:
      description: The unique identifier of the destination link
      in: path
      name: destinationLinkId
      required: true
      schema:
        type: string
    DrawingId:
      description: The unique identifier of a drawing
      in: path
      name: drawingId
      required: true
      schema:
        type: string
    ImageId:
      description: The unique identifier of the image
      in: path
      name: imageId
      required: true
      schema:
        type: string
    RichTextId:
      description: The unique identifier of the rich text content
      in: path
      name: richTextId
      required: true
      schema:
        type: string
    StyleGuideId:
      description: The unique identifier of the style guide
      in: path
      name: styleGuideId
      required: true
      schema:
        type: string
    TableId:
      description: The unique identifier for the table
      in: path
      name: tableId
      required: true
      schema:
        type: string
    MaxCellsPerPage:
      description: The maximum number of cells to retrieve. The default is 50000. The maximum allowed value is 50000.
      in: query
      name: $maxcellsperpage
      required: false
      schema:
        default: 50000
        maximum: 50000
        minimum: 1
        type: integer
    StartRow:
      description: The inclusive start row of the range of cells to retrieve. If this parameter is omitted, then the range will be unbounded in this direction.
      in: query
      name: startRow
      required: false
      schema:
        type: integer
    StopRow:
      description: The inclusive stop row of the range of cells to retrieve. If this parameter is omitted, then the range will be unbounded in this direction.
      in: query
      name: stopRow
      required: false
      schema:
        type: integer
    StartColumn:
      description: The inclusive start column of the range of cells to retrieve. If this parameter is omitted, then the range will be unbounded in this direction.
      in: query
      name: startColumn
      required: false
      schema:
        type: integer
    StopColumn:
      description: The inclusive stop column of the range of cells to retrieve. If this parameter is omitted, then the range will be unbounded in this direction.
      in: query
      name: stopColumn
      required: false
      schema:
        type: integer
    RangeLinkId:
      description: The unique identifier of a range link.
      in: path
      name: rangeLinkId
      required: true
      schema:
        $ref: '#/components/schemas/RangeLinkId'
    MilestoneId:
      description: The unique identifier of a milestone.
      in: path
      name: milestoneId
      required: true
      schema:
        $ref: '#/components/schemas/MilestoneId'
    Filter:
      description: The properties to filter the results by.
      in: query
      name: $filter
      required: false
      schema:
        type: string
    ProgramId:
      description: The unique identifier of the program
      in: path
      name: programId
      required: true
      schema:
        type: string
    DimensionId:
      description: The unique identifier of the dimension
      in: path
      name: dimensionId
      required: true
      schema:
        type: string
    MetricId:
      description: The unique identifier of the metric
      in: path
      name: metricId
      required: true
      schema:
        type: string
    MetricValueId:
      description: The unique identifier of the value
      in: path
      name: metricValueId
      required: true
      schema:
        type: string
    TopicId:
      description: The unique identifier of the topic
      in: path
      name: topicId
      required: true
      schema:
        type: string
    Wk-Service-Provider:
      description: The unique identifier of the service provider
      in: header
      name: Wk-Service-Provider
      required: true
      schema:
        type: string
    OrganizationId:
      description: The unique identifier of the organization
      in: path
      name: organizationId
      required: true
      schema:
        format: uuid
        type: string
    UserId:
      description: The unique identifier of the user
      in: path
      name: userId
      required: true
      schema:
        type: string
    Expand:
      description: Returns related resources inline with the main resource
      in: query
      name: $expand
      required: false
      schema:
        type: string
    WorkspaceId:
      description: The unique identifier of the workspace
      in: path
      name: workspaceId
      required: true
      schema:
        type: string
    GroupId:
      description: The unique identifier of the group
      in: path
      name: groupId
      required: true
      schema:
        type: string
    WorkspaceMembershipId:
      description: The unique identifier of the workspace membership
      in: path
      name: workspaceMembershipId
      required: true
      schema:
        type: string
    SolutionId:
      description: The unique identifier of the solution
      in: path
      name: solutionId
      required: true
      schema:
        type: string
    IamCookie:
      description: Cookie header for IAM requests.
      in: header
      name: Cookie
      required: false
      schema:
        type: string
    DocumentId:
      description: The unique identifier of the document
      in: path
      name: documentId
      required: true
      schema:
        type: string
    SectionId:
      description: The unique identifier of the section
      in: path
      name: sectionId
      required: true
      schema:
        type: string
    FileId:
      description: The unique identifier of the file
      in: path
      name: fileId
      required: true
      schema:
        type: string
    RecordId:
      description: The unique identifier of the record
      in: path
      name: recordId
      required: true
      schema:
        type: string
    ReportId:
      description: The unique identifier of the report
      in: path
      name: reportId
      required: true
      schema:
        type: string
    TypeId:
      description: The unique identifier of the type
      in: path
      name: typeId
      required: true
      schema:
        type: string
    OperationId:
      description: The unique identifier of the operation
      in: path
      name: operationId
      required: true
      schema:
        type: string
    PermissionId:
      description: The unique identifier of the permission
      in: path
      name: permissionId
      required: true
      schema:
        type: string
    PresentationId:
      description: The unique identifier of the presentation
      in: path
      name: presentationId
      required: true
      schema:
        type: string
    SlideLayoutId:
      description: The unique identifier of the slide layout
      in: path
      name: slideLayoutId
      required: true
      schema:
        type: string
    SlideId:
      description: The unique identifier of the slide
      in: path
      name: slideId
      required: true
      schema:
        type: string
    SpreadsheetId:
      description: The unique identifier of the spreadsheet
      in: path
      name: spreadsheetId
      required: true
      schema:
        type: string
    SheetId:
      description: The unique identifier of the sheet
      in: path
      name: sheetId
      required: true
      schema:
        type: string
    DatasetDeleteValues:
      description: Indicates whether values should be deleted along with the dataset
      in: query
      name: $deletevalues
      required: false
      schema:
        default: false
        type: boolean
    CellRange:
      description: |
        The range to query. If not provided, the entire sheet will be queried.
        A1 style representation of a cell or range. A range my be unbounded in any/all directions by leaving off the corresponding column or row.
      in: query
      name: $cellrange
      required: false
      schema:
        type: string
    Fields:
      description: A restricted set of fields for a given resource.
      in: query
      name: $fields
      required: false
      schema:
        type: string
    Range:
      description: The range of values, in A1-style notation
      in: path
      name: range
      required: true
      schema:
        type: string
        nullable: true
    ValueStyle:
      description: Whether to retrieve `raw` or `calculated` cell values. For example, if a cell's value is `=1+1`, `raw` retrieves the value `=1+1`, while `calculated` retrieves `2`.
      in: query
      name: $valuestyle
      required: false
      schema:
        default: calculated
        enum:
          - raw
          - calculated
        type: string
    TaskId:
      description: The unique identifier of the task
      in: path
      name: taskId
      required: true
      schema:
        type: string
    TestFormId:
      description: The unique identifier of the test form
      in: path
      name: testFormId
      required: true
      schema:
        type: string
    TestPhaseId:
      description: The unique identifier of the test phase
      in: path
      name: testPhaseId
      required: true
      schema:
        type: string
    AttachmentId:
      description: The unique identifier of the attachment
      in: path
      name: attachmentId
      required: true
      schema:
        type: string
    MatrixId:
      description: The unique identifier of the matrix
      in: path
      name: matrixId
      required: true
      schema:
        type: string
    SampleId:
      description: The unique identifier of the sample
      in: path
      name: sampleId
      required: true
      schema:
        type: string