"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata


CHAINS_GET_ENVIRONMENT_OP_SERVERS = [
    # US
    "https://h.app.wdesk.com/s/wdata/oc/api",
    # EU
    "https://h.eu.wdesk.com/s/wdata/oc/api",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/oc/api",
]


class ChainsGetEnvironmentRequestTypedDict(TypedDict):
    workspace_id: str
    r"""The ID of the Workspace."""
    environment_id: str
    r"""The ID of the Environment."""


class ChainsGetEnvironmentRequest(BaseModel):
    workspace_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the Workspace."""

    environment_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the Environment."""
