"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chainrunnoderesult import ChainRunNodeResult, ChainRunNodeResultTypedDict
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class NodeType(str, Enum):
    COMMAND = "command"
    EVENT = "event"


class ChainRunNodeState(str, Enum):
    SLEEPING = "sleeping"
    PAUSED = "paused"
    SKIPPED = "skipped"
    ERRORED = "errored"
    WARNED = "warned"
    SUCCEEDED = "succeeded"


class ChainRunNodeTypedDict(TypedDict):
    end_at: NotRequired[str]
    id: NotRequired[str]
    r"""The unique identifier of a resource (can be a GUID)."""
    iterable: NotRequired[bool]
    name: NotRequired[str]
    node_id: NotRequired[str]
    r"""The unique identifier of a resource (can be a GUID)."""
    node_type: NotRequired[NodeType]
    results: NotRequired[List[ChainRunNodeResultTypedDict]]
    start_at: NotRequired[str]
    state: NotRequired[ChainRunNodeState]


class ChainRunNode(BaseModel):
    end_at: Annotated[Optional[str], pydantic.Field(alias="endAt")] = None

    id: Optional[str] = None
    r"""The unique identifier of a resource (can be a GUID)."""

    iterable: Optional[bool] = None

    name: Optional[str] = None

    node_id: Annotated[Optional[str], pydantic.Field(alias="nodeId")] = None
    r"""The unique identifier of a resource (can be a GUID)."""

    node_type: Annotated[Optional[NodeType], pydantic.Field(alias="nodeType")] = None

    results: Optional[List[ChainRunNodeResult]] = None

    start_at: Annotated[Optional[str], pydantic.Field(alias="startAt")] = None

    state: Optional[ChainRunNodeState] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "endAt",
                "id",
                "iterable",
                "name",
                "nodeId",
                "nodeType",
                "results",
                "startAt",
                "state",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
