"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class OutputVariablesTypedDict(TypedDict):
    data: NotRequired[str]
    path: NotRequired[str]


class OutputVariables(BaseModel):
    data: Optional[str] = None

    path: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "path"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ChainRunNodeResultState(str, Enum):
    ACTIVE = "active"
    ERRORED = "errored"
    SKIPPED = "skipped"
    WARNED = "warned"
    SUCCEEDED = "succeeded"
    STOPPED = "stopped"


class ChainRunNodeResultTypedDict(TypedDict):
    id: NotRequired[str]
    r"""The unique identifier of a resource (can be a GUID)."""
    iterator_value: NotRequired[str]
    output_log_url: NotRequired[str]
    output_variables: NotRequired[OutputVariablesTypedDict]
    state: NotRequired[ChainRunNodeResultState]


class ChainRunNodeResult(BaseModel):
    id: Optional[str] = None
    r"""The unique identifier of a resource (can be a GUID)."""

    iterator_value: Annotated[Optional[str], pydantic.Field(alias="iteratorValue")] = (
        None
    )

    output_log_url: Annotated[Optional[str], pydantic.Field(alias="outputLogUrl")] = (
        None
    )

    output_variables: Annotated[
        Optional[OutputVariables], pydantic.Field(alias="outputVariables")
    ] = None

    state: Optional[ChainRunNodeResultState] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["id", "iteratorValue", "outputLogUrl", "outputVariables", "state"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
