"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .documentfiltersreapplication import (
    DocumentFiltersReapplication,
    DocumentFiltersReapplicationTypedDict,
)
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class DocumentFiltersReapplicationRequestTypedDict(TypedDict):
    document_filters_reapplication: DocumentFiltersReapplicationTypedDict
    r"""The filter reapplication request to apply"""
    document_id: str
    r"""The unique identifier of the document"""


class DocumentFiltersReapplicationRequest(BaseModel):
    document_filters_reapplication: Annotated[
        DocumentFiltersReapplication,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The filter reapplication request to apply"""

    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the document"""


class DocumentFiltersReapplicationResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class DocumentFiltersReapplicationResponse(BaseModel):
    headers: Dict[str, List[str]]
