"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from workiva import utils


class DrawingRichTextSelectionAnchorAttachmentPointType(
    str, Enum, metaclass=utils.OpenEnumMeta
):
    r"""The type of attachment point."""

    COMMENT = "comment"
    SOURCE_LINK = "sourceLink"
