"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from workiva import utils


class ExtensionType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates the type of the anchor extension."""

    COMMENT = "comment"
    DESTINATION_LINK = "destinationLink"
