"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from workiva.types import BaseModel


class FolderableDtoInputTypedDict(TypedDict):
    id: str
    r"""The UUID unique identifier for the entity."""
    type: int
    r"""The numerical identifier for the entity's type:  Query=100, Table=200, Pivot View=500, Folder=600, Shared Table=700"""


class FolderableDtoInput(BaseModel):
    id: str
    r"""The UUID unique identifier for the entity."""

    type: int
    r"""The numerical identifier for the entity's type:  Query=100, Table=200, Pivot View=500, Folder=600, Shared Table=700"""
