"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata


class GetActivityActionByIDRequestTypedDict(TypedDict):
    activity_action_id: str
    r"""The unique identifier of the activity action"""


class GetActivityActionByIDRequest(BaseModel):
    activity_action_id: Annotated[
        str,
        pydantic.Field(alias="activityActionId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the activity action"""
