"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .milestonelistresult import MilestoneListResult, MilestoneListResultTypedDict
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata


class GetDocumentMilestonesRequestTypedDict(TypedDict):
    document_id: str
    r"""The unique identifier of the document"""
    dollar_next: NotRequired[str]
    r"""Pagination cursor for next set of results."""


class GetDocumentMilestonesRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the document"""

    dollar_next: Annotated[
        Optional[str],
        pydantic.Field(alias="$next"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pagination cursor for next set of results."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["$next"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetDocumentMilestonesResponseTypedDict(TypedDict):
    result: MilestoneListResultTypedDict


class GetDocumentMilestonesResponse(BaseModel):
    next: Union[
        Callable[[], Optional[GetDocumentMilestonesResponse]],
        Callable[[], Awaitable[Optional[GetDocumentMilestonesResponse]]],
    ]

    result: MilestoneListResult
