"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata


class GetDimensionByIDRequestTypedDict(TypedDict):
    dimension_id: str
    r"""The unique identifier of the dimension"""
    program_id: str
    r"""The unique identifier of the program"""


class GetDimensionByIDRequest(BaseModel):
    dimension_id: Annotated[
        str,
        pydantic.Field(alias="dimensionId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the dimension"""

    program_id: Annotated[
        str,
        pydantic.Field(alias="programId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the program"""
