"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .activitieslistresult import ActivitiesListResult, ActivitiesListResultTypedDict
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata


class GetOrganizationWorkspaceActivitiesRequestTypedDict(TypedDict):
    organization_id: str
    r"""The unique identifier of the organization"""
    workspace_id: str
    r"""The unique identifier of the workspace"""
    dollar_filter: NotRequired[str]
    r"""The properties to filter the results by."""
    dollar_maxpagesize: NotRequired[int]
    r"""The maximum number of results to retrieve"""
    dollar_next: NotRequired[str]
    r"""Pagination cursor for next set of results."""
    dollar_order_by: NotRequired[str]
    r"""One or more comma-separated expressions to indicate the order in which to sort the results."""


class GetOrganizationWorkspaceActivitiesRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the organization"""

    workspace_id: Annotated[
        str,
        pydantic.Field(alias="workspaceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the workspace"""

    dollar_filter: Annotated[
        Optional[str],
        pydantic.Field(alias="$filter"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The properties to filter the results by."""

    dollar_maxpagesize: Annotated[
        Optional[int],
        pydantic.Field(alias="$maxpagesize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1000
    r"""The maximum number of results to retrieve"""

    dollar_next: Annotated[
        Optional[str],
        pydantic.Field(alias="$next"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pagination cursor for next set of results."""

    dollar_order_by: Annotated[
        Optional[str],
        pydantic.Field(alias="$orderBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""One or more comma-separated expressions to indicate the order in which to sort the results."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["$filter", "$maxpagesize", "$next", "$orderBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetOrganizationWorkspaceActivitiesResponseTypedDict(TypedDict):
    result: ActivitiesListResultTypedDict


class GetOrganizationWorkspaceActivitiesResponse(BaseModel):
    next: Union[
        Callable[[], Optional[GetOrganizationWorkspaceActivitiesResponse]],
        Callable[[], Awaitable[Optional[GetOrganizationWorkspaceActivitiesResponse]]],
    ]

    result: ActivitiesListResult
