"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .operation import Operation, OperationTypedDict
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata


class GetOperationByIDRequestTypedDict(TypedDict):
    operation_id: str
    r"""The unique identifier of the operation"""


class GetOperationByIDRequest(BaseModel):
    operation_id: Annotated[
        str,
        pydantic.Field(alias="operationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the operation"""


class GetOperationByIDResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: OperationTypedDict


class GetOperationByIDResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Operation
