"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .richtexteditlistresult import (
    RichTextEditListResult,
    RichTextEditListResultTypedDict,
)
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata


class GetRichTextBatchEditResultsRequestTypedDict(TypedDict):
    operation_id: str
    r"""The unique identifier of the operation"""
    maxpagesize: NotRequired[int]
    r"""The maximum number of results to retrieve"""
    next: NotRequired[str]
    r"""Pagination cursor for next set of results."""


class GetRichTextBatchEditResultsRequest(BaseModel):
    operation_id: Annotated[
        str,
        pydantic.Field(alias="operationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the operation"""

    maxpagesize: Annotated[
        Optional[int],
        pydantic.Field(alias="$maxpagesize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1000
    r"""The maximum number of results to retrieve"""

    next: Annotated[
        Optional[str],
        pydantic.Field(alias="$next"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pagination cursor for next set of results."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["maxpagesize", "next"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetRichTextBatchEditResultsResponseTypedDict(TypedDict):
    result: RichTextEditListResultTypedDict


class GetRichTextBatchEditResultsResponse(BaseModel):
    next: Union[
        Callable[[], Optional[GetRichTextBatchEditResultsResponse]],
        Callable[[], Awaitable[Optional[GetRichTextBatchEditResultsResponse]]],
    ]

    result: RichTextEditListResult
