"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata


class GetSectionByIDRequestTypedDict(TypedDict):
    document_id: str
    r"""The unique identifier of the document"""
    section_id: str
    r"""The unique identifier of the section"""
    dollar_expand: NotRequired[str]
    r"""Returns related resources inline with the main resource"""
    dollar_revision: NotRequired[str]
    r"""Returns resources at a specific revision"""


class GetSectionByIDRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the document"""

    section_id: Annotated[
        str,
        pydantic.Field(alias="sectionId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the section"""

    dollar_expand: Annotated[
        Optional[str],
        pydantic.Field(alias="$expand"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Returns related resources inline with the main resource"""

    dollar_revision: Annotated[
        Optional[str],
        pydantic.Field(alias="$revision"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Returns resources at a specific revision"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["$expand", "$revision"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
