"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dimensions import Dimensions, DimensionsTypedDict
from .imageref import ImageRef, ImageRefTypedDict
from .richtextformat import RichTextFormat, RichTextFormatTypedDict
from .styleref import StyleRef, StyleRefTypedDict
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ImageTextElementTypedDict(TypedDict):
    r"""A text element for image embedded content."""

    dimensions: DimensionsTypedDict
    r"""A dimension of a rectangle for properties of objects such as a shape, text box, table, chart, image, or page.

    """
    format_: NotRequired[Nullable[RichTextFormatTypedDict]]
    r"""The formatting options applied to rich text elements."""
    length: NotRequired[int]
    r"""The number of characters (32-bit unicode code point) for a text element or range of text in a selection. Most elements will have a length of 1, even if it is dynamic content which will be replaced by possibly multiple characters. The lengths are used when editing with offsets from an element. The sum of the lengths up to a specific element from another is the offset between those text elements.

    """
    offset: NotRequired[int]
    r"""The number of items to skip over in a collection before the items which will be returned or worked on. The items may be shapes, sections, elements, characters, slides, etc depending on which object or path the offset is being used on.

    """
    style: NotRequired[StyleRefTypedDict]
    r"""A reference to a style."""
    image: NotRequired[ImageRefTypedDict]
    r"""A reference to image content in a document, spreadsheet, or presentation"""


class ImageTextElement(BaseModel):
    r"""A text element for image embedded content."""

    dimensions: Dimensions
    r"""A dimension of a rectangle for properties of objects such as a shape, text box, table, chart, image, or page.

    """

    format_: Annotated[
        OptionalNullable[RichTextFormat], pydantic.Field(alias="format")
    ] = UNSET
    r"""The formatting options applied to rich text elements."""

    length: Optional[int] = 1
    r"""The number of characters (32-bit unicode code point) for a text element or range of text in a selection. Most elements will have a length of 1, even if it is dynamic content which will be replaced by possibly multiple characters. The lengths are used when editing with offsets from an element. The sum of the lengths up to a specific element from another is the offset between those text elements.

    """

    offset: Optional[int] = 0
    r"""The number of items to skip over in a collection before the items which will be returned or worked on. The items may be shapes, sections, elements, characters, slides, etc depending on which object or path the offset is being used on.

    """

    style: Optional[StyleRef] = None
    r"""A reference to a style."""

    image: Optional[ImageRef] = None
    r"""A reference to image content in a document, spreadsheet, or presentation"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["format", "length", "offset", "style", "image"])
        nullable_fields = set(["format"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
