"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imageuploadresponse import ImageUploadResponse, ImageUploadResponseTypedDict
from typing import Dict, List
from typing_extensions import TypedDict
from workiva.types import BaseModel


class ImageUploadResponse1TypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ImageUploadResponseTypedDict


class ImageUploadResponse1(BaseModel):
    headers: Dict[str, List[str]]

    result: ImageUploadResponse
