"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LineRelativeType(str, Enum):
    r"""The relative position type used for the head and tail of a line drawing element."""

    DESIGN_PAGE_RELATIVE = "designPageRelative"
    PARAGRAPH_RELATIVE = "paragraphRelative"
    SLIDE_RELATIVE = "slideRelative"
