"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LineCapSize(str, Enum):
    r"""The size of a cap at a line terminator."""

    SMALL = "small"
    MEDIUM = "medium"
    LARGE = "large"
