"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listsequencetype import ListSequenceType
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva import models
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ListProgressionStyleTypedDict(TypedDict):
    r"""The list sequence style of this list progression."""

    sequence_type: NotRequired[ListSequenceType]
    r"""The type of list sequence. If the list style is unordered, the sequence type of the first list progression must be unordered. If the list style is ordered, the sequence type of the first list progression may not be unordered.

    """
    unordered_glyph: NotRequired[Nullable[str]]
    r"""The custom glyph to use for unordered lists. If the sequenceType is not set to unordered, then this field is ignored.

    """


class ListProgressionStyle(BaseModel):
    r"""The list sequence style of this list progression."""

    sequence_type: Annotated[
        Optional[ListSequenceType], pydantic.Field(alias="sequenceType")
    ] = ListSequenceType.UNORDERED_SEQUENCE
    r"""The type of list sequence. If the list style is unordered, the sequence type of the first list progression must be unordered. If the list style is ordered, the sequence type of the first list progression may not be unordered.

    """

    unordered_glyph: Annotated[
        OptionalNullable[str], pydantic.Field(alias="unorderedGlyph")
    ] = UNSET
    r"""The custom glyph to use for unordered lists. If the sequenceType is not set to unordered, then this field is ignored.

    """

    @field_serializer("sequence_type")
    def serialize_sequence_type(self, value):
        if isinstance(value, str):
            try:
                return models.ListSequenceType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sequenceType", "unorderedGlyph"])
        nullable_fields = set(["unorderedGlyph"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
