"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LockedCellEditMode(str, Enum):
    r"""Whether or not an edit applied to locked cells is prevented. Validation will prevent an edit with a locked
    cell when set to `strict`. When set to `trim` the edit will succeed with the locked cells trimmed out.

    """

    STRICT = "strict"
    TRIM = "trim"
