"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .graphattachmentupload import GraphAttachmentUpload, GraphAttachmentUploadTypedDict
from .graphattachmentuploadresponse import (
    GraphAttachmentUploadResponse,
    GraphAttachmentUploadResponseTypedDict,
)
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class MatrixAttachmentUploadRequestTypedDict(TypedDict):
    graph_attachment_upload: GraphAttachmentUploadTypedDict
    r"""Details about the attachment upload"""
    matrix_id: str
    r"""The unique identifier of the matrix"""
    test_form_id: str
    r"""The unique identifier of the test form"""
    test_phase_id: str
    r"""The unique identifier of the test phase"""


class MatrixAttachmentUploadRequest(BaseModel):
    graph_attachment_upload: Annotated[
        GraphAttachmentUpload,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Details about the attachment upload"""

    matrix_id: Annotated[
        str,
        pydantic.Field(alias="matrixId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the matrix"""

    test_form_id: Annotated[
        str,
        pydantic.Field(alias="testFormId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the test form"""

    test_phase_id: Annotated[
        str,
        pydantic.Field(alias="testPhaseId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the test phase"""


class MatrixAttachmentUploadResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GraphAttachmentUploadResponseTypedDict


class MatrixAttachmentUploadResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GraphAttachmentUploadResponse
