"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class ParagraphSelectionTypedDict(TypedDict):
    r"""A selection of one or more paragraphs, starting from the start paragraph and ending with the stop paragraph. Both start and stop paragraph indexes are inclusive."""

    start: NotRequired[int]
    r"""The zero-based inclusive starting index of a paragraph."""
    stop: NotRequired[int]
    r"""The zero-based inclusive stopping index of a paragraph."""


class ParagraphSelection(BaseModel):
    r"""A selection of one or more paragraphs, starting from the start paragraph and ending with the stop paragraph. Both start and stop paragraph indexes are inclusive."""

    start: Optional[int] = None
    r"""The zero-based inclusive starting index of a paragraph."""

    stop: Optional[int] = None
    r"""The zero-based inclusive stopping index of a paragraph."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["start", "stop"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
