"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jsonpatchoperation import JSONPatchOperation, JSONPatchOperationTypedDict
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class PartiallyUpdateWorkspaceByIDRequestTypedDict(TypedDict):
    request_body: List[JSONPatchOperationTypedDict]
    r"""A collection of patch operations to apply to the workspace."""
    organization_id: str
    r"""The unique identifier of the organization"""
    workspace_id: str
    r"""The unique identifier of the workspace"""


class PartiallyUpdateWorkspaceByIDRequest(BaseModel):
    request_body: Annotated[
        List[JSONPatchOperation],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""A collection of patch operations to apply to the workspace."""

    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the organization"""

    workspace_id: Annotated[
        str,
        pydantic.Field(alias="workspaceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the workspace"""
