"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rangelinkdestination import RangeLinkDestination, RangeLinkDestinationTypedDict
from .rangelinksource import RangeLinkSource, RangeLinkSourceTypedDict
from .rangelinktype import RangeLinkType
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class RangeLinkTypedDict(TypedDict):
    r"""Contains properties for a range link."""

    id: str
    r"""The unique identifier of a range link."""
    revision: str
    r"""Identifies a unique revision of content. The same revision can be used for any content request within a file because revisions are allocated at the file-level.
    When querying for content, this can be used to get a consistent version of the content. When editing content, this can be used to make the change to the content at a known state. In either case, omitting the revision (when allowed) will always default to the latest revision of the file.

    """
    table: str
    r"""The unique identifier of a table"""
    type: RangeLinkType
    r"""The type of range link."""
    destination: NotRequired[Nullable[RangeLinkDestinationTypedDict]]
    r"""Contains properties for a range link destination."""
    source: NotRequired[Nullable[RangeLinkSourceTypedDict]]
    r"""Contains properties for a range link source."""


class RangeLink(BaseModel):
    r"""Contains properties for a range link."""

    id: str
    r"""The unique identifier of a range link."""

    revision: str
    r"""Identifies a unique revision of content. The same revision can be used for any content request within a file because revisions are allocated at the file-level.
    When querying for content, this can be used to get a consistent version of the content. When editing content, this can be used to make the change to the content at a known state. In either case, omitting the revision (when allowed) will always default to the latest revision of the file.

    """

    table: str
    r"""The unique identifier of a table"""

    type: RangeLinkType
    r"""The type of range link."""

    destination: OptionalNullable[RangeLinkDestination] = UNSET
    r"""Contains properties for a range link destination."""

    source: OptionalNullable[RangeLinkSource] = UNSET
    r"""Contains properties for a range link source."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["destination", "source"])
        nullable_fields = set(["destination", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
