"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class RangeLinkEditResultType(str, Enum):
    r"""The type of resource created from a range link edit."""

    RANGE_LINK = "rangeLink"


class RangeLinkEditResultTypedDict(TypedDict):
    r"""A reference to a resource that was created by an operation."""

    type: RangeLinkEditResultType
    r"""The type of resource created from a range link edit."""
    range_link: NotRequired[Nullable[str]]
    r"""The ID of the rangeLink that was created."""


class RangeLinkEditResult(BaseModel):
    r"""A reference to a resource that was created by an operation."""

    type: RangeLinkEditResultType
    r"""The type of resource created from a range link edit."""

    range_link: Annotated[OptionalNullable[str], pydantic.Field(alias="rangeLink")] = (
        UNSET
    )
    r"""The ID of the rangeLink that was created."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["rangeLink"])
        nullable_fields = set(["rangeLink"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
