"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from workiva.types import BaseModel


class ResourcePermissionInputTypedDict(TypedDict):
    r"""Mapping of the permission applied to a resource and the details of the principal to which the permission is assigned."""

    permission: str
    r"""The unique identifier of the permission"""
    principal: str
    r"""The unique identifier of the principal"""


class ResourcePermissionInput(BaseModel):
    r"""Mapping of the permission applied to a resource and the details of the principal to which the permission is assigned."""

    permission: str
    r"""The unique identifier of the permission"""

    principal: str
    r"""The unique identifier of the principal"""
