"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class RichTextAnchorCreationResultType(str, Enum):
    r"""The type of resource created from a rich text anchor creation."""

    ANCHOR = "anchor"


class RichTextAnchorCreationResultTypedDict(TypedDict):
    r"""A reference to a resource that was created by an operation."""

    type: RichTextAnchorCreationResultType
    r"""The type of resource created from a rich text anchor creation."""
    anchor: NotRequired[Nullable[str]]
    r"""The ID of the anchor that was created."""


class RichTextAnchorCreationResult(BaseModel):
    r"""A reference to a resource that was created by an operation."""

    type: RichTextAnchorCreationResultType
    r"""The type of resource created from a rich text anchor creation."""

    anchor: OptionalNullable[str] = UNSET
    r"""The ID of the anchor that was created."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["anchor"])
        nullable_fields = set(["anchor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
