"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class SectionRefTypedDict(TypedDict):
    r"""A reference to a section in a document outline"""

    document: NotRequired[str]
    r"""The unique identifier of the document containing the section being referred to"""
    revision: NotRequired[str]
    r"""The revision of the document and section being referred to"""
    section: NotRequired[str]
    r"""The unique identifier of the section being referred to"""


class SectionRef(BaseModel):
    r"""A reference to a section in a document outline"""

    document: Optional[str] = None
    r"""The unique identifier of the document containing the section being referred to"""

    revision: Optional[str] = None
    r"""The revision of the document and section being referred to"""

    section: Optional[str] = None
    r"""The unique identifier of the section being referred to"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["document", "revision", "section"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
