"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clearsectionlockedit import ClearSectionLockEdit, ClearSectionLockEditTypedDict
from .sectionedittype import SectionEditType
from .setnonprintingedit import SetNonPrintingEdit, SetNonPrintingEditTypedDict
from .setsectionlockedit import SetSectionLockEdit, SetSectionLockEditTypedDict
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class SectionEditTypedDict(TypedDict):
    r"""An edit to a section"""

    type: SectionEditType
    r"""The type of the section edit"""
    clear_lock: NotRequired[Nullable[ClearSectionLockEditTypedDict]]
    r"""Clears the selected section's lock value

    """
    set_lock: NotRequired[Nullable[SetSectionLockEditTypedDict]]
    r"""Updates the selected section's lock to the set value

    """
    set_non_printing: NotRequired[Nullable[SetNonPrintingEditTypedDict]]
    r"""Updates sections nonPrinting to the set value

    """


class SectionEdit(BaseModel):
    r"""An edit to a section"""

    type: SectionEditType
    r"""The type of the section edit"""

    clear_lock: Annotated[
        OptionalNullable[ClearSectionLockEdit], pydantic.Field(alias="clearLock")
    ] = UNSET
    r"""Clears the selected section's lock value

    """

    set_lock: Annotated[
        OptionalNullable[SetSectionLockEdit], pydantic.Field(alias="setLock")
    ] = UNSET
    r"""Updates the selected section's lock to the set value

    """

    set_non_printing: Annotated[
        OptionalNullable[SetNonPrintingEdit], pydantic.Field(alias="setNonPrinting")
    ] = UNSET
    r"""Updates sections nonPrinting to the set value

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["clearLock", "setLock", "setNonPrinting"])
        nullable_fields = set(["clearLock", "setLock", "setNonPrinting"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
