"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tabledto import TableDtoInput, TableDtoInputTypedDict
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class SharedTableDtoInputTypedDict(TypedDict):
    destination_workspace_id: str
    r"""The id of the workspace being shared to."""
    source_table_id: str
    r"""The id of the table being shared."""
    table: NotRequired[TableDtoInputTypedDict]


class SharedTableDtoInput(BaseModel):
    destination_workspace_id: Annotated[
        str, pydantic.Field(alias="destinationWorkspaceId")
    ]
    r"""The id of the workspace being shared to."""

    source_table_id: Annotated[str, pydantic.Field(alias="sourceTableId")]
    r"""The id of the table being shared."""

    table: Optional[TableDtoInput] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["table"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
