"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .interval import Interval, IntervalTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL


class SheetUpdateDeleteRowsTypedDict(TypedDict):
    r"""Delete rows from the sheet"""

    intervals: List[IntervalTypedDict]
    force: NotRequired[bool]
    r"""Force the deletion of source links, xbrl facts, connections, etc"""


class SheetUpdateDeleteRows(BaseModel):
    r"""Delete rows from the sheet"""

    intervals: List[Interval]

    force: Optional[bool] = None
    r"""Force the deletion of source links, xbrl facts, connections, etc"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["force"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
