"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .range import Range, RangeTypedDict
import pydantic
from pydantic import model_serializer
from typing import Any, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class SheetUpdateEditRangeOptionsTypedDict(TypedDict):
    r"""Edit range options"""

    apply_entered_in_scaling: NotRequired[bool]
    r"""Whether or not to apply `enteredIn` scaling

    """
    skip_edit_merge_children: NotRequired[bool]
    r"""Whether or not to skip edits to merge child cells

    """


class SheetUpdateEditRangeOptions(BaseModel):
    r"""Edit range options"""

    apply_entered_in_scaling: Annotated[
        Optional[bool], pydantic.Field(alias="applyEnteredInScaling")
    ] = False
    r"""Whether or not to apply `enteredIn` scaling

    """

    skip_edit_merge_children: Annotated[
        Optional[bool], pydantic.Field(alias="skipEditMergeChildren")
    ] = False
    r"""Whether or not to skip edits to merge child cells

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["applyEnteredInScaling", "skipEditMergeChildren"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SheetUpdateEditRangeTypedDict(TypedDict):
    r"""Edit all of the cells in a contiguous range"""

    range: Nullable[RangeTypedDict]
    r"""A range in a sheet. If any field is omitted or null, the range is unbounded in that direction."""
    values: List[List[Nullable[Any]]]
    r"""Row-major ordered two-dimensional array of cell values"""
    options: NotRequired[Nullable[SheetUpdateEditRangeOptionsTypedDict]]
    r"""Edit range options"""


class SheetUpdateEditRange(BaseModel):
    r"""Edit all of the cells in a contiguous range"""

    range: Nullable[Range]
    r"""A range in a sheet. If any field is omitted or null, the range is unbounded in that direction."""

    values: List[List[Nullable[Any]]]
    r"""Row-major ordered two-dimensional array of cell values"""

    options: OptionalNullable[SheetUpdateEditRangeOptions] = UNSET
    r"""Edit range options"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["options"])
        nullable_fields = set(["options", "range"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
