"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .taskaction import TaskAction, TaskActionTypedDict
import pydantic
from typing_extensions import Annotated, TypedDict
from workiva.types import BaseModel
from workiva.utils import FieldMetadata, PathParamMetadata, RequestMetadata


class SubmitTaskActionRequestTypedDict(TypedDict):
    task_id: str
    r"""The unique identifier of the task"""
    task_action: TaskActionTypedDict
    r"""The action to be applied on the task."""


class SubmitTaskActionRequest(BaseModel):
    task_id: Annotated[
        str,
        pydantic.Field(alias="taskId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the task"""

    task_action: Annotated[
        TaskAction,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The action to be applied on the task."""
