"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class TableLinksEditResultType(str, Enum):
    r"""The type of resource created from a table link edit."""

    DESTINATION_LINK = "destinationLink"


class TableLinksEditResultTypedDict(TypedDict):
    r"""A reference to a resource that was created by an operation."""

    type: TableLinksEditResultType
    r"""The type of resource created from a table link edit."""
    destination_link: NotRequired[Nullable[str]]
    r"""The unique identifier of a destination link created by the table links edit."""


class TableLinksEditResult(BaseModel):
    r"""A reference to a resource that was created by an operation."""

    type: TableLinksEditResultType
    r"""The type of resource created from a table link edit."""

    destination_link: Annotated[
        OptionalNullable[str], pydantic.Field(alias="destinationLink")
    ] = UNSET
    r"""The unique identifier of a destination link created by the table links edit."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["destinationLink"])
        nullable_fields = set(["destinationLink"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
