"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from workiva.types import BaseModel


class TableCellConnectionTypedDict(TypedDict):
    r"""Represents a connection to a value from a Workiva table cell"""

    cell: str
    r"""The column-row identifier of a specific cell within a table (i.e. A1)"""
    document: str
    r"""The unique identifier of the connected document."""
    section: str
    r"""The unique identifier of a specific section within the document."""
    table: str
    r"""The unique identifier of a specific table within the document."""


class TableCellConnection(BaseModel):
    r"""Represents a connection to a value from a Workiva table cell"""

    cell: str
    r"""The column-row identifier of a specific cell within a table (i.e. A1)"""

    document: str
    r"""The unique identifier of the connected document."""

    section: str
    r"""The unique identifier of a specific section within the document."""

    table: str
    r"""The unique identifier of a specific table within the document."""
