"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tablelinkseditresult import TableLinksEditResult, TableLinksEditResultTypedDict
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class TableLinksEditListResultTypedDict(TypedDict):
    r"""Returns a JSON object with `data` and `@nextLink` properties. `data` contains a list of [`TextLinksEditResult`](ref:content#textlinkseditresult) objects, and `@nextLink` provides the URL to the next set of results. If there are no additional results, `@nextLink` doesn't appear. If the request returns no results at all, `data` contains an empty array."""

    at_next_link: NotRequired[Nullable[str]]
    r"""Pagination link for next set of results"""
    data: NotRequired[List[TableLinksEditResultTypedDict]]
    revision: NotRequired[str]
    r"""Identifies a unique revision of content."""


class TableLinksEditListResult(BaseModel):
    r"""Returns a JSON object with `data` and `@nextLink` properties. `data` contains a list of [`TextLinksEditResult`](ref:content#textlinkseditresult) objects, and `@nextLink` provides the URL to the next set of results. If there are no additional results, `@nextLink` doesn't appear. If the request returns no results at all, `data` contains an empty array."""

    at_next_link: Annotated[
        OptionalNullable[str], pydantic.Field(alias="@nextLink")
    ] = UNSET
    r"""Pagination link for next set of results"""

    data: Optional[List[TableLinksEditResult]] = None

    revision: Optional[str] = None
    r"""Identifies a unique revision of content."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["@nextLink", "data", "revision"])
        nullable_fields = set(["@nextLink"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
