"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, UNSET_SENTINEL
from workiva.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata


WDATA_DOWNLOAD_FILE_OP_SERVERS = [
    # US
    "https://h.app.wdesk.com/s/wdata/prep",
    # EU
    "https://h.eu.wdesk.com/s/wdata/prep",
    # APAC
    "https://h.apac.wdesk.com/s/wdata/prep",
]


class WdataDownloadFileRequestTypedDict(TypedDict):
    token_id: str
    r"""The unique identifier of the token"""
    filename: NotRequired[str]
    r"""A filename for the download; if included, the default filename is overridden"""


class WdataDownloadFileRequest(BaseModel):
    token_id: Annotated[
        str,
        pydantic.Field(alias="tokenId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the token"""

    filename: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A filename for the download; if included, the default filename is overridden"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filename"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
