"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationuser import OrganizationUser, OrganizationUserTypedDict
from .workspace import Workspace, WorkspaceTypedDict
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from workiva.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class WorkspaceMembershipUserTypedDict(TypedDict):
    r"""A user refernenced by their unique identifier"""

    id: NotRequired[str]
    r"""The unique identifier of the user"""


class WorkspaceMembershipUser(BaseModel):
    r"""A user refernenced by their unique identifier"""

    id: Optional[str] = None
    r"""The unique identifier of the user"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WorkspaceMembershipCreatedTypedDict(TypedDict):
    r"""When the action was performed, and details about the user who did it"""

    date_time: NotRequired[datetime]
    r"""When the action was performed"""
    user: NotRequired[Nullable[WorkspaceMembershipUserTypedDict]]


class WorkspaceMembershipCreated(BaseModel):
    r"""When the action was performed, and details about the user who did it"""

    date_time: Annotated[Optional[datetime], pydantic.Field(alias="dateTime")] = None
    r"""When the action was performed"""

    user: OptionalNullable[WorkspaceMembershipUser] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["dateTime", "user"])
        nullable_fields = set(["user"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class WorkspaceMembershipSchemasUserTypedDict(TypedDict):
    r"""A user refernenced by their unique identifier"""

    id: NotRequired[str]
    r"""The unique identifier of the user"""


class WorkspaceMembershipSchemasUser(BaseModel):
    r"""A user refernenced by their unique identifier"""

    id: Optional[str] = None
    r"""The unique identifier of the user"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WorkspaceMembershipModifiedTypedDict(TypedDict):
    r"""When the action was performed, and details about the user who did it"""

    date_time: NotRequired[datetime]
    r"""When the action was performed"""
    user: NotRequired[Nullable[WorkspaceMembershipSchemasUserTypedDict]]


class WorkspaceMembershipModified(BaseModel):
    r"""When the action was performed, and details about the user who did it"""

    date_time: Annotated[Optional[datetime], pydantic.Field(alias="dateTime")] = None
    r"""When the action was performed"""

    user: OptionalNullable[WorkspaceMembershipSchemasUser] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["dateTime", "user"])
        nullable_fields = set(["user"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class WorkspaceMembershipTypedDict(TypedDict):
    r"""Details about a user's membership in a workspace."""

    created: NotRequired[Nullable[WorkspaceMembershipCreatedTypedDict]]
    id: NotRequired[Nullable[str]]
    r"""The unique identifier of the workspace membership"""
    modified: NotRequired[Nullable[WorkspaceMembershipModifiedTypedDict]]
    user: NotRequired[OrganizationUserTypedDict]
    r"""The user that is a member of the workspace"""
    workspace: NotRequired[WorkspaceTypedDict]
    r"""The workspace that this membership belongs to"""


class WorkspaceMembership(BaseModel):
    r"""Details about a user's membership in a workspace."""

    created: OptionalNullable[WorkspaceMembershipCreated] = UNSET

    id: OptionalNullable[str] = UNSET
    r"""The unique identifier of the workspace membership"""

    modified: OptionalNullable[WorkspaceMembershipModified] = UNSET

    user: Optional[OrganizationUser] = None
    r"""The user that is a member of the workspace"""

    workspace: Optional[Workspace] = None
    r"""The workspace that this membership belongs to"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["created", "id", "modified", "user", "workspace"])
        nullable_fields = set(["created", "id", "modified"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
