"""Platform API — iam namespace.

Auto-generated by codegen. Do not edit manually.
"""

from __future__ import annotations

from typing import Any, Optional

import httpx

from workiva._constants import _API
from workiva._operations._base import BaseNamespace


class Iam(BaseNamespace):
    """Iam operations."""

    _api: _API = _API.PLATFORM

    def token_request(
        self,
        *,
        body: Optional[dict[str, Any]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a token

        Include the client_id and client_secret in the body of the request as
        form encoded parameters. For example, the body of the request would be `
        grant_type=client_credentials&client_id=<client_id>&client_secret=<clien
        t_secret>`. The client can optionally specify a `scope` parameter to
        limit the scope of the returned [access token](ref:helpers#bearertoken).
        In turn, the server uses a `scope` response parameter to inform the
        client of the scope of the actual access token issued. The actual
        `scope` returned may not match the `scope` requested. Subsequent
        requests to Workiva APIs are authorized using the bearer token.
        """
        return self._client.request(
            "POST",
            self._api,
            "/oauth2/token",
            json_body=body,
            timeout=timeout,
        )

    async def token_request_async(
        self,
        *,
        body: Optional[dict[str, Any]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a token (async)

        Include the client_id and client_secret in the body of the request as
        form encoded parameters. For example, the body of the request would be `
        grant_type=client_credentials&client_id=<client_id>&client_secret=<clien
        t_secret>`. The client can optionally specify a `scope` parameter to
        limit the scope of the returned [access token](ref:helpers#bearertoken).
        In turn, the server uses a `scope` response parameter to inform the
        client of the scope of the actual access token issued. The actual
        `scope` returned may not match the `scope` requested. Subsequent
        requests to Workiva APIs are authorized using the bearer token.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/oauth2/token",
            json_body=body,
            timeout=timeout,
        )
