"""Wdata API — parameter_management namespace.

Auto-generated by codegen. Do not edit manually.
"""

from __future__ import annotations

from typing import Any, Optional

import httpx

from workiva._constants import _API
from workiva._operations._base import BaseNamespace
from workiva.models.wdata import (
    GlobalParameterDto,
)


class ParameterManagement(BaseNamespace):
    """ParameterManagement operations."""

    _api: _API = _API.WDATA

    def list_parameters(
        self,
        *,
        cursor: Optional[str] = None,
        limit: Optional[int] = 1000,
        offset: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Get Parameters

        Returns a list of all parameters associated with the workspace.  By
        default, these
        parameters are ordered by their names in ascending order.
        """
        return self._client.request(
            "GET",
            self._api,
            "/api/v1/parameter",
            query_params={
                "cursor": cursor,
                "limit": limit,
                "offset": offset,
            },
            timeout=timeout,
        )

    async def list_parameters_async(
        self,
        *,
        cursor: Optional[str] = None,
        limit: Optional[int] = 1000,
        offset: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Get Parameters (async)

        Returns a list of all parameters associated with the workspace.  By
        default, these
        parameters are ordered by their names in ascending order.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/api/v1/parameter",
            query_params={
                "cursor": cursor,
                "limit": limit,
                "offset": offset,
            },
            timeout=timeout,
        )

    def create_parameter(
        self,
        *,
        body: GlobalParameterDto,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Create parameter

        Creates a parameter.  If there is a parameter with the same ID, a 409 is
        returned.
        """
        return self._client.request(
            "POST",
            self._api,
            "/api/v1/parameter",
            json_body=body,
            timeout=timeout,
        )

    async def create_parameter_async(
        self,
        *,
        body: GlobalParameterDto,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Create parameter (async)

        Creates a parameter.  If there is a parameter with the same ID, a 409 is
        returned.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/api/v1/parameter",
            json_body=body,
            timeout=timeout,
        )

    def get_parameter(
        self,
        *,
        parameter_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Get Parameter

        Returns a parameter matching the provided parameter ID.  If no matching
        entity can be found, a 404 status is returned.
        """
        return self._client.request(
            "GET",
            self._api,
            "/api/v1/parameter/{parameterId}",
            path_params={
                "parameterId": parameter_id,
            },
            timeout=timeout,
        )

    async def get_parameter_async(
        self,
        *,
        parameter_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Get Parameter (async)

        Returns a parameter matching the provided parameter ID.  If no matching
        entity can be found, a 404 status is returned.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/api/v1/parameter/{parameterId}",
            path_params={
                "parameterId": parameter_id,
            },
            timeout=timeout,
        )

    def delete_parameter(
        self,
        *,
        parameter_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Delete Parameter

        Deletes the parameter with the provided parameter ID.  If the parameter
        is not found, this is a no-op.
        """
        return self._client.request(
            "DELETE",
            self._api,
            "/api/v1/parameter/{parameterId}",
            path_params={
                "parameterId": parameter_id,
            },
            timeout=timeout,
        )

    async def delete_parameter_async(
        self,
        *,
        parameter_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Delete Parameter (async)

        Deletes the parameter with the provided parameter ID.  If the parameter
        is not found, this is a no-op.
        """
        return await self._client.request_async(
            "DELETE",
            self._api,
            "/api/v1/parameter/{parameterId}",
            path_params={
                "parameterId": parameter_id,
            },
            timeout=timeout,
        )

    def update_parameter(
        self,
        *,
        parameter_id: str,
        body: GlobalParameterDto,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Update Parameter

        Updates the parameter matching the provided ID in the provided payload.
        """
        return self._client.request(
            "PUT",
            self._api,
            "/api/v1/parameter/{parameterId}",
            path_params={
                "parameterId": parameter_id,
            },
            json_body=body,
            timeout=timeout,
        )

    async def update_parameter_async(
        self,
        *,
        parameter_id: str,
        body: GlobalParameterDto,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Update Parameter (async)

        Updates the parameter matching the provided ID in the provided payload.
        """
        return await self._client.request_async(
            "PUT",
            self._api,
            "/api/v1/parameter/{parameterId}",
            path_params={
                "parameterId": parameter_id,
            },
            json_body=body,
            timeout=timeout,
        )
