"""Platform API — tasks namespace.

Auto-generated by codegen. Do not edit manually.
"""

from __future__ import annotations

from typing import Any, Optional

import httpx

from workiva._constants import _API
from workiva._operations._base import BaseNamespace
from workiva.models.platform import (
    Task,
    TaskAction,
)


class Tasks(BaseNamespace):
    """Tasks operations."""

    _api: _API = _API.PLATFORM

    def create_task(
        self,
        *,
        body: Task,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Create a new task

        Creates a new [task](ref:tasks#task) given its properties.
        """
        return self._client.request(
            "POST",
            self._api,
            "/tasks",
            json_body=body,
            timeout=timeout,
        )

    async def create_task_async(
        self,
        *,
        body: Task,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Create a new task (async)

        Creates a new [task](ref:tasks#task) given its properties.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/tasks",
            json_body=body,
            timeout=timeout,
        )

    def get_tasks(
        self,
        *,
        filter_: Optional[str] = None,
        order_by: Optional[str] = None,
        maxpagesize: Optional[int] = 1000,
        next_: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of tasks

        > Returns a paginated list of [tasks](ref:tasks#task). Currently this
        endpoint returns general tasks
        (such as those created as part of editing documents, sheets, and
        presentations) and tasks that have been associated  with a
        Sustainability Program.
        It does not return tasks created as part of a process.
        """
        return self._client.request(
            "GET",
            self._api,
            "/tasks",
            query_params={
                "$filter": filter_,
                "$orderBy": order_by,
                "$maxpagesize": maxpagesize,
                "$next": next_,
            },
            timeout=timeout,
        )

    async def get_tasks_async(
        self,
        *,
        filter_: Optional[str] = None,
        order_by: Optional[str] = None,
        maxpagesize: Optional[int] = 1000,
        next_: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of tasks (async)

        > Returns a paginated list of [tasks](ref:tasks#task). Currently this
        endpoint returns general tasks
        (such as those created as part of editing documents, sheets, and
        presentations) and tasks that have been associated  with a
        Sustainability Program.
        It does not return tasks created as part of a process.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/tasks",
            query_params={
                "$filter": filter_,
                "$orderBy": order_by,
                "$maxpagesize": maxpagesize,
                "$next": next_,
            },
            timeout=timeout,
        )

    def get_task_by_id(
        self,
        *,
        task_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single task

        Retrieves a [task](ref:tasks#task) given its ID
        """
        return self._client.request(
            "GET",
            self._api,
            "/tasks/{taskId}",
            path_params={
                "taskId": task_id,
            },
            timeout=timeout,
        )

    async def get_task_by_id_async(
        self,
        *,
        task_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single task (async)

        Retrieves a [task](ref:tasks#task) given its ID
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/tasks/{taskId}",
            path_params={
                "taskId": task_id,
            },
            timeout=timeout,
        )

    def delete_task_by_id(
        self,
        *,
        task_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Delete a single task

        Deletes a [task](ref:tasks#task) given its ID
        """
        return self._client.request(
            "DELETE",
            self._api,
            "/tasks/{taskId}",
            path_params={
                "taskId": task_id,
            },
            timeout=timeout,
        )

    async def delete_task_by_id_async(
        self,
        *,
        task_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Delete a single task (async)

        Deletes a [task](ref:tasks#task) given its ID
        """
        return await self._client.request_async(
            "DELETE",
            self._api,
            "/tasks/{taskId}",
            path_params={
                "taskId": task_id,
            },
            timeout=timeout,
        )

    def partially_update_task_by_id(
        self,
        *,
        task_id: str,
        body: list[Any],
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Partially update a single task

        Partially updates the properties of a [task](ref:tasks#task).
        Please note: Tasks are automatically restarted when the following
        properties are updated:
        - `assignees`
        - `approvalSteps`: If any `participants` who have already approved are
        updated, the task will be restarted.
        - `location`
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/approvalSteps`|`replace`|
        |`/assignees`|`replace`|
        |`/description`|`replace`|
        |`/dueDate`|`replace`|
        |`/location`|`replace`|
        |`/owner`|`replace`|
        |`/title`|`replace`|
        """
        return self._client.request(
            "PATCH",
            self._api,
            "/tasks/{taskId}",
            path_params={
                "taskId": task_id,
            },
            json_body=body,
            timeout=timeout,
        )

    async def partially_update_task_by_id_async(
        self,
        *,
        task_id: str,
        body: list[Any],
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Partially update a single task (async)

        Partially updates the properties of a [task](ref:tasks#task).
        Please note: Tasks are automatically restarted when the following
        properties are updated:
        - `assignees`
        - `approvalSteps`: If any `participants` who have already approved are
        updated, the task will be restarted.
        - `location`
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/approvalSteps`|`replace`|
        |`/assignees`|`replace`|
        |`/description`|`replace`|
        |`/dueDate`|`replace`|
        |`/location`|`replace`|
        |`/owner`|`replace`|
        |`/title`|`replace`|
        """
        return await self._client.request_async(
            "PATCH",
            self._api,
            "/tasks/{taskId}",
            path_params={
                "taskId": task_id,
            },
            json_body=body,
            timeout=timeout,
        )

    def submit_task_action(
        self,
        *,
        task_id: str,
        body: TaskAction,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a task action submission

        This endpoint enables submitting actions on a [task](ref:tasks#task).
        For tasks with multiple approval steps, it's the only way to advance a
        task through the approval process.
        """
        return self._client.request(
            "POST",
            self._api,
            "/tasks/{taskId}/actionSubmission",
            path_params={
                "taskId": task_id,
            },
            json_body=body,
            timeout=timeout,
        )

    async def submit_task_action_async(
        self,
        *,
        task_id: str,
        body: TaskAction,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a task action submission (async)

        This endpoint enables submitting actions on a [task](ref:tasks#task).
        For tasks with multiple approval steps, it's the only way to advance a
        task through the approval process.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/tasks/{taskId}/actionSubmission",
            path_params={
                "taskId": task_id,
            },
            json_body=body,
            timeout=timeout,
        )
