"""Platform API — test_forms namespace.

Auto-generated by codegen. Do not edit manually.
"""

from __future__ import annotations

from typing import Any, Literal, Optional

import httpx

from workiva._constants import _API
from workiva._operations._base import BaseNamespace
from workiva.models.platform import (
    GraphAttachment,
    GraphAttachmentsListResult,
    GraphAttachmentUploadResponse,
    MatricesListResult,
    Matrix,
    MatrixColumn,
    MatrixSample,
    MatrixSamplesListResult,
    SampleCell,
    TestForm,
    TestFormsListResult,
    TestPhase,
    TestPhasesListResult,
)

__all__ = ["TestForms"]


class TestForms(BaseNamespace):
    """TestForms operations."""

    _api: _API = _API.PLATFORM

    def get_test_forms(
        self,
        *,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> TestFormsListResult:
        """Retrieve a list of test forms

        Retrieves a list of [test forms](ref:testforms#testform).

        Args:
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            TestFormsListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms",
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return TestFormsListResult.model_validate(response.json())

    async def get_test_forms_async(
        self,
        *,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> TestFormsListResult:
        """Retrieve a list of test forms (async)

        Retrieves a list of [test forms](ref:testforms#testform).

        Args:
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            TestFormsListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms",
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return TestFormsListResult.model_validate(response.json())

    def get_test_form_by_id(
        self,
        *,
        test_form_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> TestForm:
        """Retrieve a single test form

        Retrieves a [test form](ref:testforms#testform) given its ID.

        Args:
            test_form_id: The unique identifier of the test form
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            TestForm

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}",
            path_params={
                "testFormId": test_form_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return TestForm.model_validate(response.json())

    async def get_test_form_by_id_async(
        self,
        *,
        test_form_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> TestForm:
        """Retrieve a single test form (async)

        Retrieves a [test form](ref:testforms#testform) given its ID.

        Args:
            test_form_id: The unique identifier of the test form
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            TestForm

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}",
            path_params={
                "testFormId": test_form_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return TestForm.model_validate(response.json())

    def test_form_export(
        self,
        *,
        test_form_id: str,
        format_: Optional[Literal["xlsx"]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a test form export

        Asynchronously exports a [test form](ref:testforms#testform).

        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            format_: The format to export the test form to—currently, only .XLSX
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        _body: dict[str, Any] = {}
        if format_ is not None:
            _body["format"] = format_
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/export",
            path_params={
                "testFormId": test_form_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )

    async def test_form_export_async(
        self,
        *,
        test_form_id: str,
        format_: Optional[Literal["xlsx"]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a test form export (async)

        Asynchronously exports a [test form](ref:testforms#testform).

        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            format_: The format to export the test form to—currently, only .XLSX
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        _body: dict[str, Any] = {}
        if format_ is not None:
            _body["format"] = format_
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/export",
            path_params={
                "testFormId": test_form_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )

    def get_test_phases(
        self,
        *,
        test_form_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> TestPhasesListResult:
        """Retrieve a list of test phases

        Returns a list of [test phases](ref:testforms#testphase).

        Args:
            test_form_id: The unique identifier of the test form
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            TestPhasesListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases",
            path_params={
                "testFormId": test_form_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return TestPhasesListResult.model_validate(response.json())

    async def get_test_phases_async(
        self,
        *,
        test_form_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> TestPhasesListResult:
        """Retrieve a list of test phases (async)

        Returns a list of [test phases](ref:testforms#testphase).

        Args:
            test_form_id: The unique identifier of the test form
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            TestPhasesListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases",
            path_params={
                "testFormId": test_form_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return TestPhasesListResult.model_validate(response.json())

    def get_test_phase_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> TestPhase:
        """Retrive a single test phase

        Retrieves a [test phase](ref:testforms#testphase) given its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            TestPhase

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return TestPhase.model_validate(response.json())

    async def get_test_phase_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> TestPhase:
        """Retrive a single test phase (async)

        Retrieves a [test phase](ref:testforms#testphase) given its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            TestPhase

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return TestPhase.model_validate(response.json())

    def test_phase_attachment_upload(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        file_name: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentUploadResponse:
        """Initiate a test phase attachment upload

        Starts the process to upload and attach a file to a [test
        phase](ref:testforms#testphase) using a [graph attachment
        upload](ref:testforms#graphattachmentupload) object. The response body
        will include an `uploadUrl`. To upload the file contents, perform a PUT
        on the `uploadUrl` with the same authentication credentials and flow as
        the attachmentUpload request. For more details, see [Authentication
        documentation](ref:authentication).

        The response also includes a `Location` header, which indicates where to
        poll for operation results. For more details on long-running job
        polling, see [Operations endpoint](ref:getoperationbyid).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            file_name: The file name of the graph attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentUploadResponse

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if file_name is not None:
            _body["fileName"] = file_name
        response = self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachmentUpload",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return GraphAttachmentUploadResponse.model_validate(response.json())

    async def test_phase_attachment_upload_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        file_name: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentUploadResponse:
        """Initiate a test phase attachment upload (async)

        Starts the process to upload and attach a file to a [test
        phase](ref:testforms#testphase) using a [graph attachment
        upload](ref:testforms#graphattachmentupload) object. The response body
        will include an `uploadUrl`. To upload the file contents, perform a PUT
        on the `uploadUrl` with the same authentication credentials and flow as
        the attachmentUpload request. For more details, see [Authentication
        documentation](ref:authentication).

        The response also includes a `Location` header, which indicates where to
        poll for operation results. For more details on long-running job
        polling, see [Operations endpoint](ref:getoperationbyid).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            file_name: The file name of the graph attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentUploadResponse

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if file_name is not None:
            _body["fileName"] = file_name
        response = await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachmentUpload",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return GraphAttachmentUploadResponse.model_validate(response.json())

    def get_test_phase_attachments(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentsListResult:
        """Retrieve a list of test phase attachments

        Returns a list of [attachments](ref:testforms#graphattachment) for a
        [test phase](ref:testforms#testphase).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentsListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachments",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            timeout=timeout,
        )
        return GraphAttachmentsListResult.model_validate(response.json())

    async def get_test_phase_attachments_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentsListResult:
        """Retrieve a list of test phase attachments (async)

        Returns a list of [attachments](ref:testforms#graphattachment) for a
        [test phase](ref:testforms#testphase).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentsListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachments",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            timeout=timeout,
        )
        return GraphAttachmentsListResult.model_validate(response.json())

    def get_test_phase_attachment_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachment:
        """Retrieve a single test phase attachment

        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachment

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )
        return GraphAttachment.model_validate(response.json())

    async def get_test_phase_attachment_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachment:
        """Retrieve a single test phase attachment (async)

        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachment

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )
        return GraphAttachment.model_validate(response.json())

    def test_phase_attachment_download_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a test phase attachment download

        Asynchronously downloads an attachment from a [test
        phase](ref:testforms#testphase).

        Responses include a `Location` header, which indicates where to poll for
        download results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the download is ready,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the file, perform a GET on the `resourceURL`
        with the same authentication credentials and flow as the download
        request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}/download",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )

    async def test_phase_attachment_download_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a test phase attachment download (async)

        Asynchronously downloads an attachment from a [test
        phase](ref:testforms#testphase).

        Responses include a `Location` header, which indicates where to poll for
        download results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the download is ready,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the file, perform a GET on the `resourceURL`
        with the same authentication credentials and flow as the download
        request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}/download",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )

    def test_phase_attachment_export_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        attachment_id: str,
        format_: Optional[Literal["pdf"]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a test phase attachment export

        Asynchronously exports an attachment for a [test
        phase](ref:testforms#testphase) to .PDF.

        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            attachment_id: The unique identifier of the attachment
            format_: The format to export the attachment to — currently, .PDF only
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        _body: dict[str, Any] = {}
        if format_ is not None:
            _body["format"] = format_
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}/export",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "attachmentId": attachment_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )

    async def test_phase_attachment_export_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        attachment_id: str,
        format_: Optional[Literal["pdf"]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a test phase attachment export (async)

        Asynchronously exports an attachment for a [test
        phase](ref:testforms#testphase) to .PDF.

        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            attachment_id: The unique identifier of the attachment
            format_: The format to export the attachment to — currently, .PDF only
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        _body: dict[str, Any] = {}
        if format_ is not None:
            _body["format"] = format_
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/attachments/{attachmentId}/export",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "attachmentId": attachment_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )

    def create_matrix(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        data_columns: Optional[list[MatrixColumn]] = None,
        name: Optional[str] = None,
        result_columns: Optional[list[MatrixColumn]] = None,
        timeout: Optional[float] = None,
    ) -> Matrix:
        """Create a new matrix

        Create a new empty [matrix](ref:testforms#matrix). The `id` field for
        the matrix and its columns should be left blank; this will be populated
        by the endpoint.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            data_columns: An array of the data columns in the matrix
            name: The name of the matrix
            result_columns: An array of the result columns in the matrix
            timeout: Override the default request timeout (seconds).

        Returns:
            Matrix

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if data_columns is not None:
            _body["dataColumns"] = data_columns
        if name is not None:
            _body["name"] = name
        if result_columns is not None:
            _body["resultColumns"] = result_columns
        response = self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return Matrix.model_validate(response.json())

    async def create_matrix_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        data_columns: Optional[list[MatrixColumn]] = None,
        name: Optional[str] = None,
        result_columns: Optional[list[MatrixColumn]] = None,
        timeout: Optional[float] = None,
    ) -> Matrix:
        """Create a new matrix (async)

        Create a new empty [matrix](ref:testforms#matrix). The `id` field for
        the matrix and its columns should be left blank; this will be populated
        by the endpoint.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            data_columns: An array of the data columns in the matrix
            name: The name of the matrix
            result_columns: An array of the result columns in the matrix
            timeout: Override the default request timeout (seconds).

        Returns:
            Matrix

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if data_columns is not None:
            _body["dataColumns"] = data_columns
        if name is not None:
            _body["name"] = name
        if result_columns is not None:
            _body["resultColumns"] = result_columns
        response = await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return Matrix.model_validate(response.json())

    def get_matrices(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> MatricesListResult:
        """Retrieve a list of matrices

        Returns a list of [matrices](ref:testforms#matrix).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            MatricesListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return MatricesListResult.model_validate(response.json())

    async def get_matrices_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> MatricesListResult:
        """Retrieve a list of matrices (async)

        Returns a list of [matrices](ref:testforms#matrix).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            MatricesListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return MatricesListResult.model_validate(response.json())

    def get_matrix_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> Matrix:
        """Retrieve a single matrix

        Retrieves a [matrix](ref:testforms#matrix) given its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            Matrix

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return Matrix.model_validate(response.json())

    async def get_matrix_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> Matrix:
        """Retrieve a single matrix (async)

        Retrieves a [matrix](ref:testforms#matrix) given its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            Matrix

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return Matrix.model_validate(response.json())

    def matrix_attachment_upload(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        file_name: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentUploadResponse:
        """Initiate a matrix attachment upload

        Starts the process to upload and attach a file to a
        [matrix](ref:testforms#matrix) using a [graph attachment
        upload](ref:testforms#graphattachmentupload) object. The response body
        will include an `uploadUrl`. To upload the file contents, perform a PUT
        on the `uploadUrl` with the same authentication credentials and flow as
        the attachmentUpload request. For more details, see [Authentication
        documentation](ref:overview#authentication).

        The response also includes a `Location` header, which indicates where to
        poll for operation results. For more details on long-running job
        polling, see [Operations endpoint](ref:getoperationbyid).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            file_name: The file name of the graph attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentUploadResponse

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if file_name is not None:
            _body["fileName"] = file_name
        response = self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachmentUpload",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return GraphAttachmentUploadResponse.model_validate(response.json())

    async def matrix_attachment_upload_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        file_name: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentUploadResponse:
        """Initiate a matrix attachment upload (async)

        Starts the process to upload and attach a file to a
        [matrix](ref:testforms#matrix) using a [graph attachment
        upload](ref:testforms#graphattachmentupload) object. The response body
        will include an `uploadUrl`. To upload the file contents, perform a PUT
        on the `uploadUrl` with the same authentication credentials and flow as
        the attachmentUpload request. For more details, see [Authentication
        documentation](ref:overview#authentication).

        The response also includes a `Location` header, which indicates where to
        poll for operation results. For more details on long-running job
        polling, see [Operations endpoint](ref:getoperationbyid).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            file_name: The file name of the graph attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentUploadResponse

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if file_name is not None:
            _body["fileName"] = file_name
        response = await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachmentUpload",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return GraphAttachmentUploadResponse.model_validate(response.json())

    def get_matrix_attachments(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentsListResult:
        """Retrieve a list of matrix attachments

        Returns a list of [attachments](ref:testforms#graphattachment) for a
        matrix.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentsListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            timeout=timeout,
        )
        return GraphAttachmentsListResult.model_validate(response.json())

    async def get_matrix_attachments_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentsListResult:
        """Retrieve a list of matrix attachments (async)

        Returns a list of [attachments](ref:testforms#graphattachment) for a
        matrix.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentsListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            timeout=timeout,
        )
        return GraphAttachmentsListResult.model_validate(response.json())

    def get_matrix_attachment_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachment:
        """Retrieve a single matrix attachment

        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachment

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )
        return GraphAttachment.model_validate(response.json())

    async def get_matrix_attachment_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachment:
        """Retrieve a single matrix attachment (async)

        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachment

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )
        return GraphAttachment.model_validate(response.json())

    def matrix_attachment_download_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a matrix attachment download

        Asynchronously downloads an attachment from a
        [matrix](ref:testforms#matrix).

        Responses include a `Location` header, which indicates where to poll for
        download results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the download is ready,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the file, perform a GET on the `resourceURL`
        with the same authentication credentials and flow as the download
        request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}/download",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )

    async def matrix_attachment_download_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a matrix attachment download (async)

        Asynchronously downloads an attachment from a
        [matrix](ref:testforms#matrix).

        Responses include a `Location` header, which indicates where to poll for
        download results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the download is ready,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the file, perform a GET on the `resourceURL`
        with the same authentication credentials and flow as the download
        request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}/download",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )

    def matrix_attachment_export_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        attachment_id: str,
        format_: Optional[Literal["pdf"]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate an export of a matrix attachment

        Asynchronously exports an attachment for a
        [matrix](ref:testforms#matrix) to .PDF.

        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            attachment_id: The unique identifier of the attachment
            format_: The format to export the attachment to — currently, .PDF only
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        _body: dict[str, Any] = {}
        if format_ is not None:
            _body["format"] = format_
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}/export",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "attachmentId": attachment_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )

    async def matrix_attachment_export_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        attachment_id: str,
        format_: Optional[Literal["pdf"]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate an export of a matrix attachment (async)

        Asynchronously exports an attachment for a
        [matrix](ref:testforms#matrix) to .PDF.

        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            attachment_id: The unique identifier of the attachment
            format_: The format to export the attachment to — currently, .PDF only
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        _body: dict[str, Any] = {}
        if format_ is not None:
            _body["format"] = format_
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/attachments/{attachmentId}/export",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "attachmentId": attachment_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )

    def create_sample(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        data_values: Optional[list[SampleCell]] = None,
        id_: Optional[str] = None,
        result_values: Optional[list[SampleCell]] = None,
        timeout: Optional[float] = None,
    ) -> MatrixSample:
        """Create a new sample

        Create a new [sample](ref:testforms#matrixsample) in a
        [matrix](ref:testforms#matrix). The new sample will be appended to the
        end of the matrix.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            data_values: An array of SampleCell values representing the values for each data column of the sample matrix's cells
            id_: The unique ID of the matrix sample
            result_values: An array of SampleCell values representing the values for each result cell in the sample matrix's cells.
            timeout: Override the default request timeout (seconds).

        Returns:
            MatrixSample

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if data_values is not None:
            _body["dataValues"] = data_values
        if id_ is not None:
            _body["id"] = id_
        if result_values is not None:
            _body["resultValues"] = result_values
        response = self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return MatrixSample.model_validate(response.json())

    async def create_sample_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        data_values: Optional[list[SampleCell]] = None,
        id_: Optional[str] = None,
        result_values: Optional[list[SampleCell]] = None,
        timeout: Optional[float] = None,
    ) -> MatrixSample:
        """Create a new sample (async)

        Create a new [sample](ref:testforms#matrixsample) in a
        [matrix](ref:testforms#matrix). The new sample will be appended to the
        end of the matrix.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            data_values: An array of SampleCell values representing the values for each data column of the sample matrix's cells
            id_: The unique ID of the matrix sample
            result_values: An array of SampleCell values representing the values for each result cell in the sample matrix's cells.
            timeout: Override the default request timeout (seconds).

        Returns:
            MatrixSample

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if data_values is not None:
            _body["dataValues"] = data_values
        if id_ is not None:
            _body["id"] = id_
        if result_values is not None:
            _body["resultValues"] = result_values
        response = await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return MatrixSample.model_validate(response.json())

    def get_samples(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> MatrixSamplesListResult:
        """Retrieve a list of samples

        Returns a list of [samples](ref:testforms#matrixsample).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            MatrixSamplesListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return MatrixSamplesListResult.model_validate(response.json())

    async def get_samples_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> MatrixSamplesListResult:
        """Retrieve a list of samples (async)

        Returns a list of [samples](ref:testforms#matrixsample).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            MatrixSamplesListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return MatrixSamplesListResult.model_validate(response.json())

    def sample_insertion(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        body: list[Any],
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Insert samples

        Inserts multiple [samples](ref:testforms#matrixsamples) into a
        [matrix](ref:testforms#matrix), and appends new samples to the end of
        the matrix. You can leave columns empty for later use. For new samples,
        provide no IDs; the endpoint generates them.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            body: Request body.
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/insertion",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            json_body=body,
            timeout=timeout,
        )

    async def sample_insertion_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        body: list[Any],
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Insert samples (async)

        Inserts multiple [samples](ref:testforms#matrixsamples) into a
        [matrix](ref:testforms#matrix), and appends new samples to the end of
        the matrix. You can leave columns empty for later use. For new samples,
        provide no IDs; the endpoint generates them.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            body: Request body.
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/insertion",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            json_body=body,
            timeout=timeout,
        )

    def sample_update(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        body: list[Any],
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Update samples

        Updates multiple [samples](ref:testforms#matrixsamples), with the
        requestBody of each specifying columns to update by their IDs. Columns
        not included in the request remain as-is.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            body: Request body.
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/update",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            json_body=body,
            timeout=timeout,
        )

    async def sample_update_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        body: list[Any],
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Update samples (async)

        Updates multiple [samples](ref:testforms#matrixsamples), with the
        requestBody of each specifying columns to update by their IDs. Columns
        not included in the request remain as-is.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            body: Request body.
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/update",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
            },
            json_body=body,
            timeout=timeout,
        )

    def partially_update_sample_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        body: list[Any],
        timeout: Optional[float] = None,
    ) -> MatrixSample:
        """Partially update a single sample

        Partially updates the properties of a
        [sample](ref:testforms#matrixsample). Note: Cell values must always be
        strings, even if they represent a number.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/dataValues/<index>/value`|`replace`|
        |`/resultValues/<index>/value`|`replace`|

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            body: Request body.
            timeout: Override the default request timeout (seconds).

        Returns:
            MatrixSample

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "PATCH",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
            },
            json_body=body,
            timeout=timeout,
        )
        return MatrixSample.model_validate(response.json())

    async def partially_update_sample_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        body: list[Any],
        timeout: Optional[float] = None,
    ) -> MatrixSample:
        """Partially update a single sample (async)

        Partially updates the properties of a
        [sample](ref:testforms#matrixsample). Note: Cell values must always be
        strings, even if they represent a number.
        ### Options
        |Path|PATCH Operations Supported|
        |---|---|
        |`/dataValues/<index>/value`|`replace`|
        |`/resultValues/<index>/value`|`replace`|

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            body: Request body.
            timeout: Override the default request timeout (seconds).

        Returns:
            MatrixSample

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "PATCH",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
            },
            json_body=body,
            timeout=timeout,
        )
        return MatrixSample.model_validate(response.json())

    def get_sample_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> MatrixSample:
        """Retrieve a single sample

        Retrieves a [sample](ref:testforms#matrixsample) given its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            MatrixSample

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return MatrixSample.model_validate(response.json())

    async def get_sample_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> MatrixSample:
        """Retrieve a single sample (async)

        Retrieves a [sample](ref:testforms#matrixsample) given its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            expand: Returns related resources inline with the main resource
            timeout: Override the default request timeout (seconds).

        Returns:
            MatrixSample

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
        return MatrixSample.model_validate(response.json())

    def sample_attachment_upload(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        file_name: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentUploadResponse:
        """Initiate an upload of a sample attachment

        Starts the process to upload and attach a file to a
        [sample](ref:testforms#matrixsample) using a [graph attachment
        upload](ref:testforms#graphattachmentupload) object. The response body
        will include an `uploadUrl`. To upload the file contents, perform a PUT
        on the `uploadUrl` with the same authentication credentials and flow as
        the attachmentUpload request. For more details, see [Authentication
        documentation](ref:authentication).

        The response also includes a `Location` header, which indicates where to
        poll for operation results. For more details on long-running job
        polling, see [Operations endpoint](ref:getoperationbyid).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            file_name: The file name of the graph attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentUploadResponse

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if file_name is not None:
            _body["fileName"] = file_name
        response = self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachmentUpload",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return GraphAttachmentUploadResponse.model_validate(response.json())

    async def sample_attachment_upload_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        file_name: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentUploadResponse:
        """Initiate an upload of a sample attachment (async)

        Starts the process to upload and attach a file to a
        [sample](ref:testforms#matrixsample) using a [graph attachment
        upload](ref:testforms#graphattachmentupload) object. The response body
        will include an `uploadUrl`. To upload the file contents, perform a PUT
        on the `uploadUrl` with the same authentication credentials and flow as
        the attachmentUpload request. For more details, see [Authentication
        documentation](ref:authentication).

        The response also includes a `Location` header, which indicates where to
        poll for operation results. For more details on long-running job
        polling, see [Operations endpoint](ref:getoperationbyid).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            file_name: The file name of the graph attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentUploadResponse

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        _body: dict[str, Any] = {}
        if file_name is not None:
            _body["fileName"] = file_name
        response = await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachmentUpload",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
        return GraphAttachmentUploadResponse.model_validate(response.json())

    def get_sample_attachments(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentsListResult:
        """Retrieve a list of sample attachments

        Returns a list of [attachments](ref:testforms#graphattachment) for a
        [sample](ref:testforms#matrixsample).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentsListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
            },
            timeout=timeout,
        )
        return GraphAttachmentsListResult.model_validate(response.json())

    async def get_sample_attachments_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachmentsListResult:
        """Retrieve a list of sample attachments (async)

        Returns a list of [attachments](ref:testforms#graphattachment) for a
        [sample](ref:testforms#matrixsample).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachmentsListResult

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
            },
            timeout=timeout,
        )
        return GraphAttachmentsListResult.model_validate(response.json())

    def get_sample_attachment_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachment:
        """Retrieve a single sample attachment

        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachment

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = self._client.request(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )
        return GraphAttachment.model_validate(response.json())

    async def get_sample_attachment_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> GraphAttachment:
        """Retrieve a single sample attachment (async)

        Retrieve a single [attachment](ref:testforms#graphattachment) by its ID.

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Returns:
            GraphAttachment

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).
        """
        response = await self._client.request_async(
            "GET",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )
        return GraphAttachment.model_validate(response.json())

    def sample_attachment_download_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a download of a sample attachment

        Asynchronously downloads an attachment from a
        [sample](ref:testforms#matrixsample).

        Responses include a `Location` header, which indicates where to poll for
        download results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the download is ready,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the file, perform a GET on the `resourceURL`
        with the same authentication credentials and flow as the download
        request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}/download",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )

    async def sample_attachment_download_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        attachment_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a download of a sample attachment (async)

        Asynchronously downloads an attachment from a
        [sample](ref:testforms#matrixsample).

        Responses include a `Location` header, which indicates where to poll for
        download results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the download is ready,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the file, perform a GET on the `resourceURL`
        with the same authentication credentials and flow as the download
        request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            attachment_id: The unique identifier of the attachment
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}/download",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
                "attachmentId": attachment_id,
            },
            timeout=timeout,
        )

    def sample_attachment_export_by_id(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        attachment_id: str,
        format_: Optional[Literal["pdf"]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate an export of a sample attachment

        Asynchronously exports an attachment for a
        [sample](ref:testforms#matrixsample) to .PDF.

        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            attachment_id: The unique identifier of the attachment
            format_: The format to export the attachment to — currently, .PDF only
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``client.wait(response).result()`` to poll until completion.
        """
        _body: dict[str, Any] = {}
        if format_ is not None:
            _body["format"] = format_
        return self._client.request(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}/export",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
                "attachmentId": attachment_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )

    async def sample_attachment_export_by_id_async(
        self,
        *,
        test_form_id: str,
        test_phase_id: str,
        matrix_id: str,
        sample_id: str,
        attachment_id: str,
        format_: Optional[Literal["pdf"]] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate an export of a sample attachment (async)

        Asynchronously exports an attachment for a
        [sample](ref:testforms#matrixsample) to .PDF.

        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).

        Args:
            test_form_id: The unique identifier of the test form
            test_phase_id: The unique identifier of the test phase
            matrix_id: The unique identifier of the matrix
            sample_id: The unique identifier of the sample
            attachment_id: The unique identifier of the attachment
            format_: The format to export the attachment to — currently, .PDF only
            timeout: Override the default request timeout (seconds).

        Raises:
            WorkivaAPIError: On API errors (400, 401, 403, 404, 409, 429, 500, 503).

        Note:
            This is a long-running operation (HTTP 202). Use
            ``await client.wait(response).result_async()`` to poll until completion.
        """
        _body: dict[str, Any] = {}
        if format_ is not None:
            _body["format"] = format_
        return await self._client.request_async(
            "POST",
            self._api,
            "/testForms/{testFormId}/testPhases/{testPhaseId}/matrices/{matrixId}/samples/{sampleId}/attachments/{attachmentId}/export",
            path_params={
                "testFormId": test_form_id,
                "testPhaseId": test_phase_id,
                "matrixId": matrix_id,
                "sampleId": sample_id,
                "attachmentId": attachment_id,
            },
            json_body=_body or None,
            timeout=timeout,
        )
