"""Platform API — activities namespace.

Auto-generated by codegen. Do not edit manually.
"""

from __future__ import annotations

from typing import Any, Optional

import httpx

from workiva._constants import _API
from workiva._operations._base import BaseNamespace


class Activities(BaseNamespace):
    """Activities operations."""

    _api: _API = _API.PLATFORM

    def get_activity_by_id(
        self,
        *,
        activity_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single activity

        Retrieves an activity given its ID.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return self._client.request(
            "GET",
            self._api,
            "/activities/{activityId}",
            path_params={
                "activityId": activity_id,
            },
            timeout=timeout,
        )

    async def get_activity_by_id_async(
        self,
        *,
        activity_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single activity (async)

        Retrieves an activity given its ID.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/activities/{activityId}",
            path_params={
                "activityId": activity_id,
            },
            timeout=timeout,
        )

    def get_activity_actions(
        self,
        *,
        maxpagesize: Optional[int] = 1000,
        next_: Optional[str] = None,
        order_by: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of activity actions

        Retrieves a list of actions performed that may produce activities.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return self._client.request(
            "GET",
            self._api,
            "/activityActions",
            query_params={
                "$maxpagesize": maxpagesize,
                "$next": next_,
                "$orderBy": order_by,
            },
            timeout=timeout,
        )

    async def get_activity_actions_async(
        self,
        *,
        maxpagesize: Optional[int] = 1000,
        next_: Optional[str] = None,
        order_by: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of activity actions (async)

        Retrieves a list of actions performed that may produce activities.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/activityActions",
            query_params={
                "$maxpagesize": maxpagesize,
                "$next": next_,
                "$orderBy": order_by,
            },
            timeout=timeout,
        )

    def get_activity_action_by_id(
        self,
        *,
        activity_action_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single activity action

        Returns an action performed, given its ID

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return self._client.request(
            "GET",
            self._api,
            "/activityActions/{activityActionId}",
            path_params={
                "activityActionId": activity_action_id,
            },
            timeout=timeout,
        )

    async def get_activity_action_by_id_async(
        self,
        *,
        activity_action_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single activity action (async)

        Returns an action performed, given its ID

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/activityActions/{activityActionId}",
            path_params={
                "activityActionId": activity_action_id,
            },
            timeout=timeout,
        )

    def get_organization_activities(
        self,
        *,
        organization_id: str,
        filter_: Optional[str] = None,
        maxpagesize: Optional[int] = 1000,
        next_: Optional[str] = None,
        order_by: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of activities for an organization

        Returns a paginated list of activities for a given organization.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return self._client.request(
            "GET",
            self._api,
            "/organizations/{organizationId}/activities",
            path_params={
                "organizationId": organization_id,
            },
            query_params={
                "$filter": filter_,
                "$maxpagesize": maxpagesize,
                "$next": next_,
                "$orderBy": order_by,
            },
            timeout=timeout,
        )

    async def get_organization_activities_async(
        self,
        *,
        organization_id: str,
        filter_: Optional[str] = None,
        maxpagesize: Optional[int] = 1000,
        next_: Optional[str] = None,
        order_by: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of activities for an organization (async)

        Returns a paginated list of activities for a given organization.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/organizations/{organizationId}/activities",
            path_params={
                "organizationId": organization_id,
            },
            query_params={
                "$filter": filter_,
                "$maxpagesize": maxpagesize,
                "$next": next_,
                "$orderBy": order_by,
            },
            timeout=timeout,
        )

    def get_organization_workspace_activities(
        self,
        *,
        organization_id: str,
        workspace_id: str,
        filter_: Optional[str] = None,
        maxpagesize: Optional[int] = 1000,
        next_: Optional[str] = None,
        order_by: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of activities for a workspace

        Returns a paginated list of activities for a given organization and
        workspace.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return self._client.request(
            "GET",
            self._api,
            "/organizations/{organizationId}/workspaces/{workspaceId}/activities",
            path_params={
                "organizationId": organization_id,
                "workspaceId": workspace_id,
            },
            query_params={
                "$filter": filter_,
                "$maxpagesize": maxpagesize,
                "$next": next_,
                "$orderBy": order_by,
            },
            timeout=timeout,
        )

    async def get_organization_workspace_activities_async(
        self,
        *,
        organization_id: str,
        workspace_id: str,
        filter_: Optional[str] = None,
        maxpagesize: Optional[int] = 1000,
        next_: Optional[str] = None,
        order_by: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of activities for a workspace (async)

        Returns a paginated list of activities for a given organization and
        workspace.

        :::{admonition} Attention
        :class: danger
        The Workiva Platform does not guarantee that actions taken in the
        platform will always result in the same Activity ID. Please rely on the
        ActivityAction `alias` field to determine if an activity is relevant to
        your use case.
        :::
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/organizations/{organizationId}/workspaces/{workspaceId}/activities",
            path_params={
                "organizationId": organization_id,
                "workspaceId": workspace_id,
            },
            query_params={
                "$filter": filter_,
                "$maxpagesize": maxpagesize,
                "$next": next_,
                "$orderBy": order_by,
            },
            timeout=timeout,
        )
