"""Platform API — graph namespace.

Auto-generated by codegen. Do not edit manually.
"""

from __future__ import annotations

from typing import Any, Optional

import httpx

from workiva._constants import _API
from workiva._operations._base import BaseNamespace


class Graph(BaseNamespace):
    """Graph operations."""

    _api: _API = _API.PLATFORM

    def create_edits(
        self,
        *,
        body: Edits,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Create new record edits

        Creates new record [edits](ref:graph#edit) given their properties. Each
        edit in the supplied array requires at least an `operation` and
        `targetId`. Up to 1000 edits may be processed per request.
        If there are invalid edits, the error details will include a list of
        errors encountered. Each message will include the zero-based position of
        the failed edit in the provided list of edits.
        """
        return self._client.request(
            "POST",
            self._api,
            "/graph/edits",
            json_body=body,
            timeout=timeout,
        )

    async def create_edits_async(
        self,
        *,
        body: Edits,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Create new record edits (async)

        Creates new record [edits](ref:graph#edit) given their properties. Each
        edit in the supplied array requires at least an `operation` and
        `targetId`. Up to 1000 edits may be processed per request.
        If there are invalid edits, the error details will include a list of
        errors encountered. Each message will include the zero-based position of
        the failed edit in the provided list of edits.
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/graph/edits",
            json_body=body,
            timeout=timeout,
        )

    def get_records(
        self,
        *,
        expand: Optional[str] = None,
        filter_: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of records

        Returns a list of [records](ref:graph#record) matching the provided
        filters. At least one filter is required. If no filter is provided an
        error will be returned.
        """
        return self._client.request(
            "GET",
            self._api,
            "/graph/records",
            query_params={
                "$expand": expand,
                "$filter": filter_,
            },
            timeout=timeout,
        )

    async def get_records_async(
        self,
        *,
        expand: Optional[str] = None,
        filter_: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of records (async)

        Returns a list of [records](ref:graph#record) matching the provided
        filters. At least one filter is required. If no filter is provided an
        error will be returned.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/graph/records",
            query_params={
                "$expand": expand,
                "$filter": filter_,
            },
            timeout=timeout,
        )

    def get_record_by_id(
        self,
        *,
        record_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single record

        Retrieves a [record](ref:graph#record) given its ID. The unique
        identifier is typically a UUID, but it may be a different unique string
        in some cases.
        """
        return self._client.request(
            "GET",
            self._api,
            "/graph/records/{recordId}",
            path_params={
                "recordId": record_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )

    async def get_record_by_id_async(
        self,
        *,
        record_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single record (async)

        Retrieves a [record](ref:graph#record) given its ID. The unique
        identifier is typically a UUID, but it may be a different unique string
        in some cases.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/graph/records/{recordId}",
            path_params={
                "recordId": record_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )

    def graph_report_export(
        self,
        *,
        report_id: str,
        body: GraphReportExport,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a graph report export

        Asynchronously exports a graph report (only CSV available at this time).
        This endpoint will execute the query of a saved report and export to the
        specified format (only CSV available at this time). The ID of the
        [record](ref:graph#record) containing the saved report is used for the
        `reportID` path element. Reports are stored in records of type
        `DataSource` and `ReportView`. The list of applicable records can be
        retrieved from the `/records` endpoint such as `GET
        /records?$filter=type eq DataSource or type eq ReportView`. A filter on
        the `title` property should be used to return a particular report.
        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).
        """
        return self._client.request(
            "POST",
            self._api,
            "/graph/reports/{reportId}/export",
            path_params={
                "reportId": report_id,
            },
            json_body=body,
            timeout=timeout,
        )

    async def graph_report_export_async(
        self,
        *,
        report_id: str,
        body: GraphReportExport,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Initiate a graph report export (async)

        Asynchronously exports a graph report (only CSV available at this time).
        This endpoint will execute the query of a saved report and export to the
        specified format (only CSV available at this time). The ID of the
        [record](ref:graph#record) containing the saved report is used for the
        `reportID` path element. Reports are stored in records of type
        `DataSource` and `ReportView`. The list of applicable records can be
        retrieved from the `/records` endpoint such as `GET
        /records?$filter=type eq DataSource or type eq ReportView`. A filter on
        the `title` property should be used to return a particular report.
        Responses include a `Location` header, which indicates where to poll for
        export results. For more details on long-running job polling, see
        [Operations endpoint](ref:getoperationbyid). When the export completes,
        its status will be `completed`, and the response body includes a
        `resourceURL`. To download the exported file, perform a GET on the
        `resourceURL` with the same authentication credentials and flow as the
        export request. For more details, see [Authentication
        documentation](ref:authentication).
        """
        return await self._client.request_async(
            "POST",
            self._api,
            "/graph/reports/{reportId}/export",
            path_params={
                "reportId": report_id,
            },
            json_body=body,
            timeout=timeout,
        )

    def get_types(
        self,
        *,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of types

        The Types endpoint is used to discover what [types](ref:graph#type) of
        records exist and their attributes. This endpoint lets you know what to
        expect from the Records endpoints.
        """
        return self._client.request(
            "GET",
            self._api,
            "/graph/types",
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )

    async def get_types_async(
        self,
        *,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a list of types (async)

        The Types endpoint is used to discover what [types](ref:graph#type) of
        records exist and their attributes. This endpoint lets you know what to
        expect from the Records endpoints.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/graph/types",
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )

    def get_type_by_id(
        self,
        *,
        type_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single type

        Returns a record [type](ref:graph#type) given its ID (name)
        """
        return self._client.request(
            "GET",
            self._api,
            "/graph/types/{typeId}",
            path_params={
                "typeId": type_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )

    async def get_type_by_id_async(
        self,
        *,
        type_id: str,
        expand: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Retrieve a single type (async)

        Returns a record [type](ref:graph#type) given its ID (name)
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/graph/types/{typeId}",
            path_params={
                "typeId": type_id,
            },
            query_params={
                "$expand": expand,
            },
            timeout=timeout,
        )
