"""Chains API — security namespace.

Auto-generated by codegen. Do not edit manually.
"""

from __future__ import annotations

from typing import Any, Optional

import httpx

from workiva._constants import _API
from workiva._operations._base import BaseNamespace


class Security(BaseNamespace):
    """Security operations."""

    _api: _API = _API.CHAINS

    def get_authorizations_activity(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of authorization activities

        Returns a list of recent authorization activity events.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/authorizations_activity",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    async def get_authorizations_activity_async(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of authorization activities (async)

        Returns a list of recent authorization activity events.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/authorizations_activity",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    def get_login_activity(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of login activity events

        Returns a list of recent login activity events.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/login_activity",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    async def get_login_activity_async(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of login activity events (async)

        Returns a list of recent login activity events.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/login_activity",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    def get_permissions(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of all permissions for a company

        Returns a list of all permissions for a company.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/permissions",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    async def get_permissions_async(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of all permissions for a company (async)

        Returns a list of all permissions for a company.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/permissions",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    def get_user_groups(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of all user groups

        Returns a list of all user groups in a company.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/user_groups",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    async def get_user_groups_async(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of all user groups (async)

        Returns a list of all user groups in a company.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/user_groups",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    def get_user_group(
        self,
        *,
        user_group_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return user group properties

        Return properties for a user group with the provided ID, or a 404 if no
        such user group is found.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/user_groups/{userGroupId}",
            path_params={
                "userGroupId": user_group_id,
            },
            timeout=timeout,
        )

    async def get_user_group_async(
        self,
        *,
        user_group_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return user group properties (async)

        Return properties for a user group with the provided ID, or a 404 if no
        such user group is found.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/user_groups/{userGroupId}",
            path_params={
                "userGroupId": user_group_id,
            },
            timeout=timeout,
        )

    def get_user_group_permissions(
        self,
        *,
        user_group_id: str,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of permissions for a user group

        Returns properties for a user group with the provided ID, or a 404 if no
        such user group is found.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/user_groups/{userGroupId}/permissions",
            path_params={
                "userGroupId": user_group_id,
            },
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    async def get_user_group_permissions_async(
        self,
        *,
        user_group_id: str,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of permissions for a user group (async)

        Returns properties for a user group with the provided ID, or a 404 if no
        such user group is found.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/user_groups/{userGroupId}/permissions",
            path_params={
                "userGroupId": user_group_id,
            },
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    def get_users(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of users

        Returns a list of all users in a particular company.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/users",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    async def get_users_async(
        self,
        *,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of users (async)

        Returns a list of all users in a particular company.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/users",
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    def get_user(
        self,
        *,
        user_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return user properties

        Returns properties for a user with the provided ID, or a 404 if no such
        user is found.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/users/{userId}",
            path_params={
                "userId": user_id,
            },
            timeout=timeout,
        )

    async def get_user_async(
        self,
        *,
        user_id: str,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return user properties (async)

        Returns properties for a user with the provided ID, or a 404 if no such
        user is found.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/users/{userId}",
            path_params={
                "userId": user_id,
            },
            timeout=timeout,
        )

    def get_user_user_groups(
        self,
        *,
        user_id: str,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of user groups

        Returns a list of all groups that a user is a part of in a particular
        company.
        """
        return self._client.request(
            "GET",
            self._api,
            "/v1/security/users/{userId}/groups",
            path_params={
                "userId": user_id,
            },
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )

    async def get_user_user_groups_async(
        self,
        *,
        user_id: str,
        page_size: Optional[int] = None,
        page: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> httpx.Response:
        """Return a list of user groups (async)

        Returns a list of all groups that a user is a part of in a particular
        company.
        """
        return await self._client.request_async(
            "GET",
            self._api,
            "/v1/security/users/{userId}/groups",
            path_params={
                "userId": user_id,
            },
            query_params={
                "pageSize": page_size,
                "page": page,
            },
            timeout=timeout,
        )
