"""Platform API — TypedDict input types.

Auto-generated by codegen. Do not edit manually.

These TypedDict classes allow passing plain dicts to SDK methods
with full IDE autocompletion, instead of importing Pydantic models.
"""

from typing import Any, Literal, Required, TypedDict


class CellRangeParam(TypedDict, total=False):
    start_column: int
    start_row: int
    stop_column: int
    stop_row: int


class ChangeSourceRangeParam(TypedDict, total=False):
    range: Required[dict[str, Any]]
    range_link: Required[str]


class CreateDestinationRangeLinkParam(TypedDict, total=False):
    apply_column_width: bool
    apply_formatting: bool
    source_range_link: Required[str]
    source_table: Required[str]


class CreateSourceRangeLinkParam(TypedDict, total=False):
    range: Required[dict[str, Any]]


class DeleteColumnsParam(TypedDict, total=False):
    columns: dict[str, Any]


class DeleteRowsParam(TypedDict, total=False):
    rows: dict[str, Any]


class DimensionValueParam(TypedDict, total=False):
    active: bool
    id_: str
    name: str


class DocumentExportParam(TypedDict, total=False):
    docx_options: dict[str, Any]
    format_: Required[Literal["pdf", "docx", "xhtml"]]
    pdf_options: dict[str, Any]
    sections: list[str]
    xhtml_options: dict[str, Any]


class DocumentToDocxOptionsParam(TypedDict, total=False):
    include_leader_dots: bool
    show_table_cell_shading: bool


class DocumentToPdfOptionsParam(TypedDict, total=False):
    include_alternate_row_fill: bool
    include_attachment_labels: bool
    include_comments: bool
    include_draft_watermark: bool
    include_hyperlinks: bool
    include_leader_dots: bool
    include_track_changes: bool
    remove_space_from_partial_export: bool
    tag_for_web_accessibility: bool
    use_cmyk_colorspace: bool


class DocumentToXhtmlOptionsParam(TypedDict, total=False):
    editable_simple: bool
    editable_xhtml: bool
    include_external_hyperlinks: bool
    include_headers_and_footers: bool


class DuplicateTableParam(TypedDict, total=False):
    insert_at: Required[dict[str, Any]]
    source_table: Required[str]


class FileCopyOptionsParam(TypedDict, total=False):
    email_on_complete: bool
    include_attachments: bool
    include_automations: bool
    include_comments: bool
    include_document_markup: bool
    include_input_cell_values: bool
    include_outline_labels: bool
    include_smart_link_metadata: bool
    include_wdata_incoming_connections: bool
    include_wdata_outgoing_connections: bool
    include_xbrl: bool
    include_xbrl_disconnected: bool
    keep_input_mode_enabled: bool
    remove_grc_links: bool
    remove_links: bool
    shallow_copy: bool


class FileRestoreOptionsParam(TypedDict, total=False):
    pass


class FileTrashOptionsParam(TypedDict, total=False):
    pass


class FolderExportParam(TypedDict, total=False):
    email_on_complete: bool
    include_attachments: bool
    include_comments: bool
    include_custom_field_values: bool
    include_document_markup: bool
    include_input_cell_values: bool
    include_outline_labels: bool
    include_smart_link_metadata: bool
    include_wdata_incoming_connections: bool
    include_wdata_outgoing_connections: bool
    include_xbrl: bool
    include_xbrl_disconnected: bool
    keep_input_mode_enabled: bool
    remove_grc_links: bool
    remove_links: bool


class FrameworkReferenceParam(TypedDict, total=False):
    framework: Required[str]
    published_version: str
    reference_name: Required[str]


class InsertColumnsParam(TypedDict, total=False):
    count: int
    next_to: int
    side: Literal["putAfter", "putBefore"]


class InsertRowsParam(TypedDict, total=False):
    count: int
    next_to: int
    side: Literal["putAfter", "putBefore"]


class MatrixColumnParam(TypedDict, total=False):
    external_id: str
    id_: str
    name: str


class MetricValueParam(TypedDict, total=False):
    coordinates: dict[str, Any]
    data_source: dict[str, Any]
    fields_to_clear: list[str]
    id_: str
    notes: str
    reporting_period: dict[str, Any]
    status: Literal[
        "notStarted", "notSent", "inProgress", "sentForApproval", "returned", "complete", "error"
    ]
    task: str
    value: str


class MoveColumnsParam(TypedDict, total=False):
    move: dict[str, Any]
    next_to: int
    side: Literal["putAfter", "putBefore"]


class MoveRowsParam(TypedDict, total=False):
    move: dict[str, Any]
    next_to: int
    side: Literal["putAfter", "putBefore"]


class OrganizationUserParam(TypedDict, total=False):
    display_name: str
    email: str
    family_name: str
    given_name: str
    status: Literal["active", "suspended"]
    username: str


class PresentationExportParam(TypedDict, total=False):
    format_: Required[Literal["pdf", "pptx"]]
    pdf_options: dict[str, Any]
    pptx_options: dict[str, Any]
    slides: list[str]


class PresentationToPdfOptionsParam(TypedDict, total=False):
    include_alternate_row_fill: bool
    include_comments: bool
    include_draft_watermark: bool
    include_hyperlinks: bool
    include_leader_dots: bool
    tag_for_web_accessibility: bool
    use_cmyk_colorspace: bool


class PresentationToPptxOptionsParam(TypedDict, total=False):
    include_unused_layout_slides: bool


class RemoveDestinationRangeLinkParam(TypedDict, total=False):
    range_link: Required[str]


class RemoveSourceRangeLinkParam(TypedDict, total=False):
    range_link: Required[str]


class ResourcePermissionParam(TypedDict, total=False):
    permission: Required[str]
    principal: Required[str]


class RichTextSelectionParam(TypedDict, total=False):
    start: Required[dict[str, Any]]
    stop: Required[dict[str, Any]]


class SampleCellParam(TypedDict, total=False):
    column: str
    value: str


class SectionParam(TypedDict, total=False):
    custom_fields: dict[str, Any]
    id_: str
    index: int
    lock: Literal["lock"]
    name: str
    non_printing: bool
    parent: dict[str, Any]


class SectionEditParam(TypedDict, total=False):
    clear_lock: dict[str, Any]
    set_lock: dict[str, Any]
    set_non_printing: dict[str, Any]
    type_: Required[Literal["clearLock", "setLock", "setNonPrinting"]]


class SheetParam(TypedDict, total=False):
    custom_fields: dict[str, Any]
    id_: str
    index: int
    lock: Literal["lock", "inputMode"]
    name: str
    parent: dict[str, Any]
    table: dict[str, Any]


class SheetUpdateApplyBordersParam(TypedDict, total=False):
    borders: Required[list[dict[str, Any]]]


class SheetUpdateApplyFormatsParam(TypedDict, total=False):
    formats: Required[list[dict[str, Any]]]


class SheetUpdateClearBordersParam(TypedDict, total=False):
    ranges: Required[list[dict[str, Any]]]


class SheetUpdateClearFormatsParam(TypedDict, total=False):
    cell_format_fields: list[str]
    clear_value_format_styles: bool
    ranges: Required[list[dict[str, Any]]]
    text_format_fields: list[str]
    value_format_fields: list[str]


class SheetUpdateDeleteColumnsParam(TypedDict, total=False):
    force: bool
    intervals: Required[list[dict[str, Any]]]


class SheetUpdateDeleteRowsParam(TypedDict, total=False):
    force: bool
    intervals: Required[list[dict[str, Any]]]


class SheetUpdateEditCellsParam(TypedDict, total=False):
    cells: Required[list[dict[str, Any]]]
    options: dict[str, Any]


class SheetUpdateEditRangeParam(TypedDict, total=False):
    options: dict[str, Any]
    range: Required[dict[str, Any]]
    values: Required[list[list[dict[str, Any]]]]


class SheetUpdateHideColumnsParam(TypedDict, total=False):
    force: bool
    intervals: Required[list[dict[str, Any]]]


class SheetUpdateHideRowsParam(TypedDict, total=False):
    force: bool
    intervals: Required[list[dict[str, Any]]]


class SheetUpdateInsertColumnsParam(TypedDict, total=False):
    inherit_from: Required[Literal["NONE", "BEFORE", "AFTER"]]
    insertions: Required[list[dict[str, Any]]]


class SheetUpdateInsertRowsParam(TypedDict, total=False):
    inherit_from: Required[Literal["NONE", "BEFORE", "AFTER"]]
    insertions: Required[list[dict[str, Any]]]


class SheetUpdateMergeRangesParam(TypedDict, total=False):
    force: bool
    merge_type: Literal["ALL", "HORIZONTAL", "VERTICAL"]
    ranges: Required[list[dict[str, Any]]]


class SheetUpdateResizeColumnsParam(TypedDict, total=False):
    resize_intervals: Required[dict[str, Any]]


class SheetUpdateResizeColumnsToFitParam(TypedDict, total=False):
    intervals: Required[list[dict[str, Any]]]


class SheetUpdateResizeRowsParam(TypedDict, total=False):
    resize_intervals: Required[dict[str, Any]]


class SheetUpdateResizeRowsToFitParam(TypedDict, total=False):
    intervals: Required[list[dict[str, Any]]]


class SheetUpdateUnhideColumnsParam(TypedDict, total=False):
    intervals: Required[list[dict[str, Any]]]


class SheetUpdateUnhideRowsParam(TypedDict, total=False):
    intervals: Required[list[dict[str, Any]]]


class SheetUpdateUnmergeRangesParam(TypedDict, total=False):
    ranges: Required[list[dict[str, Any]]]


class SolutionParam(TypedDict, total=False):
    id_: str
    name: str


class SpreadsheetExportParam(TypedDict, total=False):
    csv_options: dict[str, Any]
    format_: Required[Literal["pdf", "xlsx", "csv"]]
    pdf_options: dict[str, Any]
    sheets: list[str]
    xlsx_options: dict[str, Any]


class SpreadsheetToCsvOptionsParam(TypedDict, total=False):
    export_as_formulas: bool


class SpreadsheetToPdfOptionsParam(TypedDict, total=False):
    include_comments: bool
    include_draft_watermark: bool
    include_hyperlinks: bool
    include_leader_dots: bool
    include_track_changes: bool
    only_export_print_areas: bool
    page_height: float
    page_orientation: Literal["portrait", "landscape"]
    page_scale: Literal["actualSize", "fitToWidth"]
    page_width: float
    show_cell_fills: bool
    show_gridlines: bool
    use_cmyk_colorspace: bool


class SpreadsheetToXlsxOptionsParam(TypedDict, total=False):
    export_as_formulas: bool
    export_precision: Literal["fullPrecision", "rounded", "displayed"]


class SupportingDocumentImportOptionsParam(TypedDict, total=False):
    container_id: str


class TableCellsEditParam(TypedDict, total=False):
    clear_cells_borders: dict[str, Any]
    clear_cells_format: dict[str, Any]
    clear_cells_properties: dict[str, Any]
    clear_cells_text: dict[str, Any]
    format_cells: dict[str, Any]
    rich_cell_batch_edit: dict[str, Any]
    set_cells_borders: dict[str, Any]
    set_cells_lock: dict[str, Any]
    set_cells_properties: dict[str, Any]
    set_cells_style: dict[str, Any]
    set_cells_text: dict[str, Any]
    set_input_cells: dict[str, Any]
    type_: Required[
        Literal[
            "clearCellsBorders",
            "clearCellsFormat",
            "clearCellsProperties",
            "clearCellsText",
            "formatCells",
            "richCellBatchEdit",
            "setCellsBorders",
            "setCellsLock",
            "setCellsProperties",
            "setCellsStyle",
            "setCellsText",
            "setInputCells",
        ]
    ]


class TableLinksEditParam(TypedDict, total=False):
    insert_cell_destination_link: dict[str, Any]
    remove_cells_link: dict[str, Any]
    rich_cell_link_batch_edit: dict[str, Any]
    type_: Required[
        Literal["insertCellDestinationLink", "removeCellsLink", "richCellLinkBatchEdit"]
    ]


class TableRefParam(TypedDict, total=False):
    table: str


class TagParam(TypedDict, total=False):
    name: Required[str]
    value: Required[str]


class TaskApprovalStepParam(TypedDict, total=False):
    completion_mode: Required[Literal["ONE", "ALL"]]
    due_date: str
    participants: Required[list[dict[str, Any]]]


class TaskLocationParam(TypedDict, total=False):
    resource: str
    segment: str


class TaskUserParam(TypedDict, total=False):
    id_: str
    type_: Literal["USER"]


class TextEditParam(TypedDict, total=False):
    clear_list_format: dict[str, Any]
    clear_paragraph_properties: dict[str, Any]
    clear_text_format: dict[str, Any]
    delete_text: dict[str, Any]
    format_text: dict[str, Any]
    insert_footnote: dict[str, Any]
    insert_image: dict[str, Any]
    insert_page_number: dict[str, Any]
    insert_paragraph: dict[str, Any]
    insert_soft_return: dict[str, Any]
    insert_table: dict[str, Any]
    insert_text: dict[str, Any]
    remove_hyperlinks: dict[str, Any]
    set_hyperlink: dict[str, Any]
    set_list_format: dict[str, Any]
    set_paragraph_properties: dict[str, Any]
    set_paragraph_style: dict[str, Any]
    set_table_properties: dict[str, Any]
    style_text: dict[str, Any]
    type_: Required[
        Literal[
            "clearListFormat",
            "clearParagraphProperties",
            "clearTextFormat",
            "deleteText",
            "formatText",
            "insertFootnote",
            "insertImage",
            "insertPageNumber",
            "insertParagraph",
            "insertSoftReturn",
            "insertTable",
            "insertText",
            "removeHyperlinks",
            "setHyperlink",
            "setListFormat",
            "setParagraphProperties",
            "setParagraphStyle",
            "setTableProperties",
            "styleText",
        ]
    ]


class TextLinkEditParam(TypedDict, total=False):
    insert_destination_link: dict[str, Any]
    remove_links: dict[str, Any]
    type_: Required[Literal["insertDestinationLink", "removeLinks"]]


class WorkivaFileExportParam(TypedDict, total=False):
    workiva_file_export_options: dict[str, Any]


class WorkivaFileImportOptionsParam(TypedDict, total=False):
    create_new_result_container: bool
    destination_container: str
    email_on_complete: bool
    include_attachments: bool
    include_comments: bool
    include_custom_field_values: bool
    include_document_markup: bool
    include_input_cell_values: bool
    include_outline_labels: bool
    include_smart_link_metadata: bool
    include_wdata_incoming_connections: bool
    include_wdata_outgoing_connections: bool
    include_xbrl: bool
    include_xbrl_disconnected: bool
    keep_input_mode_enabled: bool
    new_result_container_name: str


class WorkspaceParam(TypedDict, total=False):
    name: str
    solutions: list[dict[str, Any]]


class WorkspaceMembershipCreationOptionsParam(TypedDict, total=False):
    notify_new_member: bool
    send_welcome_email: bool
